import { AgentOperations } from '../src/modules/agents/operations-port.js';
import { SalesHandoffs } from '../src/modules/sales/handoff.js';
import { workflowChildren } from '../src/modules/workflow/children.js';
import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import type { DataSource } from 'typeorm';
import { migrate } from '../src/kernel/database/migration-runner.js';
import { migrations } from '../src/kernel/database/migrations.js';
import { Chatflows } from '../src/modules/chatflow/application.js';
import { ChatflowEngine } from '../src/modules/chatflow/engine.js';
import { Workflows } from '../src/modules/workflow/application.js';
import { Routing } from '../src/modules/agents/routing.js';
import { Conversations } from '../src/modules/conversation/domain.js';
import { OutboundDispatcher } from '../src/modules/conversation/outbound.js';
import { MockSender } from '../src/modules/channels/mock-sender.js';
import { CrmRecords } from '../src/modules/crm/records.js';
import { coreDomains,contactReferences } from '../src/modules/crm/core.js';
import { LeadService,leadDomain } from '../src/modules/sales/leads.js';
import { tools } from '../src/modules/agents/protocol.js';
import type { Envelope } from '../src/kernel/reliability/delivery.js';
import { workflowActor } from '../src/modules/identity/workflow-port.js';
export function chatflowCases(isolated:(name:string)=>Promise<DataSource>){describe('SRC-020 real Chatflow',()=>{
 let ds:DataSource,app:Chatflows,engine:ChatflowEngine,workflows:Workflows,routing:Routing,conversations:Conversations,contact:string;
 const tenant=randomUUID(),beta=randomUUID(),account=randomUUID(),human=randomUUID(),ai=randomUUID(),role=randomUUID(),team=randomUUID(),policy=randomUUID(),service=randomUUID(),connection=randomUUID();
 const grants=[...['design','publish','operate','read'].map(action=>({resource:'automation',action,scope:'all'})),...['read','reply','update','assign','takeover'].map(action=>({resource:'conversation',action,scope:'all'})),...['create','read','update'].map(action=>({resource:'contact',action,scope:'all'})),...['create','read','qualify'].map(action=>({resource:'lead',action,scope:'all'}))];
 const actions=['conversation.read','conversation.reply','contact.read','lead.create','lead.qualify','routing.request_human'];
 const end={key:'end',type:'end',config:{outcome:'qualified'}};
 const graph=()=>({entry_node:'interest',nodes:[
  {key:'interest',type:'collect',config:{variable_key:'service_interest',value_type:'string',required:true,prompt:'Synthetic interest?'},next:'need'},
  {key:'need',type:'collect',config:{variable_key:'need_summary',value_type:'string',required:true,prompt:'Synthetic need?'},next:'method'},
  {key:'method',type:'collect',config:{variable_key:'preferred_contact_method',value_type:'enum',required:true,choices:['messenger','phone'],prompt:'Synthetic method?'},next:'consent'},
  {key:'consent',type:'collect',config:{variable_key:'contact_permission',value_type:'boolean',required:true,prompt:'Bạn đồng ý để liên hệ?'},next:'validate'},
  {key:'validate',type:'validate_qualification',config:{on_valid:'lead',on_invalid:'human'}},
  {key:'lead',type:'upsert_lead',config:{},next:'end'},
  {key:'human',type:'request_human',config:{reason:'qualification_incomplete',target_chat_team:team},next:'end'},end,
 ]});
 const mutate=(op:any,body:any,id?:string,num?:number,version?:string,key=randomUUID())=>app.mutate(account,tenant,op,body,key,'synthetic-chatflow',id,num,version);
 async function version(g:any=graph()){const d=String((await mutate('create',{key:'c_'+randomUUID().replaceAll('-',''),name:'Synthetic Chatflow'})).body.data.id);const v=String((await mutate('version',{graph:g},d)).body.data.id);await mutate('publish',{},d,1,'1');return {d,v};}
 async function start(g:any=graph(),owner=ai,first='Synthetic service',salesTeam?:string){
  await ds.query('UPDATE workflow_definition SET enabled=0');const cf=await version(g);const wg:any={trigger:{event_type:'conversation.created',connection_id:connection},entry_node:'start',nodes:[{key:'start',type:'start_chatflow',config:{conversation_id:{ref:'trigger.aggregate_id'},chatflow_version_id:cf.v},next:'wait'},{key:'wait',type:'wait_event',config:{event_type:'chatflow.completed',match_key:{ref:'outputs.start.session_id'},timeout_seconds:60},next:'end',on_timeout:'end'},{key:'end',type:'end',config:{outcome:'done'}}]};
  if(salesTeam){wg.nodes[1].next='handoff';wg.nodes.push({key:'handoff',type:'request_lead_handoff',config:{lead_id:{ref:'outputs.wait.lead_id'},target_team_id:salesTeam},next:'sale'},{key:'sale',type:'wait_event',config:{event_type:'lead.accepted',match_key:{ref:'outputs.handoff.handoff_id'},timeout_seconds:900},next:'end',on_timeout:'end'});}
  const wd=String((await workflows.mutate(account,tenant,'create',{key:'w_'+randomUUID().replaceAll('-',''),name:'Synthetic parent',service_actor_id:service},randomUUID(),'synthetic')).body.data.id);await workflows.mutate(account,tenant,'version',{graph:wg,execution_role_id:role},randomUUID(),'synthetic',wd);await workflows.mutate(account,tenant,'publish',{},randomUUID(),'synthetic',wd,1,'1');await workflows.mutate(account,tenant,'enable',{enabled:true},randomUUID(),'synthetic',wd,undefined,'2');
  const identity=randomUUID();await ds.query('INSERT INTO contact_identity(id,tenant_id,connection_id,contact_id,external_subject_id) VALUES (?,?,?,?,?)',[identity,tenant,connection,contact,identity]);
  const received=await conversations.uow.run({tenantId:tenant},s=>conversations.receive(s,{identityId:identity,providerMessageId:randomUUID(),text:first,occurredAt:'2026-10-05T01:00:00Z',correlation:'synthetic'}));await routing.mutate(account,tenant,received.conversationId,false,{owner_principal_id:owner,reason:'manual'},randomUUID(),'1','synthetic');
  const e={event_id:randomUUID(),tenant_id:tenant,event_type:'conversation.created',schema_version:1,aggregate_id:received.conversationId,aggregate_type:'conversation',aggregate_version:'1',data:{contact_id:contact,connection_id:connection},correlation_id:'synthetic',actor:{kind:'system',id:tenant},occurred_at:'2026-10-05T01:00:00Z'} as Envelope;
  await engine.uow.run({tenantId:tenant},s=>workflows.engine.start(s,e));const [run]=await ds.query('SELECT id FROM workflow_run WHERE definition_id=?',[wd]);const claim=(await workflows.engine.claim()).find(c=>c.runId===run.id)!;await workflows.engine.effect(claim);await workflows.engine.finish(claim);const [session]=await ds.query('SELECT id FROM chatflow_session WHERE parent_run_id=?',[run.id]);return {id:session.id as string,c:received.conversationId,first:received.messageId,identity,run:run.id as string,...cf};
 }
 async function row(id:string){return engine.uow.run({tenantId:tenant},s=>engine.lock(s,id));}
 async function claim(id:string){const c=(await engine.claim()).find(c=>c.sessionId===id);expect(c).toBeDefined();return c!;}
 async function step(id:string){const c=await claim(id);await engine.step(c);return c;}
 async function inbound(f:{identity:string},text:string){return conversations.uow.run({tenantId:tenant},s=>conversations.receive(s,{identityId:f.identity,providerMessageId:randomUUID(),text,occurredAt:'2026-10-05T01:00:00Z',correlation:'synthetic'}));}
 async function answers(f:Awaited<ReturnType<typeof start>>,consent='yes'){await inbound(f,'Synthetic need');await inbound(f,'messenger');return inbound(f,consent);}
 async function complete(f:Awaited<ReturnType<typeof start>>,message:string,key=randomUUID(),overrides:any={}){const r=await row(f.id),[c]=await ds.query('SELECT owner_revision FROM crm_record WHERE id=?',[f.c]);return mutate('complete',{qualification:{service_interest:'Synthetic service',need_summary:'Synthetic need',preferred_contact_method:'messenger',contact_permission:true},consent_message_id:message,owner_revision:String(c.owner_revision),...overrides},f.id,undefined,r.version,key);}
 it('v13 upgrade preserves existing records and journals, repeat no-op',async()=>{
    ds=await isolated('chatflow_test');await migrate(ds,migrations.slice(0,13));for(const t of [tenant,beta])await ds.query("INSERT INTO tenant(id,name,status,created_at,updated_at) VALUES (?,'Synthetic','active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[t]);
    const member=randomUUID();await ds.query("INSERT INTO account(id,issuer,subject,display_name,created_at,updated_at) VALUES (?,'https://runtime.invalid',?,'Synthetic',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[account,account]);await ds.query("INSERT INTO membership(id,tenant_id,account_id,status,seat_code,created_at,updated_at) VALUES (?,?,?,'active','admin',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[member,tenant,account]);await ds.query("INSERT INTO principal(id,tenant_id,kind,membership_id,status,created_at,updated_at) VALUES (?,?,'human',?,'active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[human,tenant,member]);
    await ds.query("INSERT INTO `role`(id,tenant_id,`key`,name,permissions,created_at,updated_at) VALUES (?,?,'runtime','Synthetic',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[role,tenant,JSON.stringify(grants)]);await ds.query("INSERT INTO agent_policy(id,tenant_id,`key`,allowed_tools,allowed_actions,timeout_ms,max_tool_calls,created_at,updated_at) VALUES (?,?,'runtime',?,?,30000,5,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[policy,tenant,JSON.stringify(tools),JSON.stringify(actions)]);
    const agent=randomUUID();await ds.query("INSERT INTO ai_agent(id,tenant_id,name,runtime_adapter,policy_id,max_concurrency,created_at,updated_at) VALUES (?,?,'Synthetic','mock',?,1,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[agent,tenant,policy]);await ds.query("INSERT INTO principal(id,tenant_id,kind,ai_agent_id,status,created_at,updated_at) VALUES (?,?,'ai',?,'active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[ai,tenant,agent]);await ds.query("INSERT INTO team(id,tenant_id,name,purpose,created_at,updated_at) VALUES (?,?,'Synthetic','chat',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[team,tenant]);for(const p of [ai,human]){await ds.query('INSERT INTO principal_role VALUES (?,?,?)',[tenant,p,role]);await ds.query('INSERT INTO team_member(tenant_id,team_id,principal_id) VALUES (?,?,?)',[tenant,team,p]);}
    await ds.query("INSERT INTO service_actor(id,tenant_id,`key`,role_id,created_at,updated_at) VALUES (?,?,'runtime',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[service,tenant,role]);for(const key of ['contact','conversation','lead'])await ds.query("INSERT INTO object_type(id,tenant_id,`key`,label,kind,created_at,updated_at) VALUES (?,?,?,?,'standard',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[randomUUID(),tenant,key,key]);
    const records=new CrmRecords(ds,'synthetic',coreDomains());contact=String((await records.mutate(account,tenant,{object:'contact',kind:'records'},{fields:{display_name:'Synthetic runtime contact',normalized_email:'synthetic@example.invalid'}},randomUUID(),undefined,'synthetic')).body.data.id);
    const before=await ds.query('SELECT * FROM crm_record'),journal=await ds.query('SELECT * FROM schema_migration ORDER BY version');expect(await migrate(ds)).toBe(migrations.length-13);expect(await migrate(ds)).toBe(0);expect(await ds.query('SELECT * FROM crm_record')).toEqual(before);expect((await ds.query('SELECT * FROM schema_migration ORDER BY version')).slice(0,13)).toEqual(journal);
    await ds.query("INSERT INTO channel_connection(id,tenant_id,provider,external_account_id,team_id) VALUES (?,?,'mock_messenger','chatflow',?)",[connection,tenant,team]);app=new Chatflows(ds);engine=app.engine;workflows=new Workflows(ds,workflowChildren(ds));routing=new Routing(ds);conversations=new Conversations(ds,'synthetic');
 });
 it('first message predates session; complete real Workflow predicate, one Lead and explicit provenance',async()=>{
  const f=await start();await answers(f);for(let i=0;i<7;i++)await step(f.id);const r=await row(f.id);expect(r.status).toBe('completed');expect(r.variables.service_interest).toBe('Synthetic service');expect(r.provenance.service_interest.message_id).toBe(f.first);expect(await ds.query('SELECT * FROM chatflow_turn WHERE session_id=?',[f.id])).toHaveLength(4);const [lead]=await ds.query('SELECT * FROM `lead` WHERE qualification_session_id=?',[f.id]);expect(lead.status).toBe('qualified');expect(lead.contact_id).toBe(contact);
  const wait=(await workflows.engine.claim()).find(c=>c.runId===f.run)!;await workflows.engine.finish(wait);expect((await ds.query('SELECT current_node FROM workflow_run WHERE id=?',[f.run]))[0].current_node).toBe('end');expect(await ds.query("SELECT id FROM outbox_event WHERE event_type='chatflow.completed' AND aggregate_id=?",[f.id])).toHaveLength(1);
 });
 it('start action replay and active Conversation uniqueness, pinned version, cross-parent predicate rejection',async()=>{
  const f=await start();const r=await row(f.id);await engine.uow.run({tenantId:tenant},async s=>{const access=await workflowActor(s,service,role);const c={runId:f.run,actorId:service,actionKey:r.start_action_key,correlationId:'synthetic',access};expect(await engine.start(s,f.v,f.c,c)).toBe(f.id);});
  await expect(engine.uow.run({tenantId:tenant},async s=>engine.start(s,f.v,f.c,{runId:f.run,actorId:service,actionKey:'new',correlationId:'synthetic',access:await workflowActor(s,service,role)}))).rejects.toThrow('CHATFLOW_ALREADY_ACTIVE');
  await mutate('version',{graph:{entry_node:'end',nodes:[{...end,config:{outcome:'needs_attention'}}]}},f.d);await mutate('publish',{},f.d,2,'2');expect((await row(f.id)).version_id).toBe(f.v);await expect(engine.uow.run({tenantId:tenant},s=>engine.children().result(s,randomUUID(),'chatflow.completed',f.id))).rejects.toThrow('CHATFLOW_PARENT_INVALID');await expect(engine.uow.run({tenantId:beta},s=>engine.lock(s,f.id))).rejects.toThrow('NOT_FOUND');await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,f.run));
 });
 it('lease fencing/restart advances once; waiting prompt is not duplicated',async()=>{
  const f=await start(),old=await claim(f.id);await ds.query('UPDATE chatflow_node_run SET lease_until=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE session_id=?',[f.id]);const fresh=await claim(f.id);await expect(engine.step(old)).rejects.toThrow('CHATFLOW_LEASE_LOST');await new ChatflowEngine(ds).step(fresh);await expect(engine.step(fresh)).rejects.toThrow('CHATFLOW_LEASE_LOST');await step(f.id);await step(f.id);expect(await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id])).toHaveLength(1);expect(await ds.query('SELECT * FROM chatflow_turn WHERE session_id=?',[f.id])).toHaveLength(1);
  const [intent]=await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id]);await new OutboundDispatcher(ds,new MockSender(ds)).dispatch(tenant,f.c,intent.id);expect((await ds.query('SELECT status FROM outbound_intent WHERE id=?',[intent.id]))[0].status).toBe('sent');await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,f.run));
 });
 it('explicit refusal ends immediately without Lead or subsequent prompts',async()=>{
  const f=await start();await answers(f,'không đồng ý');for(let i=0;i<4;i++)await step(f.id);expect((await row(f.id)).outcome).toBe('disqualified');expect(await ds.query('SELECT record_id FROM `lead` WHERE qualification_session_id=?',[f.id])).toHaveLength(0);expect(await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id])).toHaveLength(0);await expect(complete(f,f.first)).rejects.toThrow('FORBIDDEN');
 });
 it('three ambiguous consent turns retain prior variables and route Human',async()=>{
  const f=await start();await answers(f,'maybe');await inbound(f,'yes!');await inbound(f,'not yes');for(let i=0;i<6;i++)await step(f.id);const r=await row(f.id);expect(r.status).toBe('paused_human');expect(r.variables.need_summary).toBe('Synthetic need');expect(r.variables.contact_permission).toBeUndefined();expect((await ds.query('SELECT owner_principal_id FROM crm_record WHERE id=?',[f.c]))[0].owner_principal_id).toBe(human);const yes=await inbound(f,'ĐỒNG Ý');await complete(f,yes.messageId);expect((await row(f.id)).status).toBe('completed');
 });
 it('Human start is paused; completion requires evidence, CAS and owner, and receipt replay returns once',async()=>{
  const f=await start(graph(),human,'yes'),r=await row(f.id);expect(r.status).toBe('paused_human');const payload={qualification:{service_interest:'Synthetic service',need_summary:'Synthetic need',preferred_contact_method:'messenger',contact_permission:true},consent_message_id:f.first,owner_revision:'2'};
  await expect(mutate('complete',payload,f.id,undefined)).rejects.toThrow('VERSION_REQUIRED');await expect(mutate('complete',payload,f.id,undefined,'999')).rejects.toThrow('VERSION_CONFLICT');await expect(mutate('complete',{...payload,owner_revision:'1'},f.id,undefined,r.version)).rejects.toThrow('OWNER_CONFLICT');await expect(mutate('complete',{...payload,consent_message_id:randomUUID()},f.id,undefined,r.version)).rejects.toThrow('CONSENT_MESSAGE_INVALID');
  const key=randomUUID(),result=await mutate('complete',payload,f.id,undefined,r.version,key);expect(await mutate('complete',payload,f.id,undefined,r.version,key)).toEqual(result);await expect(complete(f,f.first)).rejects.toThrow('INVALID_TRANSITION');expect(await ds.query('SELECT record_id FROM `lead` WHERE qualification_session_id=?',[f.id])).toHaveLength(1);expect((await ds.query('SELECT owner_principal_id FROM crm_record WHERE id=?',[f.c]))[0].owner_principal_id).toBe(human);
  await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants.filter(g=>g.resource!=='lead')),role]);await expect(mutate('complete',payload,f.id,undefined,r.version,key)).rejects.toThrow('FORBIDDEN');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);
 });
 it('Human consent rejects other Conversation, ambiguous input and invalid phone atomically',async()=>{
  const f=await start(graph(),human),other=await start(graph(),human,'yes');await expect(complete(f,other.first)).rejects.toThrow('CONSENT_MESSAGE_INVALID');await expect(complete(f,f.first)).rejects.toThrow('CONSENT_MESSAGE_INVALID');const yes=await inbound(f,'yes');await expect(complete(f,yes.messageId,randomUUID(),{qualification:{service_interest:'Synthetic',need_summary:'Synthetic',preferred_contact_method:'phone',phone:'invalid',contact_permission:true}})).rejects.toThrow();expect(await ds.query('SELECT record_id FROM `lead` WHERE qualification_session_id=?',[f.id])).toHaveLength(0);await engine.uow.run({tenantId:tenant},async s=>{await engine.children().cancel(s,f.run);await engine.children().cancel(s,other.run);});
 });
 it('real Runtime is bound to invoke node; takeover preserves draft and rejects late callback, cancels prompt',async()=>{
  const g={entry_node:'agent',nodes:[{key:'agent',type:'invoke_agent',config:{instruction:'ask_need',allowed_tools:[...tools]},next:'end'},{...end,config:{outcome:'needs_attention'}}]};const f=await start(g);await step(f.id);const [execution]=await ds.query('SELECT id FROM agent_execution WHERE session_id=?',[f.id]);await engine.runtime.claim(tenant,execution.id);const [run]=await ds.query('SELECT dispatch_token FROM agent_execution WHERE id=?',[execution.id]);await engine.runtime.accept(tenant,execution.id,run.dispatch_token,{execution_id:execution.id,status:'tool_calls',tool_calls:[{call_id:'save',tool:'qualification.save',arguments:{qualification:{need_summary:'Synthetic retained draft'}}},{call_id:'reply',tool:'conversation.propose_reply',arguments:{text:'Synthetic proposal'}}]});
  expect(await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id])).toHaveLength(0);const [c]=await ds.query('SELECT version FROM crm_record WHERE id=?',[f.c]);await routing.mutate(account,tenant,f.c,true,{reason:'human_takeover'},randomUUID(),String(c.version),'synthetic');const r=await row(f.id);expect(r.status).toBe('paused_human');expect(r.draft.need_summary).toBe('Synthetic retained draft');await engine.runtime.accept(tenant,execution.id,run.dispatch_token,{execution_id:execution.id,status:'completed',proposed_reply:'Late forbidden'});expect((await row(f.id)).draft).toEqual(r.draft);expect(await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id])).toHaveLength(0);
 });
 it('Runtime completion advances exact node and prompt is emitted once by mock',async()=>{
  const f=await start({entry_node:'agent',nodes:[{key:'agent',type:'invoke_agent',config:{instruction:'ask_need',allowed_tools:[]},next:'end'},{...end,config:{outcome:'needs_attention'}}]});await step(f.id);const [e]=await ds.query('SELECT id FROM agent_execution WHERE session_id=?',[f.id]);await engine.runtime.run(tenant,e.id);expect((await row(f.id)).node_key).toBe('end');expect(await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id])).toHaveLength(1);await step(f.id);expect((await row(f.id)).status).toBe('completed');
 });
 it('atomic rollback on final outbox failure preserves no half-created Lead or completed session',async()=>{
  const f=await start(graph(),human,'yes');await ds.query("CREATE TRIGGER fail_chatflow_outbox BEFORE INSERT ON outbox_event FOR EACH ROW BEGIN IF NEW.event_type='chatflow.completed' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic failure'; END IF; END");try{await expect(complete(f,f.first)).rejects.toThrow('synthetic failure');}finally{await ds.query('DROP TRIGGER fail_chatflow_outbox');}expect((await row(f.id)).status).toBe('paused_human');expect(await ds.query('SELECT record_id FROM `lead` WHERE qualification_session_id=?',[f.id])).toHaveLength(0);await complete(f,f.first);
 });
 it('concurrent Human completion produces one terminal transition/Lead; cross-tenant FK cannot be bypassed',async()=>{
  const f=await start(graph(),human,'yes'),results=await Promise.allSettled([complete(f,f.first),complete(f,f.first)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await ds.query('SELECT record_id FROM `lead` WHERE qualification_session_id=?',[f.id])).toHaveLength(1);await expect(ds.query('UPDATE chatflow_session SET tenant_id=? WHERE id=?',[beta,f.id])).rejects.toThrow();await expect(ds.query('UPDATE `lead` SET conversation_id=NULL WHERE qualification_session_id=?',[f.id])).rejects.toThrow();
 });
 it('close/cancel stops sessions and queued work; live service/AI revocation pauses even waiting sessions',async()=>{
  const f=await start();await step(f.id);await step(f.id);const [c]=await ds.query('SELECT version FROM crm_record WHERE id=?',[f.c]);await conversations.mutate(account,tenant,f.c,'transition',{target_status:'closed',reason:'synthetic'},randomUUID(),String(c.version),'synthetic');expect((await row(f.id)).status).toBe('cancelled');
  const g=await start();await ds.query('UPDATE service_actor SET active=0 WHERE id=?',[service]);await engine.tick();expect((await row(g.id)).status).toBe('paused_human');await ds.query('UPDATE service_actor SET active=1 WHERE id=?',[service]);await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,g.run));expect((await row(g.id)).status).toBe('cancelled');
 });
 it('read projection filters draft/provenance and denies revoked Conversation access',async()=>{
  const f=await start();await step(f.id);const [type]=await ds.query("SELECT id FROM object_type WHERE tenant_id=? AND `key`='lead'",[tenant]),field=randomUUID();await ds.query("INSERT INTO field_policy(id,tenant_id,role_id,object_type_id,property_key,denied_actions,created_at,updated_at) VALUES (?,?,?,?,'service_interest',JSON_ARRAY('read'),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[field,tenant,role,type.id]);const data=(await app.read(account,tenant,'session',f.id)).data as any;expect(data.variables).not.toHaveProperty('service_interest');expect(data.provenance).not.toHaveProperty('service_interest');await ds.query('DELETE FROM field_policy WHERE id=?',[field]);await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants.filter(g=>g.resource!=='conversation')),role]);await expect(app.read(account,tenant,'session',f.id)).rejects.toThrow('NOT_FOUND');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,f.run));
 });

 it('expiry after prompt effect rolls back the intent and message, then reclaim emits once',async()=>{
  const f=await start();await step(f.id);const c=await claim(f.id),original=engine.conversations.prompt.bind(engine.conversations);
  engine.conversations.prompt=async(...args)=>{const id=await original(...args);await args[0].query('UPDATE chatflow_node_run SET lease_until=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE session_id=?',[f.id]);return id;};
  try{await expect(engine.step(c)).rejects.toThrow('CHATFLOW_LEASE_LOST');}finally{engine.conversations.prompt=original;}
  expect(await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id])).toHaveLength(0);await engine.step(c);expect(await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id])).toHaveLength(1);await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,f.run));
 });
 it('queued AI send rechecks policy/service and never sends after role revocation',async()=>{
  const f=await start();await step(f.id);await step(f.id);const [intent]=await ds.query('SELECT id FROM outbound_intent WHERE chatflow_session_id=?',[f.id]);await ds.query('UPDATE agent_policy SET allowed_actions=JSON_ARRAY() WHERE id=?',[policy]);try{await new OutboundDispatcher(ds,new MockSender(ds)).dispatch(tenant,f.c,intent.id);}finally{await ds.query('UPDATE agent_policy SET allowed_actions=? WHERE id=?',[JSON.stringify(actions),policy]);}expect((await ds.query('SELECT status FROM outbound_intent WHERE id=?',[intent.id]))[0].status).toBe('cancelled');await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,f.run));
 });
 it('revoked async execution cannot strand a session when current principal remains eligible',async()=>{
  const f=await start({entry_node:'agent',nodes:[{key:'agent',type:'invoke_agent',config:{instruction:'ask_need',allowed_tools:[]},next:'end'},{...end,config:{outcome:'needs_attention'}}]});await step(f.id);await ds.query('UPDATE principal SET auth_revision=auth_revision+1 WHERE id=?',[ai]);await engine.uow.run({tenantId:tenant},s=>engine.runtime.revoke(s,ai));await engine.tick();expect((await row(f.id)).status).toBe('paused_human');await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,f.run));
 });
 it('active session blocks direct Lead mutation and completion qualifies the same existing draft',async()=>{
  const g=graph();g.nodes.splice(1,0,{key:'draft',type:'upsert_lead',config:{},next:'need'} as any);g.nodes[0]!.next='draft';const f=await start(g);await step(f.id);await step(f.id);const r=await row(f.id),domains=coreDomains();domains.set('lead',leadDomain(contactReferences));const records=new CrmRecords(ds,'synthetic',domains),leads=new LeadService(records,contactReferences),[record]=await ds.query('SELECT version FROM crm_record WHERE id=?',[r.lead_id]);await expect(leads.command(account,tenant,r.lead_id,'disqualify',{reason:'synthetic'},randomUUID(),String(record.version),'synthetic')).rejects.toThrow('SESSION_ORCHESTRATION_REQUIRED');await expect(records.mutate(account,tenant,{object:'lead',kind:'records',id:r.lead_id},{fields:{qualification:{need_summary:'Bypass'}}},randomUUID(),String(record.version),'synthetic')).rejects.toThrow('SESSION_ORCHESTRATION_REQUIRED');await answers(f);for(let i=0;i<6;i++)await step(f.id);expect((await row(f.id)).lead_id).toBe(r.lead_id);expect((await ds.query('SELECT status FROM `lead` WHERE record_id=?',[r.lead_id]))[0].status).toBe('qualified');
 });
 it('SRC-021 real Chatflow → Workflow handoff → Sale acceptance preserves Conversation and source',async()=>{
  const salesTeam=randomUUID();await ds.query("INSERT INTO team(id,tenant_id,name,purpose,created_at,updated_at) VALUES (?,?,'Synthetic Sales','sales',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[salesTeam,tenant]);await ds.query('INSERT INTO team_member(tenant_id,team_id,principal_id) VALUES (?,?,?)',[tenant,salesTeam,human]);await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify([...grants,...['handoff','accept'].map(action=>({resource:'lead',action,scope:'all'}))]),role]);
  try{const f=await start(graph(),human,'yes',salesTeam);await complete(f,f.first);const r=await row(f.id),before=await ds.query('SELECT owner_principal_id,owner_revision,team_id,version FROM crm_record WHERE id=?',[f.c]),source=await ds.query('SELECT contact_id,source_touchpoint_id,qualification_session_id FROM `lead` WHERE record_id=?',[r.lead_id]);
   const wait=(await workflows.engine.claim()).find(c=>c.runId===f.run)!;await workflows.engine.finish(wait);const handoff=(await workflows.engine.claim()).find(c=>c.runId===f.run)!;await workflows.engine.effect(handoff);await workflows.engine.finish(handoff);const sales=new SalesHandoffs(ds),h=(await sales.read(account,tenant,r.lead_id)).data[0]!;expect(h.owner_principal_id).toBe(human);await sales.mutate(account,tenant,r.lead_id,h.handoff_id,{owner_revision:h.owner_revision},randomUUID(),h.version,'synthetic');await workflows.engine.finish((await workflows.engine.claim()).find(c=>c.runId===f.run)!);await workflows.engine.finish((await workflows.engine.claim()).find(c=>c.runId===f.run)!);
   expect((await ds.query('SELECT status FROM workflow_run WHERE id=?',[f.run]))[0].status).toBe('completed');expect((await ds.query('SELECT status FROM `lead` WHERE record_id=?',[r.lead_id]))[0].status).toBe('accepted');expect(await ds.query('SELECT owner_principal_id,owner_revision,team_id,version FROM crm_record WHERE id=?',[f.c])).toEqual(before);expect(await ds.query('SELECT contact_id,source_touchpoint_id,qualification_session_id FROM `lead` WHERE record_id=?',[r.lead_id])).toEqual(source);
  }finally{await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);}
 });
 it('SRC-022 run list respects related Conversation permission and excludes raw context',async()=>{
  const f=await start(graph(),human,'yes'),list=await workflows.listRuns(account,tenant,{limit:'50'});expect(list.data.some(r=>r.id===f.run)).toBe(true);const serialized=JSON.stringify(list);expect(serialized).not.toContain('outputs');expect(serialized).not.toContain('Synthetic service');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants.filter(g=>g.resource!=='conversation')),role]);try{expect((await workflows.listRuns(account,tenant,{limit:'50'})).data).toHaveLength(0);}finally{await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);}await engine.uow.run({tenantId:tenant},s=>engine.children().cancel(s,f.run));
 });
 it('SRC-022 Agent Operations only exposes authorized sanitized metadata',async()=>{
  const ops=new AgentOperations(ds),result=await ops.list(account,tenant,{limit:'50'});expect(result.data.length).toBeGreaterThan(0);for(const r of result.data){expect(Object.keys(r).sort()).toEqual(['attention','conversation_id','created_at','error_code','id','status']);}await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants.filter(g=>g.resource!=='conversation')),role]);try{expect((await ops.list(account,tenant,{})).data).toHaveLength(0);}finally{await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);}
 });
});}
