import { it,expect } from 'vitest';
import { FacebookGraph,PageTokenCrypto,facebookConfig,credentialContext } from '../src/modules/channels/facebook-graph.js';
const config={appId:'123',secret:'synthetic-app-secret-only',key:'ab'.repeat(32),origin:'http://localhost:8080'};
const token='synthetic-page-token-only';
it('Facebook credentials are encrypted and bound to tenant, channel, app and Page',()=>{const c=new PageTokenCrypto(config.key),context=credentialContext('tenant','channel','app','page'),sealed=c.seal(token,context);expect(sealed).not.toContain(token);expect(c.open(sealed,context)).toBe(token);expect(()=>c.open(sealed,context+'other')).toThrow('FACEBOOK_CREDENTIAL_UNAVAILABLE');expect(()=>new PageTokenCrypto('bad')).toThrow();expect(()=>c.seal('short',context)).toThrow();});
it('Facebook config fails closed and OAuth URL uses fixed origin and requested permissions',()=>{expect(facebookConfig({})).toBeNull();expect(facebookConfig({FACEBOOK_APP_ID:'123',FACEBOOK_APP_SECRET:config.secret,FACEBOOK_TOKEN_ENCRYPTION_KEY:config.key,APP_ORIGIN:'http://evil.invalid',APP_ENV:'test'})).toBeNull();const url=new URL(new FacebookGraph(config).authorization('synthetic'));expect(url.origin).toBe('https://www.facebook.com');expect(url.searchParams.get('redirect_uri')).toBe(config.origin+'/api/v1/admin/channels/facebook/callback');expect(url.searchParams.get('scope')).toContain('pages_show_list');expect(url.toString()).not.toContain(config.secret);});
it('Graph discovery rebuilds pagination on fixed endpoint and keeps token in Authorization',async()=>{const seen:string[]=[];const graph=new FacebookGraph(config,async(url,init)=>{seen.push(String(url));expect(init?.redirect).toBe('error');if(seen.length===1)return Response.json({access_token:token});expect((init?.headers as any).authorization).toBe('Bearer '+token);expect(String(url)).not.toContain(token);return seen.length===2?Response.json({data:[{id:'1',name:'Synthetic',access_token:token}],paging:{next:'https://evil.invalid/steal',cursors:{after:'opaque-cursor'}}}):Response.json({data:[{id:'2',name:'Synthetic 2',access_token:token}]});});expect(await graph.discover('synthetic-code')).toHaveLength(2);expect(seen.every(u=>u.startsWith('https://graph.facebook.com/v26.0/'))).toBe(true);expect(seen[2]).toContain('after=opaque-cursor');});
it('Graph fails without partial result on protocol failures and never includes provider errors',async()=>{for(const body of [{data:[{id:'1',name:'Synthetic',access_token:'short'}]},{data:[],paging:{next:'next',cursors:{after:''}}},{error:{message:token}}]){let n=0;const graph=new FacebookGraph(config,async()=>Response.json(n++?body:{access_token:token}));await expect(graph.discover('code')).rejects.toThrow(/^FACEBOOK_(INVALID_RESPONSE|API_UNAVAILABLE)$/);}const graph=new FacebookGraph(config,async()=>{throw new Error(token);});await expect(graph.discover('code')).rejects.toThrow('FACEBOOK_API_UNAVAILABLE');});
it('Manual Page token validation cannot bind a token from another Page',async()=>{const graph=new FacebookGraph(config,async()=>Response.json({id:'2'}));await expect(graph.verifyPage(token,'1')).rejects.toThrow('FACEBOOK_PAGE_MISMATCH');});
