import { describe,it,expect } from 'vitest';
import { randomUUID,createHash } from 'node:crypto';
import type { DataSource } from 'typeorm';
import { Module } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { migrate } from '../src/kernel/database/migration-runner.js';
import { migrations } from '../src/kernel/database/migrations.js';
import { FacebookChannels } from '../src/modules/channels/facebook.js';
import { FacebookGraph,PageTokenCrypto,credentialContext } from '../src/modules/channels/facebook-graph.js';
import { FacebookController,FacebookRuntime } from '../src/modules/channels/facebook-http.js';
import { AuthRuntime } from '../src/modules/identity/auth/http.js';
export function facebookCases(isolated:(name:string)=>Promise<DataSource>){describe('SRC-031 Facebook configuration',()=>{
 let ds:DataSource,app:FacebookChannels;const tenant=randomUUID(),beta=randomUUID(),account=randomUUID(),other=randomUUID(),team=randomUUID(),betaTeam=randomUUID(),role=randomUUID(),betaRole=randomUUID();
 const config={appId:'123',secret:'synthetic-app-secret-only',key:'cd'.repeat(32),origin:'http://localhost:8080'},token='synthetic-page-token-never-log',session='synthetic-session',grants=['read','configure'].map(action=>({resource:'integration',action,scope:'all'}));
 let mode='normal',pages=[{id:'100',name:'Synthetic Page',access_token:token}],calls=0;
 const graph=new FacebookGraph(config,async(url)=>{calls++;if(mode==='outage')throw new Error(token);if(String(url).includes('oauth/access_token'))return Response.json({access_token:'synthetic-user-token'});if(String(url).includes('/me?'))return Response.json({id:mode==='wrong-page'?'999':'100'});if(mode==='supersede')await app.begin(account,tenant,session,{team_id:team});if(mode==='revoke')await ds.query('UPDATE `role` SET permissions=JSON_ARRAY() WHERE id=?',[role]);return Response.json({data:pages});});
 const begin=async(t=tenant,tm=team,sid=session)=>new URL((await app.begin(account,t,sid,{team_id:tm})).authorization_url).searchParams.get('state')!;
 const finish=(state:string,sid=session,a=account)=>app.callback(a,sid,{state,code:'synthetic-code'});
 it('schema18 upgrade retains mock connection and enforces real provider metadata',async()=>{ds=await isolated('facebook_test');await migrate(ds,migrations.slice(0,18));for(const [t,tm,r] of [[tenant,team,role],[beta,betaTeam,betaRole]]){await ds.query("INSERT INTO tenant(id,name,status,created_at,updated_at) VALUES (?,'Synthetic','active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[t]);await ds.query("INSERT INTO team(id,tenant_id,name,purpose,created_at,updated_at) VALUES (?,?,'Synthetic','chat',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[tm,t]);await ds.query("INSERT INTO `role`(id,tenant_id,`key`,name,permissions,created_at,updated_at) VALUES (?,?,'synthetic','Synthetic',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[r,t,JSON.stringify(grants)]);}
 for(const a of [account,other])await ds.query("INSERT INTO account(id,issuer,subject,display_name,created_at,updated_at) VALUES (?,'https://synthetic.invalid',?,'Synthetic',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[a,a]);
 for(const [t,r] of [[tenant,role],[beta,betaRole]]){const m=randomUUID(),p=randomUUID();await ds.query("INSERT INTO membership(id,tenant_id,account_id,status,seat_code,created_at,updated_at) VALUES (?,?,?,'active','admin',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[m,t,account]);await ds.query("INSERT INTO principal(id,tenant_id,kind,membership_id,status,created_at,updated_at) VALUES (?,?,'human',?,'active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[p,t,m]);await ds.query('INSERT INTO principal_role VALUES (?,?,?)',[t,p,r]);}
 const id=randomUUID();await ds.query("INSERT INTO channel_connection(id,tenant_id,provider,external_account_id,team_id) VALUES (?,?,'mock_messenger','synthetic-mock',?)",[id,tenant,team]);const before=await ds.query('SELECT * FROM channel_connection');expect(await migrate(ds)).toBe(1);expect(await ds.query('SELECT * FROM channel_connection')).toEqual(before);expect(await migrate(ds)).toBe(0);app=new FacebookChannels(ds,config,graph);
 });
 it('state binds account/session, expires, cancels and cannot replay',async()=>{let state=await begin();await expect(finish(state,'other-session')).rejects.toThrow('FACEBOOK_STATE_INVALID');await expect(finish(state,session,other)).rejects.toThrow('FACEBOOK_STATE_INVALID');expect(await app.callback(account,session,{state,error:'access_denied'})).toBe('cancelled');await expect(finish(state)).rejects.toThrow('FACEBOOK_STATE_INVALID');state=await begin();await ds.query('UPDATE facebook_oauth_attempt SET expires_at=TIMESTAMPADD(MINUTE,-1,UTC_TIMESTAMP(6)) WHERE state_hash=?',[createHash('sha256').update(state).digest('hex')]);await expect(finish(state)).rejects.toThrow('FACEBOOK_STATE_INVALID');const old=await begin();await begin();await expect(finish(old)).rejects.toThrow('FACEBOOK_STATE_INVALID');expect(calls).toBe(0);});
 it('OAuth stores encrypted Page tokens, no secret projections, reconnect preserves channel IDs',async()=>{expect(await finish(await begin())).toBe('connected');const first=(await app.list(account,tenant,{})).data[0];expect(first).toMatchObject({page_id:'100',channel:'messenger',credential_status:'stored'});const [saved]=await ds.query('SELECT * FROM facebook_page WHERE tenant_id=?',[tenant]);expect(saved.token_ciphertext).not.toContain(token);expect(new PageTokenCrypto(config.key).open(saved.token_ciphertext,credentialContext(tenant,first.id,config.appId,'100'))).toBe(token);expect(JSON.stringify(first)).not.toContain(token);expect((await ds.query('SELECT status,provider FROM channel_connection WHERE id=?',[first.id]))[0]).toEqual({status:'disabled',provider:'messenger'});await finish(await begin());expect((await app.list(account,tenant,{})).data[0]).toMatchObject({id:first.id,version:'2'});expect(await ds.query('SELECT * FROM facebook_page')).toHaveLength(1);});
 it('cross-tenant Page conflict rolls back whole batch and no ownership leaks',async()=>{pages=[{id:'099',name:'Synthetic new',access_token:token},...pages];await expect(finish(await begin(beta,betaTeam))).rejects.toThrow('FACEBOOK_PAGE_UNAVAILABLE');expect((await app.list(account,beta,{})).data).toEqual([]);expect(await ds.query("SELECT id FROM channel_connection WHERE tenant_id=? AND provider='messenger'",[beta])).toHaveLength(0);pages=pages.slice(1);});
 it('remote outage and revocation during Graph calls persist no credential mutation',async()=>{const before=await ds.query('SELECT * FROM facebook_page');mode='outage';await expect(finish(await begin())).rejects.toThrow('FACEBOOK_API_UNAVAILABLE');mode='supersede';await expect(finish(await begin())).rejects.toThrow('FACEBOOK_ATTEMPT_SUPERSEDED');mode='revoke';await expect(finish(await begin())).rejects.toThrow('FORBIDDEN');expect(await ds.query('SELECT * FROM facebook_page')).toEqual(before);await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);mode='normal';});
 it('manual replacement validates Page, uses encrypted storage and audit never holds token',async()=>{const [{id}]=(await app.list(account,tenant,{})).data;mode='wrong-page';await expect(app.replaceToken(tenant,id,token)).rejects.toThrow('FACEBOOK_PAGE_MISMATCH');mode='normal';await app.replaceToken(tenant,id,token);expect(JSON.stringify(await ds.query('SELECT * FROM audit_entry'))).not.toContain(token);await expect(app.replaceToken(beta,id,token)).rejects.toThrow('NOT_FOUND');});
 it('HTTP admin connect/list/callback session and CSRF checks with sanitized redirect',async()=>{class TestModule{}Module({controllers:[FacebookController],providers:[{provide:FacebookRuntime,useValue:{ready:async()=>{},facebook:app}},{provide:AuthRuntime,useValue:{service:{session:async()=>({account_id:account}),requireMutation:async(_sid:unknown,_origin:unknown,csrf:unknown)=>{if(csrf!=='synthetic')throw new Error();return {account_id:account};}}}}]})(TestModule);const api=await NestFactory.create(TestModule,{logger:false});api.setGlobalPrefix('api/v1');await api.listen(0,'127.0.0.1');try{const origin=await api.getUrl(),url=origin+'/api/v1/admin/channels/facebook',headers={'content-type':'application/json','x-tenant-id':tenant,cookie:'crm_session='+session,'x-csrf-token':'synthetic'};const denied=await fetch(url+'/connect',{method:'POST',headers:{...headers,'x-csrf-token':''},body:JSON.stringify({team_id:team})});expect(denied.status).not.toBe(200);const r=await fetch(url+'/connect',{method:'POST',headers,body:JSON.stringify({team_id:team})});expect(r.status).toBe(200);const body=await r.json() as any,state=new URL(body.data.authorization_url).searchParams.get('state')!;const callback=await fetch(url+'/callback?'+new URLSearchParams({state,code:'synthetic-code'}),{headers:{cookie:headers.cookie},redirect:'manual'});expect(callback.status).toBe(303);expect(callback.headers.get('location')).toBe('/?facebook=connected');expect(callback.headers.get('referrer-policy')).toBe('no-referrer');expect(await callback.text()).toBe('');const read=await fetch(url+'/pages',{headers});expect(read.status).toBe(200);expect(await read.text()).not.toContain(token);}finally{await api.close();}});
});}
