import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import type { DataSource } from 'typeorm';
import { migrate } from '../src/kernel/database/migration-runner.js';
import { migrations } from '../src/kernel/database/migrations.js';
import { AgentExecutions } from '../src/modules/agents/executions.js';
import { Routing } from '../src/modules/agents/routing.js';
import { Conversations } from '../src/modules/conversation/domain.js';
import { CrmRecords } from '../src/modules/crm/records.js';
import { coreDomains } from '../src/modules/crm/core.js';
import { RuntimeSessionHarness } from './runtime-harness.js';
import { DeterministicMock,tools,type RuntimeAdapter } from '../src/modules/agents/protocol.js';
import { runtimeAccessConsumer } from '../src/modules/agents/runtime-consumer.js';
import { DurableDelivery } from '../src/kernel/reliability/delivery.js';
import { DurableCommands } from '../src/kernel/reliability/commands.js';
export function runtimeCases(isolated:(name:string)=>Promise<DataSource>){describe('SRC-018 guarded Agent Runtime',()=>{
  let ds:DataSource,app:AgentExecutions,routing:Routing,conversations:Conversations,contact:string;
  const tenant=randomUUID(),beta=randomUUID(),account=randomUUID(),human=randomUUID(),ai=randomUUID(),role=randomUUID(),team=randomUUID(),policy=randomUUID(),service=randomUUID(),connection=randomUUID();const harness=new RuntimeSessionHarness();
  const grants=[...['read','reply','update','assign','takeover'].map(action=>({resource:'conversation',action,scope:'all'})),...['create','read','update'].map(action=>({resource:'contact',action,scope:'all'})),...['create','read','qualify'].map(action=>({resource:'lead',action,scope:'all'}))];
  const actions=['conversation.read','conversation.reply','contact.read','lead.create','lead.qualify','routing.request_human'];
  const parse=(v:any)=>typeof v==='string'?JSON.parse(v):v;
  async function setup(){const identity=randomUUID();await ds.query('INSERT INTO contact_identity(id,tenant_id,connection_id,contact_id,external_subject_id) VALUES (?,?,?,?,?)',[identity,tenant,connection,contact,identity]);const received=await conversations.uow.run({tenantId:tenant},s=>conversations.receive(s,{identityId:identity,providerMessageId:randomUUID(),text:'Synthetic context only',occurredAt:'2026-10-05T01:00:00Z',correlation:'synthetic-runtime'}));const c=received.conversationId;await routing.mutate(account,tenant,c,false,{owner_principal_id:ai,reason:'manual'},randomUUID(),'1','synthetic-runtime');const session=randomUUID(),snapshot={id:session,conversationId:c,principalId:ai,ownerRevision:'2',serviceActorId:service,node:'invoke',instruction:'ask_need',allowedTools:[...tools],qualification:{}};await ds.query("INSERT INTO synthetic_runtime_session(tenant_id,id,snapshot,draft,status) VALUES (?,?,?,JSON_OBJECT(),'running')",[tenant,session,JSON.stringify(snapshot)]);return {session,c,message:received.messageId};}
  async function queued(f:Awaited<ReturnType<typeof setup>>,runtime=app,key=randomUUID()){return runtime.uow.run({tenantId:tenant},s=>runtime.start(s,f.session,f.message,key));}
  async function running(f:Awaited<ReturnType<typeof setup>>){const {id}=await queued(f);const request=await app.claim(tenant,id);expect(request).not.toBeNull();const [row]=await ds.query('SELECT dispatch_token FROM agent_execution WHERE id=?',[id]);return {id,token:row.dispatch_token,request:request!};}
  async function row(id:string){return (await ds.query('SELECT * FROM agent_execution WHERE id=?',[id]))[0];}
  async function state(session:string){const [r]=await ds.query('SELECT * FROM synthetic_runtime_session WHERE id=?',[session]);return {...r,draft:parse(r.draft)};}
  const call=(id:string,tool:string,args:Record<string,unknown>,call_id='call1')=>({execution_id:id,status:'tool_calls',tool_calls:[{call_id,tool,arguments:args}]});
  it('v11 to v12 preserves principals/owners and immutable journals; repeat no-op',async()=>{
    ds=await isolated('runtime_test');await migrate(ds,migrations.slice(0,11));for(const t of [tenant,beta])await ds.query("INSERT INTO tenant(id,name,status,created_at,updated_at) VALUES (?,'Synthetic','active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[t]);
    const member=randomUUID();await ds.query("INSERT INTO account(id,issuer,subject,display_name,created_at,updated_at) VALUES (?,'https://runtime.invalid',?,'Synthetic',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[account,account]);await ds.query("INSERT INTO membership(id,tenant_id,account_id,status,seat_code,created_at,updated_at) VALUES (?,?,?,'active','admin',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[member,tenant,account]);await ds.query("INSERT INTO principal(id,tenant_id,kind,membership_id,status,created_at,updated_at) VALUES (?,?,'human',?,'active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[human,tenant,member]);
    await ds.query("INSERT INTO `role`(id,tenant_id,`key`,name,permissions,created_at,updated_at) VALUES (?,?,'runtime','Synthetic',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[role,tenant,JSON.stringify(grants)]);await ds.query("INSERT INTO agent_policy(id,tenant_id,`key`,allowed_tools,allowed_actions,timeout_ms,max_tool_calls,created_at,updated_at) VALUES (?,?,'runtime',?,?,30000,5,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[policy,tenant,JSON.stringify(tools),JSON.stringify(actions)]);
    const agent=randomUUID();await ds.query("INSERT INTO ai_agent(id,tenant_id,name,runtime_adapter,policy_id,max_concurrency,created_at,updated_at) VALUES (?,?,'Synthetic','mock',?,1,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[agent,tenant,policy]);await ds.query("INSERT INTO principal(id,tenant_id,kind,ai_agent_id,status,created_at,updated_at) VALUES (?,?,'ai',?,'active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[ai,tenant,agent]);await ds.query("INSERT INTO team(id,tenant_id,name,purpose,created_at,updated_at) VALUES (?,?,'Synthetic','chat',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[team,tenant]);for(const p of [ai,human]){await ds.query('INSERT INTO principal_role VALUES (?,?,?)',[tenant,p,role]);await ds.query('INSERT INTO team_member(tenant_id,team_id,principal_id) VALUES (?,?,?)',[tenant,team,p]);}
    await ds.query("INSERT INTO service_actor(id,tenant_id,`key`,role_id,created_at,updated_at) VALUES (?,?,'runtime',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[service,tenant,role]);for(const key of ['contact','conversation','lead'])await ds.query("INSERT INTO object_type(id,tenant_id,`key`,label,kind,created_at,updated_at) VALUES (?,?,?,?,'standard',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[randomUUID(),tenant,key,key]);
    const records=new CrmRecords(ds,'synthetic',coreDomains());contact=String((await records.mutate(account,tenant,{object:'contact',kind:'records'},{fields:{display_name:'Synthetic runtime contact',normalized_email:'synthetic@example.invalid'}},randomUUID(),undefined,'synthetic')).body.data.id);
    const before=await ds.query('SELECT * FROM crm_record'),journal=await ds.query('SELECT * FROM schema_migration ORDER BY version');expect(await migrate(ds)).toBe(1);expect(await migrate(ds)).toBe(0);expect(await ds.query('SELECT * FROM crm_record')).toEqual(before);expect((await ds.query('SELECT * FROM schema_migration ORDER BY version')).slice(0,11)).toEqual(journal);
    await ds.query("INSERT INTO channel_connection(id,tenant_id,provider,external_account_id,team_id) VALUES (?,?,'mock_messenger','runtime',?)",[connection,tenant,team]);await harness.install(ds);app=new AgentExecutions(ds,harness);routing=new Routing(ds);conversations=new Conversations(ds,'synthetic');
  });
  it('production default has no fake session; tenant binding and action key replay are strict',async()=>{
    const f=await setup();await expect(queued(f,new AgentExecutions(ds))).rejects.toThrow('SESSION_NOT_AVAILABLE');const key=randomUUID(),first=await queued(f,app,key);expect(await queued(f,app,key)).toEqual(first);await expect(app.uow.run({tenantId:beta},s=>app.start(s,f.session,f.message,key))).rejects.toThrow('SESSION_NOT_AVAILABLE');await app.run(tenant,first.id);expect((await row(first.id)).status).toBe('completed');expect(await queued(f,app,key)).toEqual({id:first.id,status:'completed'});expect((await state(f.session)).reply).toContain('dịch vụ');expect(await ds.query('SELECT * FROM outbound_intent WHERE conversation_id=?',[f.c])).toHaveLength(0);
  });
  it('context capped20, field-redacted Contact, no transcript persisted in request/audit',async()=>{
    const f=await setup();for(let n=0;n<23;n++)await ds.query("INSERT INTO message(id,tenant_id,conversation_id,connection_id,provider_message_id,direction,text,occurred_at,received_at,status) VALUES (?,?,?,?,?,'inbound',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),'received')",[randomUUID(),tenant,f.c,connection,randomUUID(),`Synthetic bounded ${n}`]);
    const [type]=await ds.query("SELECT id FROM object_type WHERE tenant_id=? AND `key`='contact'",[tenant]),field=randomUUID();await ds.query("INSERT INTO field_policy(id,tenant_id,role_id,object_type_id,property_key,denied_actions,created_at,updated_at) VALUES (?,?,?,?,'normalized_email',JSON_ARRAY('read'),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[field,tenant,role,type.id]);const r=await running(f);expect(r.request.context.messages).toHaveLength(20);expect(r.request.context.contact).not.toHaveProperty('normalized_email');expect(JSON.stringify(parse((await row(r.id)).request))).not.toContain('Synthetic bounded');await ds.query('DELETE FROM field_policy WHERE id=?',[field]);await app.accept(tenant,r.id,r.token,{execution_id:r.id,status:'completed'});
  });
  it('tool call replay applies one draft, changed arguments conflict, consent injection denied',async()=>{
    const f=await setup(),r=await running(f),body=call(r.id,'qualification.save',{qualification:{need_summary:'Synthetic need'}});await app.accept(tenant,r.id,r.token,body);await app.accept(tenant,r.id,r.token,body);expect((await state(f.session)).effects).toBe(1);expect(await ds.query('SELECT * FROM tool_execution WHERE agent_execution_id=?',[r.id])).toHaveLength(1);await expect(app.accept(tenant,r.id,r.token,call(r.id,'qualification.save',{qualification:{need_summary:'Changed'}}))).rejects.toThrow('TOOL_CALL_CONFLICT');await expect(app.accept(tenant,r.id,r.token,call(r.id,'qualification.save',{qualification:{contact_permission:true}},'consent'))).rejects.toThrow('RUNTIME_PROTOCOL_INVALID');expect((await state(f.session)).draft).not.toHaveProperty('contact_permission');await app.accept(tenant,r.id,r.token,{execution_id:r.id,status:'completed'});
  });
  it('batch forbidden tool rolls back earlier tool and effect; unknown tool never executes',async()=>{
    const f=await setup(),r=await running(f);const body={execution_id:r.id,status:'tool_calls',tool_calls:[{call_id:'ok',tool:'qualification.save',arguments:{qualification:{service_interest:'Synthetic'}}},{call_id:'bad',tool:'crm.read_contact',arguments:{contact_id:randomUUID()}}]};await expect(app.accept(tenant,r.id,r.token,body)).rejects.toThrow('TOOL_FORBIDDEN');expect((await state(f.session)).effects).toBe(0);expect(await ds.query('SELECT * FROM tool_execution WHERE agent_execution_id=?',[r.id])).toHaveLength(0);await expect(app.accept(tenant,r.id,r.token,call(r.id,'arbitrary.sql',{sql:'SELECT 1'}))).rejects.toThrow('RUNTIME_PROTOCOL_INVALID');await app.fail(tenant,r.id,r.token,'TOOL_FORBIDDEN');expect((await state(f.session)).status).toBe('paused_human');expect((await row(r.id)).status).toBe('failed');
  });
  it('five calls across continuations enforced; replay does not consume another call',async()=>{
    const f=await setup(),r=await running(f);for(let i=0;i<5;i++)await app.accept(tenant,r.id,r.token,call(r.id,'conversation.propose_reply',{text:'Synthetic proposal'},`c${i}`));await app.accept(tenant,r.id,r.token,call(r.id,'conversation.propose_reply',{text:'Synthetic proposal'},'c0'));await expect(app.accept(tenant,r.id,r.token,call(r.id,'conversation.propose_reply',{text:'Sixth'},'c5'))).rejects.toThrow('TOOL_LIMIT');expect((await state(f.session)).effects).toBe(5);await app.fail(tenant,r.id,r.token,'TOOL_LIMIT');
  });
  it('live field deny, policy content change and service revocation reject results',async()=>{
    for(const kind of ['field','policy','service']){const f=await setup(),r=await running(f);let field:string|undefined;
      if(kind==='field'){const [type]=await ds.query("SELECT id FROM object_type WHERE tenant_id=? AND `key`='lead'",[tenant]);field=randomUUID();await ds.query("INSERT INTO field_policy(id,tenant_id,role_id,object_type_id,property_key,denied_actions,created_at,updated_at) VALUES (?,?,?,?,'need_summary',JSON_ARRAY('write'),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[field,tenant,role,type.id]);}
      if(kind==='policy')await ds.query('UPDATE agent_policy SET max_tool_calls=4 WHERE id=?',[policy]);if(kind==='service')await ds.query('UPDATE service_actor SET auth_revision=auth_revision+1 WHERE id=?',[service]);
      await expect(app.accept(tenant,r.id,r.token,call(r.id,'qualification.save',{qualification:{need_summary:'Denied'}}))).rejects.toThrow(kind==='field'?'TOOL_FORBIDDEN':'RUNTIME_AUTH_REVOKED');expect((await state(f.session)).effects).toBe(0);
      if(field)await ds.query('DELETE FROM field_policy WHERE id=?',[field]);if(kind==='policy')await ds.query('UPDATE agent_policy SET max_tool_calls=5 WHERE id=?',[policy]);await app.fail(tenant,r.id,r.token,'RUNTIME_AUTH_REVOKED');
    }
  });
  it('takeover atomically cancels execution/tools, releases slot and rejects late output; draft retained',async()=>{
    const f=await setup(),r=await running(f);await app.accept(tenant,r.id,r.token,call(r.id,'qualification.save',{qualification:{need_summary:'Retained synthetic'}}));await routing.mutate(account,tenant,f.c,true,{reason:'human_takeover'},randomUUID(),'2','synthetic');expect((await row(r.id)).status).toBe('cancelled');expect((await ds.query('SELECT status FROM tool_execution WHERE agent_execution_id=?',[r.id]))[0].status).toBe('cancelled');expect((await ds.query('SELECT released_at FROM agent_capacity_slot WHERE execution_id=?',[r.id]))[0].released_at).not.toBeNull();await app.accept(tenant,r.id,r.token,{execution_id:r.id,status:'completed',proposed_reply:'Too late'});expect((await state(f.session)).draft.need_summary).toBe('Retained synthetic');expect((await state(f.session)).reply).toBeNull();
  });
  it('close cancels queued execution; stale token cannot write current result',async()=>{
    const f=await setup(),q=await queued(f);await conversations.mutate(account,tenant,f.c,'transition',{target_status:'closed',reason:'Synthetic'},randomUUID(),'2','synthetic');expect((await row(q.id)).status).toBe('cancelled');const g=await setup(),r=await running(g);expect((await app.accept(tenant,r.id,randomUUID(),{execution_id:r.id,status:'completed',proposed_reply:'Stale'})).terminal).toBe(true);expect((await state(g.session)).reply).toBeNull();await app.accept(tenant,r.id,r.token,{execution_id:r.id,status:'completed'});
  });
  it('expired running recovery hands to Human without repeating runtime; late result cannot change owner',async()=>{
    const f=await setup(),r=await running(f);await ds.query('UPDATE agent_execution SET expires_at=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE id=?',[r.id]);await app.tick();expect((await row(r.id)).status).toBe('timed_out');expect((await state(f.session)).status).toBe('paused_human');const before=(await conversations.read(account,tenant,f.c)).data;expect((before as any).owner_principal_id).toBe(human);await app.accept(tenant,r.id,r.token,{execution_id:r.id,status:'completed',proposed_reply:'Late'});expect((await conversations.read(account,tenant,f.c)).data).toEqual(before);
  });
  it('capacity queued30s, queue expiry routes Human, available queued claim later succeeds',async()=>{
    const f=await setup(),g=await setup(),r=await running(f),q=await queued(g);expect(await app.claim(tenant,q.id)).toBeNull();await ds.query('UPDATE agent_execution SET queued_until=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE id=?',[q.id]);expect(await app.claim(tenant,q.id)).toBeNull();expect((await row(q.id)).error_code).toBe('CAPACITY_TIMEOUT');await app.accept(tenant,r.id,r.token,{execution_id:r.id,status:'completed'});
    const h=await setup(),fresh=await queued(h);await app.run(tenant,fresh.id);expect((await row(fresh.id)).status).toBe('completed');
  });
  it('slow session effect cannot commit past deadline; all draft/tool writes rollback',async()=>{
    const f=await setup(),r=await running(f),slow=Object.create(harness) as RuntimeSessionHarness;slow.saveDraft=async(s,id,value)=>{await harness.saveDraft(s,id,value);await s.query('UPDATE agent_execution SET expires_at=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE tenant_id=? AND id=?',[tenant,r.id]);};const runtime=new AgentExecutions(ds,slow);await expect(runtime.accept(tenant,r.id,r.token,call(r.id,'qualification.save',{qualification:{need_summary:'Rolled back'}}))).rejects.toThrow('RUNTIME_DEADLINE');expect((await state(f.session)).effects).toBe(0);expect(await ds.query('SELECT * FROM tool_execution WHERE agent_execution_id=?',[r.id])).toHaveLength(0);await app.fail(tenant,r.id,r.token,'RUNTIME_DEADLINE');
  });
  it('real adapter timeout bounded; runtime failures sanitized; cancel best effort after commit',async()=>{
    await ds.query('UPDATE agent_policy SET timeout_ms=100 WHERE id=?',[policy]);const f=await setup();let cancelled=0;const adapter:RuntimeAdapter={execute:async()=>new Promise(()=>{}),cancel:async()=>{cancelled++;}},runtime=new AgentExecutions(ds,harness,adapter),q=await queued(f,runtime);await runtime.run(tenant,q.id);expect((await row(q.id)).status).toBe('timed_out');expect(cancelled).toBe(0);await runtime.cancelExternal();expect(cancelled).toBeGreaterThan(0);await ds.query('UPDATE agent_policy SET timeout_ms=30000 WHERE id=?',[policy]);
  });
  it('late adapter promise after takeover is discarded with no reply effect',async()=>{
    const f=await setup();let resolve!:(v:unknown)=>void,started!:()=>void;const entered=new Promise<void>(r=>{started=r;}),adapter:RuntimeAdapter={execute:async()=>{started();return new Promise(r=>{resolve=r;});},cancel:async()=>{}},runtime=new AgentExecutions(ds,harness,adapter),q=await queued(f,runtime),work=runtime.run(tenant,q.id);await entered;await routing.mutate(account,tenant,f.c,true,{reason:'human_takeover'},randomUUID(),'2','synthetic');resolve({execution_id:q.id,status:'completed',proposed_reply:'Forbidden late synthetic'});await work;expect((await state(f.session)).reply).toBeNull();expect((await row(q.id)).status).toBe('cancelled');
  });
  it('durable disable consumer cancels execution using live auth and keeps owner stable',async()=>{
    const f=await setup(),r=await running(f);await ds.query("UPDATE principal SET status='suspended',auth_revision=auth_revision+1 WHERE id=?",[ai]);await app.uow.run({tenantId:tenant},s=>new DurableCommands().accessChanged(s,human,'synthetic-runtime-disable',{id:ai,version:'2',auth_revision:'2'}));const delivery=new DurableDelivery(ds),[event]=await ds.query("SELECT id FROM outbox_event WHERE correlation_id='synthetic-runtime-disable'"),claim=(await delivery.claim()).find(c=>c.eventId===event.id)!;await delivery.consume(claim,runtimeAccessConsumer(app));await delivery.consume(claim,runtimeAccessConsumer(app));expect((await row(r.id)).status).toBe('cancelled');expect(((await conversations.read(account,tenant,f.c)).data as any).owner_principal_id).toBe(ai);await ds.query("UPDATE principal SET status='active',auth_revision=auth_revision+1 WHERE id=?",[ai]);
  });
  it('private mock continuation exercises approved tools and explicit Human handoff',async()=>{
    const f=await setup();let turn=0;const adapter:RuntimeAdapter={execute:async request=>++turn===1?call(request.execution_id,'qualification.save',{qualification:{service_interest:'Synthetic service'}}):call(request.execution_id,'routing.request_human',{reason:'request_human'},'handoff'),cancel:async()=>{}},runtime=new AgentExecutions(ds,harness,adapter),q=await queued(f,runtime);await runtime.run(tenant,q.id);expect((await state(f.session)).draft.service_interest).toBe('Synthetic service');expect((await state(f.session)).status).toBe('paused_human');expect((await row(q.id)).status).toBe('completed');
  });
  it('session tool subset rejects known but unapproved tools; revoked service prevents unauthorized fallback',async()=>{
    const f=await setup();const [session]=await ds.query('SELECT snapshot FROM synthetic_runtime_session WHERE id=?',[f.session]);const snapshot=parse(session.snapshot);snapshot.allowedTools=['conversation.propose_reply'];await ds.query('UPDATE synthetic_runtime_session SET snapshot=? WHERE id=?',[JSON.stringify(snapshot),f.session]);
    const adapter:RuntimeAdapter={execute:async request=>call(request.execution_id,'qualification.save',{qualification:{need_summary:'Unapproved'}}),cancel:async()=>{}},runtime=new AgentExecutions(ds,harness,adapter),q=await queued(f,runtime);await runtime.run(tenant,q.id);expect((await row(q.id)).error_code).toBe('TOOL_FORBIDDEN');expect((await state(f.session)).effects).toBe(0);
    const g=await setup(),r=await running(g);await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants.filter(g=>g.action!=='assign')),role]);await app.fail(tenant,r.id,r.token,'RUNTIME_FAILURE');expect((await row(r.id)).attention).toBe(1);expect(((await conversations.read(account,tenant,g.c)).data as any).owner_principal_id).toBe(ai);expect((await state(g.session)).status).toBe('running');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);
  });
  it('Contact tool replay reprojects newly denied fields, worker tick does not block on runtime',async()=>{
    const f=await setup(),r=await running(f),body=call(r.id,'crm.read_contact',{contact_id:contact});const first=await app.accept(tenant,r.id,r.token,body);expect(first.results[0]!.result).toHaveProperty('normalized_email');
    const [type]=await ds.query("SELECT id FROM object_type WHERE tenant_id=? AND `key`='contact'",[tenant]),field=randomUUID();await ds.query("INSERT INTO field_policy(id,tenant_id,role_id,object_type_id,property_key,denied_actions,created_at,updated_at) VALUES (?,?,?,?,'normalized_email',JSON_ARRAY('read'),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[field,tenant,role,type.id]);expect((await app.accept(tenant,r.id,r.token,body)).results[0]!.result).not.toHaveProperty('normalized_email');await ds.query('DELETE FROM field_policy WHERE id=?',[field]);await app.accept(tenant,r.id,r.token,{execution_id:r.id,status:'completed'});
    const g=await setup();let resolve!:(v:unknown)=>void,started!:()=>void;const entered=new Promise<void>(r=>{started=r;}),runtime=new AgentExecutions(ds,harness,{execute:async()=>{started();return new Promise(r=>{resolve=r;});},cancel:async()=>{}}),q=await queued(g,runtime);await runtime.tick();await entered;expect((await row(q.id)).status).toBe('running');resolve({execution_id:q.id,status:'completed'});await runtime.drain();expect((await row(q.id)).status).toBe('completed');
  });
  it('tenant FK and sanitized evidence; no public runtime API introduced',async()=>{
    const f=await setup(),q=await queued(f);await expect(ds.query('UPDATE agent_execution SET tenant_id=? WHERE id=?',[beta,q.id])).rejects.toThrow();await app.run(tenant,q.id);const audit=JSON.stringify(await ds.query('SELECT * FROM audit_entry'));for(const text of ['Synthetic context only','Retained synthetic','Forbidden late synthetic','Synthetic service'])expect(audit).not.toContain(text);expect(new DeterministicMock()).not.toHaveProperty('fixtures');
  });
});}
