import { describe,it,expect,beforeEach } from 'vitest';
import { randomUUID } from 'node:crypto';
import type { DataSource } from 'typeorm';
import { Module } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { migrate } from '../src/kernel/database/migration-runner.js';
import { migrations } from '../src/kernel/database/migrations.js';
import { CrmRecords } from '../src/modules/crm/records.js';
import { coreDomains,contactReferences } from '../src/modules/crm/core.js';
import { LeadService,leadDomain } from '../src/modules/sales/leads.js';
import { SalesHandoffs } from '../src/modules/sales/handoff.js';
import { CrmController,CrmRuntime } from '../src/modules/crm/http.js';
import { AuthRuntime } from '../src/modules/identity/auth/http.js';
import { AuthError } from '../src/modules/identity/auth/security.js';
import { Workflows } from '../src/modules/workflow/application.js';
import { WorkflowEngine } from '../src/modules/workflow/engine.js';
import { workflowChildren } from '../src/modules/workflow/children.js';
import { IdentityAuthorization } from '../src/modules/identity/authorization.js';
import type { Envelope } from '../src/kernel/reliability/delivery.js';
export function salesHandoffCases(isolated:(name:string)=>Promise<DataSource>){describe('SRC-021 Sales handoff',()=>{
 let ds:DataSource,records:CrmRecords,leads:LeadService,sales:SalesHandoffs,workflows:Workflows;
 const tenant=randomUUID(),beta=randomUUID(),admin=randomUUID(),principal=randomUUID(),role=randomUUID(),team=randomUUID(),chatTeam=randomUUID(),service=randomUUID(),connection=randomUUID();
 const sellers=[{account:randomUUID(),principal:randomUUID(),role:randomUUID()},{account:randomUUID(),principal:randomUUID(),role:randomUUID()}];
 const grants=[...['contact','lead'].flatMap(resource=>['create','read','update','qualify','handoff','accept','assign'].map(action=>({resource,action,scope:'all'}))),...['design','publish','operate','read'].map(action=>({resource:'automation',action,scope:'all'}))];
 const sellerGrants=[...['read','accept'].map(action=>({resource:'lead',action,scope:'team'})),...['read','update'].map(action=>({resource:'contact',action,scope:'team'}))];
 beforeEach(async()=>{if(!sales)return;await available(true);for(const p of sellers){await ds.query("UPDATE membership SET seat_code='sales' WHERE account_id=?",[p.account]);await ds.query('UPDATE team_member SET active=1 WHERE principal_id=?',[p.principal]);await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(sellerGrants),p.role]);}});
 async function qualified(){const contact=String((await records.mutate(admin,tenant,{object:'contact',kind:'records'},{fields:{display_name:'Synthetic Sales contact'}},randomUUID(),undefined,'synthetic')).body.data.id),id=String((await leads.create(admin,tenant,{contact_id:contact},randomUUID(),'synthetic')).body.data.id);await leads.command(admin,tenant,id,'qualification',{qualification:{service_interest:'Synthetic',need_summary:'Synthetic need',contact_permission:true,preferred_contact_method:'messenger',consent_evidence:{kind:'manual',note:'Synthetic consent'}}},randomUUID(),'1','synthetic');return {id,contact};}
 const request=(id:string,key=randomUUID(),target=team,version='2')=>sales.mutate(admin,tenant,id,undefined,{target_team_id:target},key,version,'synthetic');
 async function accept(id:string,h:any,seller=sellers[0]!,key=randomUUID()){return sales.mutate(seller.account,tenant,id,h.handoff_id,{owner_revision:h.owner_revision},key,h.version,'synthetic');}
 async function available(value:boolean){for(const p of sellers)await ds.query('UPDATE principal SET availability=? WHERE id=?',[value?'available':'unavailable',p.principal]);}
 async function workflow(id:string){await ds.query('UPDATE workflow_definition SET enabled=0');const graph={trigger:{event_type:'conversation.created',connection_id:connection},entry_node:'handoff',nodes:[{key:'handoff',type:'request_lead_handoff',config:{lead_id:id,target_team_id:team},next:'wait'},{key:'wait',type:'wait_event',config:{event_type:'lead.accepted',match_key:{ref:'outputs.handoff.handoff_id'},timeout_seconds:900},next:'end',on_timeout:'end'},{key:'end',type:'end',config:{outcome:'done'}}]};
  const d=String((await workflows.mutate(admin,tenant,'create',{key:'w_'+randomUUID().replaceAll('-',''),name:'Synthetic Sales',service_actor_id:service},randomUUID(),'synthetic')).body.data.id);await workflows.mutate(admin,tenant,'version',{graph,execution_role_id:role},randomUUID(),'synthetic',d);await workflows.mutate(admin,tenant,'publish',{},randomUUID(),'synthetic',d,1,'1');await workflows.mutate(admin,tenant,'enable',{enabled:true},randomUUID(),'synthetic',d,undefined,'2');
  await workflows.engine.uow.run({tenantId:tenant},s=>workflows.engine.start(s,{event_id:randomUUID(),tenant_id:tenant,event_type:'conversation.created',schema_version:1,aggregate_id:randomUUID(),data:{contact_id:randomUUID(),connection_id:connection},correlation_id:'synthetic'} as Envelope));return (await ds.query('SELECT id FROM workflow_run WHERE definition_id=?',[d]))[0].id as string;
 }
 async function claim(run:string){const c=(await workflows.engine.claim()).find(x=>x.runId===run);expect(c).toBeDefined();return c!;}
 it('v16 upgrade additive, historical checksum/data preserved and repeat no-op',async()=>{
  ds=await isolated('sales_handoff_test');await migrate(ds,migrations.slice(0,16));for(const t of [tenant,beta])await ds.query("INSERT INTO tenant(id,name,status,created_at,updated_at) VALUES (?,'Synthetic','active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[t]);
  for(const p of [{account:admin,principal,role},...sellers]){const m=randomUUID();await ds.query("INSERT INTO account(id,issuer,subject,display_name,created_at,updated_at) VALUES (?,'https://sales.invalid',?,'Synthetic',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[p.account,p.account]);await ds.query("INSERT INTO membership(id,tenant_id,account_id,status,seat_code,created_at,updated_at) VALUES (?,?,?,'active',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[m,tenant,p.account,p.account===admin?'admin':'sales']);await ds.query("INSERT INTO principal(id,tenant_id,kind,membership_id,status,created_at,updated_at) VALUES (?,?,'human',?,'active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[p.principal,tenant,m]);await ds.query("INSERT INTO `role`(id,tenant_id,`key`,name,permissions,created_at,updated_at) VALUES (?,?,?,'Synthetic',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[p.role,tenant,'r_'+p.role.replaceAll('-',''),JSON.stringify(p.account===admin?grants:sellerGrants)]);await ds.query('INSERT INTO principal_role VALUES (?,?,?)',[tenant,p.principal,p.role]);}
  for(const [t,purpose] of [[team,'sales'],[chatTeam,'chat']])await ds.query("INSERT INTO team(id,tenant_id,name,purpose,created_at,updated_at) VALUES (?,?,'Synthetic',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[t,tenant,purpose]);for(const p of sellers)await ds.query('INSERT INTO team_member(tenant_id,team_id,principal_id) VALUES (?,?,?)',[tenant,team,p.principal]);
  for(const key of ['contact','lead'])await ds.query("INSERT INTO object_type(id,tenant_id,`key`,label,kind,created_at,updated_at) VALUES (?,?,?,?,'standard',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[randomUUID(),tenant,key,key]);const domains=coreDomains();domains.set('lead',leadDomain(contactReferences));records=new CrmRecords(ds,'synthetic',domains);leads=new LeadService(records,contactReferences);await qualified();
  const before=await ds.query('SELECT * FROM crm_record'),journal=await ds.query('SELECT * FROM schema_migration ORDER BY version');expect(await migrate(ds)).toBe(migrations.length-16);expect(await migrate(ds)).toBe(0);expect(await ds.query('SELECT * FROM crm_record')).toEqual(before);expect((await ds.query('SELECT * FROM schema_migration ORDER BY version')).slice(0,16)).toEqual(journal);
  await ds.query("INSERT INTO service_actor(id,tenant_id,`key`,role_id,created_at,updated_at) VALUES (?,?,'sales',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[service,tenant,role]);await ds.query("INSERT INTO channel_connection(id,tenant_id,provider,external_account_id,team_id) VALUES (?,?,'mock_messenger','sales',?)",[connection,tenant,chatTeam]);sales=new SalesHandoffs(ds);workflows=new Workflows(ds,workflowChildren(ds));
 });
 it('routes using accept without qualify, shares Contact read only and retains Contact owner',async()=>{
  const f=await qualified();await expect(records.read(sellers[0]!.account,tenant,{object:'contact',kind:'records',id:f.contact})).rejects.toThrow('NOT_FOUND');const h=(await request(f.id)).body.data;expect(sellers.some(p=>p.principal===h.owner_principal_id)).toBe(true);expect(h).toMatchObject({status:'pending',team_id:team,version:'3',attention:false});
  const [row]=await ds.query('SELECT TIMESTAMPDIFF(SECOND,created_at,due_at) seconds FROM lead_handoff WHERE id=?',[h.handoff_id]);expect(Number(row.seconds)).toBe(900);
  expect((await records.read(sellers[0]!.account,tenant,{object:'contact',kind:'records',id:f.contact})).data.owner_principal_id).toBe(principal);await expect(records.mutate(sellers[0]!.account,tenant,{object:'contact',kind:'records',id:f.contact},{fields:{display_name:'Forbidden'}},randomUUID(),'1','synthetic')).rejects.toThrow('FORBIDDEN');
  await expect(accept(f.id,h,sellers.find(p=>p.principal!==h.owner_principal_id)!)).rejects.toThrow('FORBIDDEN');const winner=sellers.find(p=>p.principal===h.owner_principal_id)!;expect((await accept(f.id,h,winner)).body.data.status).toBe('accepted');
 });
 it('receipt replay, body conflict, second handoff and invalid team/CAS roll back',async()=>{
  const f=await qualified(),key=randomUUID(),h=await request(f.id,key);expect(await request(f.id,key)).toEqual(h);await expect(request(f.id,key,chatTeam)).rejects.toThrow('IDEMPOTENCY_CONFLICT');await expect(request(f.id)).rejects.toThrow('INVALID_TRANSITION');const g=await qualified();await expect(request(g.id,randomUUID(),chatTeam)).rejects.toThrow('SALES_TEAM_REQUIRED');await expect(request(g.id,randomUUID(),team,'1')).rejects.toThrow('VERSION_CONFLICT');expect(await ds.query('SELECT id FROM lead_handoff WHERE lead_id=?',[g.id])).toHaveLength(0);expect(await ds.query('SELECT * FROM record_team_access WHERE record_id=?',[g.contact])).toHaveLength(0);
 });
 it('no eligible owner stays queue; simultaneous accepts have exactly one winner/event',async()=>{
  await available(false);const f=await qualified(),h=(await request(f.id)).body.data;expect(h).toMatchObject({owner_principal_id:null,attention:true});const results=await Promise.allSettled(sellers.map(p=>accept(f.id,h,p)));expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((results.find(x=>x.status==='rejected') as PromiseRejectedResult).reason.status).toBe(409);expect(await ds.query("SELECT id FROM outbox_event WHERE aggregate_id=? AND event_type='lead.accepted'",[f.id])).toHaveLength(1);expect((await ds.query('SELECT status,attention FROM lead_handoff WHERE id=?',[h.handoff_id]))[0]).toEqual({status:'accepted',attention:0});await available(true);
 });
 it('accept CAS and owner revision reject before effects; same-key replay stable',async()=>{
  await available(false);const f=await qualified(),h=(await request(f.id)).body.data;await expect(accept(f.id,{...h,version:'2'})).rejects.toThrow('VERSION_CONFLICT');await expect(accept(f.id,{...h,owner_revision:'1'})).rejects.toThrow('OWNER_CONFLICT');const key=randomUUID(),accepted=await accept(f.id,h,sellers[0],key);expect(await accept(f.id,h,sellers[0],key)).toEqual(accepted);await expect(accept(f.id,h)).rejects.toThrow('INVALID_TRANSITION');await available(true);
 });
 it('live role, seat and target-team revocation forbid accept and receipt replay',async()=>{
  await available(false);const f=await qualified(),h=(await request(f.id)).body.data,p=sellers[0]!;
  await ds.query("UPDATE membership SET seat_code='viewer' WHERE account_id=?",[p.account]);await expect(accept(f.id,h,p)).rejects.toThrow('FORBIDDEN');await ds.query("UPDATE membership SET seat_code='sales' WHERE account_id=?",[p.account]);
  await ds.query('UPDATE team_member SET active=0 WHERE principal_id=?',[p.principal]);await expect(accept(f.id,h,p)).rejects.toThrow('NOT_FOUND');await ds.query('UPDATE team_member SET active=1 WHERE principal_id=?',[p.principal]);const key=randomUUID();await accept(f.id,h,p,key);await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(sellerGrants.filter(g=>g.action!=='accept')),p.role]);await expect(accept(f.id,h,p,key)).rejects.toThrow('FORBIDDEN');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(sellerGrants),p.role]);await available(true);
 });
 it('field denial retained for shared Contact and handoff response',async()=>{
  const f=await qualified(),h=(await request(f.id)).body.data,p=sellers[0]!,policy=randomUUID(),[type]=await ds.query("SELECT id FROM object_type WHERE tenant_id=? AND `key`='contact'",[tenant]);await ds.query("INSERT INTO field_policy(id,tenant_id,role_id,object_type_id,property_key,denied_actions,created_at,updated_at) VALUES (?,?,?,?,'display_name',JSON_ARRAY('read'),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[policy,tenant,p.role,type.id]);expect((await records.read(p.account,tenant,{object:'contact',kind:'records',id:f.contact})).data.fields).not.toHaveProperty('display_name');await ds.query('DELETE FROM field_policy WHERE id=?',[policy]);expect((await sales.read(p.account,tenant,f.id)).data[0]!.handoff_id).toBe(h.handoff_id);
 });
 it('15 minute attention persists once, does not auto reassign or accept',async()=>{
  const f=await qualified(),h=(await request(f.id)).body.data;await sales.tick();expect((await sales.read(admin,tenant,f.id)).data[0]!.attention).toBe(false);await ds.query('UPDATE lead_handoff SET due_at=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE id=?',[h.handoff_id]);await Promise.all([sales.tick(),sales.tick()]);expect((await sales.read(admin,tenant,f.id)).data[0]).toMatchObject({attention:true,status:'pending',owner_principal_id:h.owner_principal_id});expect(await ds.query("SELECT id FROM audit_entry WHERE resource_id=? AND action='lead.handoff_overdue'",[h.handoff_id])).toHaveLength(1);
 });
 it('tenant FK, pending uniqueness and accepted NULL bypass blocked by MySQL',async()=>{
  const f=await qualified(),h=(await request(f.id)).body.data;await expect(ds.query('UPDATE lead_handoff SET tenant_id=? WHERE id=?',[beta,h.handoff_id])).rejects.toThrow();await expect(ds.query("UPDATE lead_handoff SET status='accepted' WHERE id=?",[h.handoff_id])).rejects.toThrow();await expect(ds.query("INSERT INTO lead_handoff(id,tenant_id,lead_id,target_team_id,requested_by_kind,requested_by_id,status,due_at) VALUES (?,?,?,?,'human',?,'pending',UTC_TIMESTAMP(6))",[randomUUID(),tenant,f.id,team,principal])).rejects.toThrow();await expect(sales.uow.run({tenantId:beta},s=>sales.result(s,randomUUID(),String(h.handoff_id)))).rejects.toThrow('NOT_FOUND');
 });
 it('request rollback includes share, owner, cursor, handoff and events',async()=>{
  const f=await qualified(),auth=new IdentityAuthorization(sales.uow);await expect(sales.uow.run({tenantId:tenant},async s=>{await sales.request(s,await auth.loadHuman(s,admin,undefined,true),f.id,team,'2','synthetic','human');throw new Error('Synthetic rollback');})).rejects.toThrow('Synthetic rollback');expect(await ds.query('SELECT id FROM lead_handoff WHERE lead_id=?',[f.id])).toHaveLength(0);expect(await ds.query('SELECT * FROM record_team_access WHERE record_id=?',[f.contact])).toHaveLength(0);expect((await leads.read(admin,tenant,f.id)).data.version).toBe('2');expect(await ds.query("SELECT id FROM outbox_event WHERE event_type='lead.handoff_requested' AND aggregate_id=?",[f.id])).toHaveLength(0);
 });
 it('actual Workflow crash/replay/fencing creates one handoff; early accept resumes predicate',async()=>{
  await available(false);const f=await qualified(),run=await workflow(f.id),old=await claim(run);await workflows.engine.effect(old);await ds.query('UPDATE workflow_step_run SET lease_until=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[run]);const current=await claim(run);await expect(workflows.engine.effect(old)).rejects.toThrow('WORKFLOW_LEASE_LOST');await workflows.engine.effect(current);await workflows.engine.finish(current);expect(await ds.query('SELECT id FROM lead_handoff WHERE parent_run_id=?',[run])).toHaveLength(1);const h=(await sales.read(admin,tenant,f.id)).data[0]!;await expect(sales.uow.run({tenantId:tenant},s=>sales.result(s,randomUUID(),String(h.handoff_id)))).rejects.toThrow('HANDOFF_PARENT_INVALID');await accept(f.id,h);await workflows.engine.finish(await claim(run));expect((await ds.query('SELECT current_node FROM workflow_run WHERE id=?',[run]))[0].current_node).toBe('end');await workflows.engine.finish(await claim(run));expect((await ds.query('SELECT status FROM workflow_run WHERE id=?',[run]))[0].status).toBe('completed');await available(true);
 });
 it('Workflow final fence failure rolls back Sales transaction and parent cancel preserves committed handoff',async()=>{
  const f=await qualified(),run=await workflow(f.id),c=await claim(run),children=workflowChildren(ds),slow=new WorkflowEngine(ds,{...children,async execute(s,n,i,ctx){const result=await children.execute(s,n,i,ctx);await s.query('UPDATE workflow_step_run SET lease_until=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[ctx.runId]);return result;}});await expect(slow.effect(c)).rejects.toThrow('WORKFLOW_LEASE_LOST');expect(await ds.query('SELECT id FROM lead_handoff WHERE lead_id=?',[f.id])).toHaveLength(0);await workflows.engine.effect(c);await workflows.engine.uow.run({tenantId:tenant},s=>workflows.engine.cancel(s,run));await workflows.engine.uow.run({tenantId:tenant},s=>children.cancel(s,run));expect((await sales.read(admin,tenant,f.id)).data[0]!.status).toBe('pending');
 });
 it('handoff race creates one pending row; manager assign can accept another owner',async()=>{
  const f=await qualified(),race=await Promise.allSettled([request(f.id),request(f.id)]);expect(race.filter(x=>x.status==='fulfilled')).toHaveLength(1);const h=(await sales.read(admin,tenant,f.id)).data[0]!,other=sellers.find(p=>p.principal!==h.owner_principal_id)!;
  await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify([...sellerGrants,{resource:'lead',action:'assign',scope:'team'}]),other.role]);expect((await accept(f.id,h,other)).body.data.owner_principal_id).toBe(other.principal);await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(sellerGrants),other.role]);
 });
 it('Workflow timeout retains pending handoff and service revocation blocks a new action',async()=>{
  const f=await qualified(),run=await workflow(f.id),c=await claim(run);await workflows.engine.effect(c);await workflows.engine.finish(c);await workflows.engine.finish(await claim(run));await ds.query('UPDATE workflow_wait SET resume_at=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[run]);await workflows.engine.uow.run({tenantId:tenant},s=>workflows.engine.wake(s,run));expect((await ds.query('SELECT status FROM workflow_wait WHERE run_id=?',[run]))[0].status).toBe('timed_out');expect((await sales.read(admin,tenant,f.id)).data[0]!.status).toBe('pending');await workflows.engine.finish(await claim(run));
  const g=await qualified(),other=await workflow(g.id),claim2=await claim(other);await ds.query('UPDATE service_actor SET active=0 WHERE id=?',[service]);await expect(workflows.engine.effect(claim2)).rejects.toThrow('FORBIDDEN');expect(await ds.query('SELECT id FROM lead_handoff WHERE lead_id=?',[g.id])).toHaveLength(0);await ds.query('UPDATE service_actor SET active=1 WHERE id=?',[service]);await workflows.engine.uow.run({tenantId:tenant},s=>workflows.engine.cancel(s,other));
 });
 it('HTTP guards, exact DTO, ETag and generated route shape',async()=>{
  let authorize=true,actor=admin;class TestModule{}Module({controllers:[CrmController],providers:[{provide:CrmRuntime,useValue:{ready:async()=>{},records,leads,handoffs:sales}},{provide:AuthRuntime,useValue:{service:{session:async()=>({account_id:actor}),requireMutation:async()=>{if(!authorize)throw new AuthError(403,'CSRF_INVALID');return {account_id:actor};}}}}]})(TestModule);
  const server=await NestFactory.create(TestModule,{logger:false});server.setGlobalPrefix('api/v1');await server.listen(0,'127.0.0.1');try{const f=await qualified(),base=await server.getUrl(),headers={'Content-Type':'application/json','X-Tenant-Id':tenant,'Idempotency-Key':randomUUID()},url=`${base}/api/v1/leads/${f.id}/handoffs`;
   expect((await fetch(url,{method:'POST',headers,body:JSON.stringify({target_team_id:team})})).status).toBe(428);authorize=false;expect((await fetch(url,{method:'POST',headers:{...headers,'If-Match':'"2"'},body:JSON.stringify({target_team_id:team})})).status).toBe(403);authorize=true;const res=await fetch(url,{method:'POST',headers:{...headers,'If-Match':'"2"'},body:JSON.stringify({target_team_id:team})});expect(res.status).toBe(200);expect(res.headers.get('etag')).toBe('"3"');const wire=await res.json() as any;actor=sellers.find(p=>p.principal===wire.data.owner_principal_id)!.account;const accepted=await fetch(`${url}/${wire.data.handoff_id}/accept`,{method:'POST',headers:{...headers,'Idempotency-Key':randomUUID(),'If-Match':'"3"'},body:JSON.stringify({owner_revision:wire.data.owner_revision})});expect(accepted.status).toBe(200);expect(accepted.headers.get('etag')).toBe('"4"');expect((await fetch(url,{headers})).status).toBe(200);
  }finally{await server.close();}
 });
});}
