import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import type { DataSource } from 'typeorm';
import { migrate } from '../src/kernel/database/migration-runner.js';
import { migrations } from '../src/kernel/database/migrations.js';
import { Workflows } from '../src/modules/workflow/application.js';
import { WorkflowEngine } from '../src/modules/workflow/engine.js';
import type { WorkflowChildren } from '../src/modules/workflow/ports.js';
import { Conversations } from '../src/modules/conversation/domain.js';
import { CrmRecords } from '../src/modules/crm/records.js';
import { coreDomains } from '../src/modules/crm/core.js';
import { DurableDelivery } from '../src/kernel/reliability/delivery.js';
import type { Envelope } from '../src/kernel/reliability/delivery.js';
export function workflowCases(isolated:(name:string)=>Promise<DataSource>){describe('SRC-019 durable Workflow',()=>{
 let ds:DataSource,app:Workflows,engine:WorkflowEngine,conversations:Conversations,contact:string;
 const tenant=randomUUID(),beta=randomUUID(),account=randomUUID(),human=randomUUID(),role=randomUUID(),team=randomUUID(),service=randomUUID(),connection=randomUUID();
 const grants=[...['design','publish','operate','read'].map(action=>({resource:'automation',action,scope:'all'})),...['read','reply','update','assign'].map(action=>({resource:'conversation',action,scope:'all'})),...['create','read'].map(action=>({resource:'contact',action,scope:'all'}))];
 const children:WorkflowChildren={async validate(){},async execute(s,n,_input,c){const id=randomUUID();await s.query("INSERT INTO synthetic_workflow_child(tenant_id,id,run_id,kind,status) VALUES (?,?,?,?,'running')",[s.context.tenantId,id,c.runId,n.type]);return n.type==='start_chatflow'?{session_id:id}:{handoff_id:id,lead_id:randomUUID()};},async result(s,run,type,id){const [c]=await s.query('SELECT * FROM synthetic_workflow_child WHERE tenant_id=? AND id=? AND run_id=? AND kind=? FOR UPDATE',[s.context.tenantId,id,run,type==='chatflow.completed'?'start_chatflow':'request_lead_handoff']);if(!c)throw new Error('Wrong child binding');return c.status==='completed'?{outcome:'qualified',lead_id:null}:null;},async cancel(s,run){await s.query("UPDATE synthetic_workflow_child SET status='cancelled' WHERE tenant_id=? AND run_id=? AND status='running'",[s.context.tenantId,run]);}};
 const end={key:'end',type:'end',config:{outcome:'done'}};
 const graph=(nodes:any[]=[end])=>({trigger:{event_type:'conversation.created',connection_id:connection},entry_node:nodes[0].key,nodes});
 const childGraph=()=>graph([{key:'start',type:'start_chatflow',config:{conversation_id:{ref:'trigger.aggregate_id'},chatflow_version_id:randomUUID()},next:'wait'},{key:'wait',type:'wait_event',config:{event_type:'chatflow.completed',match_key:{ref:'outputs.start.session_id'},timeout_seconds:60},next:'end',on_timeout:'timeout'},end,{key:'timeout',type:'end',config:{outcome:'timeout'}}]);
 const mutate=(op:any,body:any,id?:string,num?:number,version?:string,key=randomUUID())=>app.mutate(account,tenant,op,body,key,'synthetic-workflow',id,num,version);
 async function definition(g=graph(),publish=true){const d=String((await mutate('create',{key:`w_${randomUUID().replaceAll('-','')}`,name:'Synthetic',service_actor_id:service})).body.data.id);await mutate('version',{graph:g,execution_role_id:role},d);if(publish){await mutate('publish',{},d,1,'1');await mutate('enable',{enabled:true},d,undefined,'2');}return d;}
 async function event(){const identity=randomUUID();await ds.query('INSERT INTO contact_identity(id,tenant_id,connection_id,contact_id,external_subject_id) VALUES (?,?,?,?,?)',[identity,tenant,connection,contact,identity]);const received=await conversations.uow.run({tenantId:tenant},s=>conversations.receive(s,{identityId:identity,providerMessageId:randomUUID(),text:'Synthetic workflow',occurredAt:'2026-10-05T01:00:00Z',correlation:'synthetic-workflow'}));return {event_id:randomUUID(),tenant_id:tenant,event_type:'conversation.created',schema_version:1,aggregate_id:received.conversationId,aggregate_type:'conversation',aggregate_version:'1',data:{contact_id:contact,connection_id:connection},correlation_id:'synthetic-workflow',actor:{kind:'system',id:tenant},occurred_at:'2026-10-05T01:00:00Z'} as Envelope;}
 async function start(g=graph()){await ds.query('UPDATE workflow_definition SET enabled=0');const d=await definition(g),e=await event();await engine.uow.run({tenantId:tenant},s=>engine.start(s,e));const [r]=await ds.query('SELECT * FROM workflow_run WHERE definition_id=? AND trigger_event_id=?',[d,e.event_id]);return {d,e,id:r.id as string};}
 async function claim(id:string){const c=(await engine.claim()).find(c=>c.runId===id);expect(c).toBeDefined();return c!;}
 async function step(id:string){const c=await claim(id);await engine.effect(c);await engine.finish(c);return c;}
 async function row(id:string){return (await ds.query('SELECT * FROM workflow_run WHERE id=?',[id]))[0];}
 async function completeChild(id:string){await ds.query("UPDATE synthetic_workflow_child SET status='completed' WHERE run_id=?",[id]);}
 it('v12 to v13 preserves identity/CRM data, journals; rerun no-op',async()=>{
  ds=await isolated('workflow_test');await migrate(ds,migrations.slice(0,12));for(const t of [tenant,beta])await ds.query("INSERT INTO tenant(id,name,status,created_at,updated_at) VALUES (?,'Synthetic','active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[t]);
  const member=randomUUID();await ds.query("INSERT INTO account(id,issuer,subject,display_name,created_at,updated_at) VALUES (?,'https://workflow.invalid',?,'Synthetic',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[account,account]);await ds.query("INSERT INTO membership(id,tenant_id,account_id,status,seat_code,created_at,updated_at) VALUES (?,?,?,'active','admin',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[member,tenant,account]);await ds.query("INSERT INTO principal(id,tenant_id,kind,membership_id,status,created_at,updated_at) VALUES (?,?,'human',?,'active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[human,tenant,member]);await ds.query("INSERT INTO `role`(id,tenant_id,`key`,name,permissions,created_at,updated_at) VALUES (?,?,'workflow','Synthetic',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[role,tenant,JSON.stringify(grants)]);await ds.query('INSERT INTO principal_role VALUES (?,?,?)',[tenant,human,role]);await ds.query("INSERT INTO team(id,tenant_id,name,purpose,created_at,updated_at) VALUES (?,?,'Synthetic','chat',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[team,tenant]);await ds.query('INSERT INTO team_member(tenant_id,team_id,principal_id) VALUES (?,?,?)',[tenant,team,human]);await ds.query("INSERT INTO service_actor(id,tenant_id,`key`,role_id,created_at,updated_at) VALUES (?,?,'workflow',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[service,tenant,role]);for(const key of ['contact','conversation'])await ds.query("INSERT INTO object_type(id,tenant_id,`key`,label,kind,created_at,updated_at) VALUES (?,?,?,?,'standard',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[randomUUID(),tenant,key,key]);
  contact=String((await new CrmRecords(ds,'synthetic',coreDomains()).mutate(account,tenant,{object:'contact',kind:'records'},{fields:{display_name:'Synthetic workflow contact'}},randomUUID(),undefined,'synthetic')).body.data.id);
  const before=await ds.query('SELECT * FROM crm_record'),journal=await ds.query('SELECT * FROM schema_migration ORDER BY version');expect(await migrate(ds)).toBe(migrations.length-12);expect(await migrate(ds)).toBe(0);expect(await ds.query('SELECT * FROM crm_record')).toEqual(before);expect((await ds.query('SELECT * FROM schema_migration ORDER BY version')).slice(0,12)).toEqual(journal);
  await ds.query("INSERT INTO channel_connection(id,tenant_id,provider,external_account_id,team_id) VALUES (?,?,'mock_messenger','workflow',?)",[connection,tenant,team]);await ds.query('CREATE TABLE synthetic_workflow_child(tenant_id CHAR(36),id CHAR(36),run_id CHAR(36),kind VARCHAR(32),status VARCHAR(16),PRIMARY KEY(tenant_id,id)) ENGINE=InnoDB');app=new Workflows(ds,children);engine=app.engine;conversations=new Conversations(ds,'synthetic');
 });
 it('publish guards version/CAS, permission, missing references and production child unavailability',async()=>{
  const d=await definition(childGraph(),false);await expect(new Workflows(ds).mutate(account,tenant,'publish',{},randomUUID(),'synthetic',d,1,'1')).rejects.toThrow('WORKFLOW_CHILD_UNAVAILABLE');await expect(mutate('publish',{},d,1)).rejects.toThrow('VERSION_REQUIRED');await expect(mutate('publish',{},d,1,'9')).rejects.toThrow('VERSION_CONFLICT');await mutate('publish',{},d,1,'1');await expect(mutate('publish',{},d,1,'2')).rejects.toThrow('VERSION_IMMUTABLE');await expect(app.read(account,beta,'definitions')).rejects.toThrow('FORBIDDEN');
  const bad=await definition({...graph(),trigger:{event_type:'conversation.created',connection_id:randomUUID()}},false);await expect(mutate('publish',{},bad,1,'1')).rejects.toThrow('CONNECTION_UNAVAILABLE');
 });
 it('atomic command replay, changed body conflict and current rights on replay',async()=>{
  const key=randomUUID(),body={key:'receipt',name:'Synthetic receipt',service_actor_id:service},r=await mutate('create',body,undefined,undefined,undefined,key);expect(await mutate('create',body,undefined,undefined,undefined,key)).toEqual(r);await expect(mutate('create',{...body,name:'Changed'},undefined,undefined,undefined,key)).rejects.toThrow('IDEMPOTENCY_CONFLICT');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants.filter(g=>g.action!=='design')),role]);await expect(mutate('create',body,undefined,undefined,undefined,key)).rejects.toThrow('FORBIDDEN');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);
 });
 it('pin version and starter selection across duplicate, disable, new publish and concurrent delivery',async()=>{
  const f=await start();await mutate('version',{graph:graph(),execution_role_id:role},f.d);await mutate('publish',{},f.d,2,'3');await Promise.all([1,2].map(()=>engine.uow.run({tenantId:tenant},s=>engine.start(s,f.e))));expect(await ds.query('SELECT id FROM workflow_run WHERE definition_id=?',[f.d])).toHaveLength(1);const [v]=await ds.query('SELECT number FROM workflow_version WHERE id=?',[(await row(f.id)).version_id]);expect(v.number).toBe(1);await step(f.id);expect((await row(f.id)).status).toBe('completed');
  const d=await definition(graph(),false),e=await event();await engine.uow.run({tenantId:tenant},s=>engine.start(s,e));await mutate('publish',{},d,1,'1');await mutate('enable',{enabled:true},d,undefined,'2');await engine.uow.run({tenantId:tenant},s=>engine.start(s,e));expect(await ds.query('SELECT id FROM workflow_run WHERE definition_id=?',[d])).toHaveLength(0);
 });
 it('crash after effect replays one child using same action key; fencing rejects old worker',async()=>{
  const f=await start(childGraph()),old=await claim(f.id);await engine.effect(old);await ds.query('UPDATE workflow_step_run SET lease_until=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[f.id]);const current=await claim(f.id);expect(current.token).not.toBe(old.token);await expect(engine.finish(old)).rejects.toThrow('WORKFLOW_LEASE_LOST');await expect(engine.effect(old)).rejects.toThrow('WORKFLOW_LEASE_LOST');await engine.effect(current);await engine.finish(current);expect(await ds.query('SELECT id FROM synthetic_workflow_child WHERE run_id=?',[f.id])).toHaveLength(1);const [s]=await ds.query('SELECT action_key,attempt FROM workflow_step_run WHERE run_id=? AND node_key=?',[f.id,'start']);expect(s.action_key).toBe(`${f.id}:start`);expect(s.attempt).toBe(2);
 });
 it('expired effect rolls back child and ledger even if work passed initial fence',async()=>{
  const f=await start(childGraph()),c=await claim(f.id),slow=new WorkflowEngine(ds,{...children,async execute(s,n,i,ctx){const out=await children.execute(s,n,i,ctx);await s.query('UPDATE workflow_step_run SET lease_until=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[ctx.runId]);return out;}});await expect(slow.effect(c)).rejects.toThrow('WORKFLOW_LEASE_LOST');expect(await ds.query('SELECT id FROM synthetic_workflow_child WHERE run_id=?',[f.id])).toHaveLength(0);expect(await ds.query('SELECT * FROM workflow_action WHERE run_id=?',[f.id])).toHaveLength(0);await engine.uow.run({tenantId:tenant},s=>engine.cancel(s,f.id));
 });
 it('early child result survives wait registration and missing signal',async()=>{
  const f=await start(childGraph());await step(f.id);await completeChild(f.id);await step(f.id);expect((await row(f.id)).current_node).toBe('end');await step(f.id);expect((await row(f.id)).status).toBe('completed');expect(await ds.query('SELECT status FROM workflow_wait WHERE run_id=?',[f.id])).toEqual([{status:'resumed'}]);
 });
 it('concurrent timeout/event checks use predicate first, exactly one transition/outbox',async()=>{
  const f=await start(childGraph());await step(f.id);await step(f.id);await ds.query('UPDATE workflow_wait SET resume_at=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[f.id]);await completeChild(f.id);await Promise.all([1,2].map(()=>engine.uow.run({tenantId:tenant},s=>engine.wake(s,f.id))));expect((await row(f.id)).current_node).toBe('end');await step(f.id);expect(await ds.query("SELECT id FROM outbox_event WHERE aggregate_id=? AND event_type='workflow.completed'",[f.id])).toHaveLength(1);
 });
 it('timeout follows on_timeout; timer waits persist and recover with no Redis',async()=>{
  const f=await start(childGraph());await step(f.id);await step(f.id);await ds.query('UPDATE workflow_wait SET resume_at=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[f.id]);await engine.uow.run({tenantId:tenant},s=>engine.wake(s,f.id));expect((await row(f.id)).current_node).toBe('timeout');await step(f.id);
  const t=await start(graph([{key:'timer',type:'wait_timer',config:{duration_seconds:1},next:'end'},end]));await step(t.id);expect((await row(t.id)).status).toBe('waiting');await ds.query('UPDATE workflow_wait SET resume_at=TIMESTAMPADD(SECOND,-1,UTC_TIMESTAMP(6)) WHERE run_id=?',[t.id]);await new WorkflowEngine(ds,children).tick();expect((await row(t.id)).current_node).toBe('end');await step(t.id);
 });
 it('live role/service revocation fails without child side effect',async()=>{
  const f=await start(childGraph()),c=await claim(f.id);await ds.query('UPDATE service_actor SET active=0 WHERE id=?',[service]);await expect(engine.effect(c)).rejects.toThrow('FORBIDDEN');await engine.fail(c,new (await import('../src/kernel/reliability/commands.js')).CommandError(403,'FORBIDDEN'));expect((await row(f.id)).status).toBe('failed');expect(await ds.query('SELECT id FROM synthetic_workflow_child WHERE run_id=?',[f.id])).toHaveLength(0);await ds.query('UPDATE service_actor SET active=1 WHERE id=?',[service]);
 });
 it('five transient retries retain action key, then failure is sanitized',async()=>{
  const f=await start();for(let i=0;i<6;i++){const c=await claim(f.id);await engine.fail(c,new Error('sensitive synthetic diagnostic'));if(i<5){expect((await row(f.id)).status).toBe('running');await ds.query('UPDATE workflow_step_run SET next_attempt_at=UTC_TIMESTAMP(6) WHERE run_id=?',[f.id]);}}expect((await row(f.id)).status).toBe('failed');expect((await row(f.id)).error_code).toBe('WORKFLOW_TRANSIENT_FAILURE');
 });
 it('cancel fences worker, requests child cancel, keeps committed effect, terminal is idempotent',async()=>{
  const f=await start(childGraph());await step(f.id);const c=await claim(f.id);await mutate('cancel',{reason:'operator_cancelled'},f.id);await expect(engine.finish(c)).rejects.toThrow('WORKFLOW_LEASE_LOST');await engine.tick();expect((await row(f.id)).cancel_pending).toBe(0);expect(await ds.query('SELECT status FROM synthetic_workflow_child WHERE run_id=?',[f.id])).toEqual([{status:'cancelled'}]);expect(await ds.query('SELECT * FROM workflow_action WHERE run_id=?',[f.id])).toHaveLength(1);await mutate('cancel',{reason:'operator_cancelled'},f.id);expect((await row(f.id)).status).toBe('cancelled');
 });
 it('run projection excludes context/input and checks tenant/current Conversation rights',async()=>{
  const f=await start();const result=await app.read(account,tenant,'run',f.id);expect(result.data).not.toHaveProperty('context');await expect(app.read(account,beta,'run',f.id)).rejects.toThrow('FORBIDDEN');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants.filter(g=>g.resource!=='conversation')),role]);await expect(app.read(account,tenant,'run',f.id)).rejects.toThrow('NOT_FOUND');await ds.query('UPDATE `role` SET permissions=? WHERE id=?',[JSON.stringify(grants),role]);await step(f.id);
 });
 it('real assignment action uses owner port once; condition chooses typed true/false edges',async()=>{
  const f=await start(graph([{key:'assign',type:'assign_owner',config:{record_id:{ref:'trigger.aggregate_id'},team_id:team,capability:'chat',preference:'human'},next:'check'},{key:'check',type:'condition',config:{left:{ref:'outputs.assign.owner_id'},op:'exists',on_true:'end',on_false:'empty'}},end,{key:'empty',type:'end',config:{outcome:'empty'}}]));await step(f.id);const [r]=await ds.query('SELECT owner_principal_id,owner_revision FROM crm_record WHERE id=?',[f.e.aggregate_id]);expect(r.owner_principal_id).toBe(human);expect(String(r.owner_revision)).toBe('2');await step(f.id);expect((await row(f.id)).current_node).toBe('end');await step(f.id);
  const no=await start(graph([{key:'check',type:'condition',config:{left:false,op:'eq',right:true,on_true:'end',on_false:'no'}},end,{key:'no',type:'end',config:{outcome:'no'}}]));await step(no.id);expect((await row(no.id)).current_node).toBe('no');await step(no.id);
 });
 it('durable delivery starter consumes replay once and signal wakes persisted child',async()=>{
  const f=await start(childGraph());const [outbox]=await ds.query("SELECT id FROM outbox_event WHERE aggregate_id=? AND event_type='conversation.created'",[f.e.aggregate_id]);const delivery=new DurableDelivery(ds);await ds.query("UPDATE outbox_event SET status='dispatched' WHERE id<>?",[outbox.id]);const c=(await delivery.claim()).find(c=>c.eventId===outbox.id)!;await delivery.consume(c,engine.consumers()[0]!);await delivery.consume(c,engine.consumers()[0]!);expect(await ds.query('SELECT id FROM workflow_run WHERE definition_id=? AND trigger_event_id=?',[f.d,outbox.id])).toHaveLength(1);
  await step(f.id);await step(f.id);await completeChild(f.id);const [child]=await ds.query('SELECT id FROM synthetic_workflow_child WHERE run_id=?',[f.id]);await engine.uow.run({tenantId:tenant},s=>engine.consumers()[1]!.handle(s,{...f.e,event_type:'chatflow.completed',data:{session_id:child.id}}));expect((await row(f.id)).current_node).toBe('end');await step(f.id);
 });
 it('cancellation retries stop after five failures and retain attention',async()=>{
  const f=await start(childGraph());await step(f.id);await engine.uow.run({tenantId:tenant},s=>engine.cancel(s,f.id));let attempts=0;const failing=new WorkflowEngine(ds,{...children,async cancel(){attempts++;throw new Error('synthetic child unavailable');}});for(let i=0;i<6;i++){await ds.query('UPDATE workflow_run SET cancel_retry_at=NULL WHERE id=?',[f.id]);await failing.tick();}const r=await row(f.id);expect(r.cancel_attempts).toBe(5);expect(r.cancel_pending).toBe(1);expect(r.attention).toBe(1);expect(attempts).toBe(5);
 });
 it('same tenant version FK and pinned service role reject cross-tenant or changed role',async()=>{
  const f=await start(childGraph()),c=await claim(f.id);await expect(ds.query('UPDATE workflow_run SET tenant_id=? WHERE id=?',[beta,f.id])).rejects.toThrow();const next=randomUUID();await ds.query("INSERT INTO `role`(id,tenant_id,`key`,name,permissions,created_at,updated_at) VALUES (?,?,'changed','Synthetic',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[next,tenant,JSON.stringify(grants)]);await ds.query('UPDATE service_actor SET role_id=? WHERE id=?',[next,service]);await expect(engine.effect(c)).rejects.toThrow('WORKFLOW_ROLE_REVOKED');await ds.query('UPDATE service_actor SET role_id=? WHERE id=?',[role,service]);await engine.uow.run({tenantId:tenant},s=>engine.cancel(s,f.id));
 });

});}
