'use client';
import { CrmWorkspace } from './crm/workspace';
import { useEffect,useState } from 'react';
interface Membership {id:string;tenant_id:string;tenant_name:string;seat_code:string}
export function TenantPanel({userName,onLogout,logoutBusy}:{userName:string;onLogout:()=>void;logoutBusy:boolean}){
 const [members,setMembers]=useState<Membership[]>([]),[selected,setSelected]=useState(''),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(false),[loading,setLoading]=useState(true);
 async function load(next?:string){setLoading(true);setError(false);try{const res=await fetch(`/api/v1/me/memberships?limit=100${next?'&cursor='+encodeURIComponent(next):''}`,{cache:'no-store'});if(!res.ok)throw Error();const body=await res.json();setMembers(old=>next?[...old,...body.data]:body.data);setCursor(body.next_cursor);if(!next){const wanted=sessionStorage.getItem('facebook_config_tenant');if(new URLSearchParams(window.location.search).has('facebook')&&body.data.some((m:Membership)=>m.tenant_id===wanted)){setSelected(wanted!);sessionStorage.removeItem('facebook_config_tenant');}else if(body.data.length===1&&!body.next_cursor)setSelected(body.data[0].tenant_id);}}catch{setError(true);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const selector=<label className="ui-tenant-selector"><span className="sr-only">Chọn tổ chức</span><select aria-label="Chọn tổ chức" value={selected} onChange={e=>{if(document.querySelector('[data-unsaved="true"]')&&!window.confirm('Bỏ bản nháp chưa lưu và chuyển tổ chức?'))return;setSelected(e.target.value);}}><option value="">Chọn tổ chức…</option>{members.map(m=><option key={m.id} value={m.tenant_id}>{m.tenant_name} · {m.seat_code}</option>)}</select></label>;
 return selected?<CrmWorkspace key={selected} tenant={selected} tenantSelector={selector} userName={userName} onLogout={onLogout} logoutBusy={logoutBusy} moreTenants={cursor?<button onClick={()=>void load(cursor)} disabled={loading}>Tải thêm tổ chức</button>:null}/>:<div className="ui-entry"><a className="brand" href="/"><span className="mark">a</span>agentic crm</a><section className="auth-panel"><div><h2>Chọn workspace</h2><p>Xin chào {userName}.</p>{selector}{loading&&<p role="status">Đang tải tổ chức…</p>}{error&&<button onClick={()=>void load()}>Tải lại tổ chức</button>}{!loading&&!error&&!members.length&&<p>Tài khoản chưa được cấp quyền vào tổ chức nào.</p>}{cursor&&<button onClick={()=>void load(cursor)}>Tải thêm tổ chức</button>}</div><button onClick={onLogout} disabled={logoutBusy}>Đăng xuất</button></section></div>;
}
