'use client';
import { useEffect,useState } from 'react';
import { Button } from '../../components/ui/button';
import { useApi,useCommand,ErrorNotice,can,type Context } from './api';
import { ChannelBadge } from './channel-badge';
export interface FacebookPageRow {id:string;channel_id:string;page_id:string;name:string;team_id:string;credential_status:'stored'|'missing';connected_at:string}
export function FacebookPageTable({pages,teams=[]}:{pages:FacebookPageRow[];teams?:{id:string;name:string}[]}){return <div className="crm-table-wrap"><table><thead><tr><th>Facebook Page</th><th>Kênh</th><th>Nhóm tiếp nhận</th><th>Cấu hình</th></tr></thead><tbody>{pages.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>Page ID: {p.page_id}</small><small>Channel ID: {p.channel_id}</small></td><td><ChannelBadge channel="messenger"/></td><td>{teams.find(t=>t.id===p.team_id)?.name??p.team_id}</td><td><span className="crm-badge">{p.credential_status==='stored'?'Đã lưu thông tin kết nối':'Chưa có thông tin kết nối'}</span><small>Chưa bật nhận/gửi tin</small></td></tr>)}</tbody></table>{!pages.length&&<p className="crm-empty">Chưa có Facebook Page. Kết nối Facebook để chọn quyền truy cập và lấy danh sách Page.</p>}</div>;}
export function FacebookSettings({tenant,context}:{tenant:string;context:Context}){
 const [team,setTeam]=useState(''),[cursor,setCursor]=useState<string|null>(null),[notice,setNotice]=useState(''),command=useCommand(tenant);
 const list=useApi(tenant,`/api/v1/admin/channels/facebook/pages?limit=50${cursor?'&cursor='+cursor:''}`,can(context,'integration','read'));
 const teams=useApi(tenant,'/api/v1/admin/teams?limit=100',can(context,'team','read'));
 useEffect(()=>{const q=new URLSearchParams(window.location.search),result=q.get('facebook');if(!result)return;setNotice(({connected:'Đã kết nối Facebook và lưu danh sách Page.',empty:'Facebook chưa trả về Page nào. Kiểm tra tài khoản và quyền đã cấp.',cancelled:'Bạn đã hủy kết nối Facebook. Có thể kết nối lại bất cứ lúc nào.',failed:'Không thể hoàn tất kết nối Facebook. Kiểm tra cấu hình ứng dụng hoặc thử kết nối lại.'} as Record<string,string>)[result]??'');q.delete('facebook');window.history.replaceState(null,'',window.location.pathname+(q.size?'?'+q:'')+window.location.hash);},[]);
 const available=(teams.data?.data??[]).filter((t:any)=>t.active&&['chat','general'].includes(t.purpose));
 const connect=async()=>{const result=await command.run('/api/v1/admin/channels/facebook/connect',{team_id:team});if(result){sessionStorage.setItem('facebook_config_tenant',tenant);window.location.assign(result.data.authorization_url);}};
 if(!can(context,'integration','read'))return <p>Bạn chưa có quyền xem cấu hình kênh.</p>;
 return <section aria-label="Facebook channels"><div className="eyebrow">CHANNELS / FACEBOOK</div><h3>Facebook Pages</h3><p>Kết nối tài khoản Facebook để quản lý các Page trong CRM.</p>{notice&&<p role="status" className="chat-note">{notice}</p>}
 {can(context,'integration','configure')&&<div className="facebook-connect"><label>Nhóm tiếp nhận Page mới<select aria-label="Nhóm tiếp nhận Page mới" value={team} onChange={e=>setTeam(e.target.value)}><option value="">Chọn nhóm…</option>{available.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Button disabled={!team||command.busy||!list.data?.oauth_configured} onClick={()=>void connect()}>{command.busy?'Đang kết nối…':'Connect Facebook'}</Button><ErrorNotice error={teams.error}/>{teams.data?.next_cursor&&<p>Danh sách hiển thị 100 nhóm đầu tiên.</p>}<p>Facebook sẽ yêu cầu bạn chọn Page và cấp quyền. Các Page đã có vẫn giữ nguyên nhóm.</p></div>}
 {list.data&&!list.data.oauth_configured&&<p role="status">Facebook chưa được cấu hình cho hệ thống. Liên hệ quản trị viên để bật kết nối.</p>}
 <ErrorNotice error={command.error}/>{list.isPending?<p role="status">Đang tải Page…</p>:list.error?<ErrorNotice error={list.error} reload={()=>void list.refetch()}/>:<><FacebookPageTable pages={list.data.data} teams={teams.data?.data??[]}/><div className="crm-actions">{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>Trang đầu</Button>}{list.data.next_cursor&&<Button variant="outline" onClick={()=>setCursor(list.data.next_cursor)}>Trang tiếp</Button>}<Button variant="outline" onClick={()=>void list.refetch()}>Tải lại Page</Button></div></>}
 </section>;
}
