'use client';
import { Ownership } from './ownership';
import { useEffect,useRef,useState } from 'react';
import { useInfiniteQuery,useQuery } from '@tanstack/react-query';
import { Button } from '../../components/ui/button';
import { request,useCommand,ErrorNotice,type Context } from './api';
import type { ConversationEntity as Conversation } from '../../../../packages/contracts/src/generated/conversation-entity';
import type { ConversationMessage as Message } from '../../../../packages/contracts/src/generated/conversation-message';
const labels:Record<string,string>={open:'Đang mở',pending:'Đang chờ',closed:'Đã đóng',received:'Đã nhận',queued:'Đang xếp hàng',sending:'Đang gửi',sent:'Đã gửi',failed:'Gửi thất bại',unknown:'Chưa rõ kết quả — cần kiểm tra delivery',cancelled:'Đã hủy'};
type PendingSend={text:string;owner_revision:string};
const quickReplies=['Chào bạn, mình có thể hỗ trợ gì cho bạn?','Cảm ơn bạn. Mình sẽ kiểm tra và phản hồi.','Bạn muốn được liên hệ qua Messenger hay điện thoại?'];
const name=(r:Conversation)=>r.contact?.display_name??`Hội thoại ${r.id.slice(0,8)}`;
const owner=(r:Conversation,context:Context)=>!r.owner_principal_id?'Chưa phân công':`${r.owner_kind==='human'?'Human':r.owner_kind==='ai'?'AI':'Owner'} · ${r.owner_principal_id===context.principal_id?'Bạn':r.owner_principal_id}`;
function usePoll(tenant:string,path:string){return useQuery({queryKey:[tenant,path],queryFn:({signal})=>request(tenant,path,{signal}),refetchInterval:5000,retry:false,refetchOnWindowFocus:true});}
function usePages(tenant:string,path:string){return useInfiniteQuery({queryKey:[tenant,path],initialPageParam:null as string|null,queryFn:({signal,pageParam})=>request(tenant,path+(pageParam?`&cursor=${encodeURIComponent(pageParam)}`:''),{signal}),getNextPageParam:page=>page.next_cursor??undefined,refetchInterval:5000,retry:false,refetchOnWindowFocus:true});}
export function Inbox({tenant,context}:{tenant:string;context:Context}){
  const [state,setState]=useState('open'),[scope,setScope]=useState('all'),[team,setTeam]=useState(''),[teamInput,setTeamInput]=useState(''),[search,setSearch]=useState(''),[id,setId]=useState<string|null>(null);
  const [drafts,setDrafts]=useState<Record<string,string>>({}),keys=useRef(new Map<string,string>()),reviews=useRef(new Map<string,string>()),[pending,setPending]=useState<Record<string,PendingSend|undefined>>({});
  const params=new URLSearchParams({limit:'30',...(state?{state}:{}),...(scope==='mine'?{owner:context.principal_id}:scope==='unassigned'?{owner:'unassigned'}:{}),...(team?{team}:{})});
  const queue=usePages(tenant,`/api/v1/conversations?${params}`);
  const rows:Conversation[]=queue.data?.pages.flatMap(p=>p.data)??[];
  const filtered=rows.filter(r=>name(r).toLocaleLowerCase().startsWith(search.toLocaleLowerCase()));
  function reset(){setId(null);}
  return <div className="chat-layout" aria-label="Chat inbox"><section className="crm-card chat-queue"><h3>Hộp thư</h3><p className="chat-caption">Cập nhật mỗi 5 giây</p>
    <label>Trạng thái hội thoại<select aria-label="Trạng thái hội thoại" value={state} onChange={e=>{setState(e.target.value);reset();}}><option value="">Tất cả trạng thái</option>{['open','pending','closed'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>
    <label>Phân công<select aria-label="Phân công" value={scope} onChange={e=>{setScope(e.target.value);reset();}}><option value="all">Trong quyền truy cập</option><option value="mine">Của tôi</option><option value="unassigned">Chưa phân công</option></select></label>
    <form onSubmit={e=>{e.preventDefault();setTeam(teamInput);reset();}}><label>Lọc nhóm (ID)<input value={teamInput} onChange={e=>setTeamInput(e.target.value)} pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/></label><Button variant="outline" type="submit">Áp dụng nhóm</Button></form>
    <label>Tìm đầu tên trong danh sách đã tải<input value={search} onChange={e=>setSearch(e.target.value)}/></label>
    {queue.isPending?<p role="status">Đang tải hộp thư…</p>:queue.error?<ErrorNotice error={queue.error} reload={()=>void queue.refetch()}/>:<><ul className="record-list">{filtered.map(r=><li key={r.id}><button aria-pressed={id===r.id} onClick={()=>setId(r.id)}><strong>{name(r)}</strong><span>{labels[r.status]} · {owner(r,context)}</span>{r.latest_message&&<><span className="chat-preview">{r.latest_message.text??'Nội dung không nằm trong quyền đọc.'}</span><small>{labels[r.latest_message.status]}</small></>}<small>{new Date(r.latest_message?.received_at??r.opened_at).toLocaleString('vi-VN')}</small></button></li>)}</ul>{!filtered.length&&<p>Chưa có hội thoại phù hợp.</p>}{queue.hasNextPage&&<Button variant="outline" disabled={queue.isFetching} onClick={()=>void queue.fetchNextPage()}>Tải thêm hội thoại</Button>}</>}
  </section>{queue.error?<section className="crm-card"><p>Không thể đọc hộp thư. Hãy tải lại trước khi tiếp tục.</p></section>:id?<Detail key={id} tenant={tenant} context={context} id={id} keys={keys.current} reviews={reviews.current} pending={pending[id]} setPending={value=>setPending(old=>({...old,[id]:value}))} drafts={drafts} setDraft={(key,value)=>setDrafts(old=>({...old,[key]:value}))}/>:<section className="crm-card crm-empty"><h3>Chọn một hội thoại</h3><p>Xem lịch sử tin nhắn, ghi chú và thông tin liên hệ.</p></section>}</div>;
}
function Detail({tenant,context,id,keys,reviews,pending,setPending,drafts,setDraft}:{tenant:string;context:Context;id:string;keys:Map<string,string>;reviews:Map<string,string>;pending?:PendingSend;setPending:(value:PendingSend|undefined)=>void;drafts:Record<string,string>;setDraft:(key:string,value:string)=>void}){
  const detail=usePoll(tenant,`/api/v1/conversations/${id}`),contextPanel=useRef<HTMLDetailsElement>(null);
  useEffect(()=>{if(contextPanel.current)contextPanel.current.open=window.matchMedia('(min-width:1450px)').matches;},[detail.isPending]);
  if(detail.error)return <section className="crm-card"><ErrorNotice error={detail.error} reload={()=>void detail.refetch()}/></section>;
  if(detail.isPending)return <section className="crm-card" role="status">Đang tải hội thoại…</section>;
  const r=detail.data.data as Conversation;
  return <div className="chat-detail"><section className="crm-card chat-thread"><div className="crm-detail-heading"><h3>{name(r)}</h3><span className="crm-badge">{labels[r.status]}</span><p>{owner(r,context)}</p><small className="crm-record-id">Nhóm: {r.team_id??'Chưa có'} · {r.id}</small></div>
    {r.status!=='closed'&&r.allowed_actions?.some(a=>a==='assign'||a==='takeover')&&<Ownership tenant={tenant} record={r} reload={()=>void detail.refetch()}/>}
    <Timeline tenant={tenant} id={id}/><Composer tenant={tenant} record={r} keys={keys} reviews={reviews} pending={pending} setPending={setPending} draft={drafts[id+':reply']??''} note={drafts[id+':note']??''} setDraft={(mode,value)=>setDraft(id+':'+mode,value)} reload={()=>void detail.refetch()}/>
  </section><details ref={contextPanel} className="crm-card chat-context"><summary>Thông tin liên hệ & nguồn</summary><h3>Liên hệ</h3>{r.contact?<><p>{r.contact.display_name??'Tên không nằm trong quyền đọc'}</p>{r.contact.normalized_phone&&<p>{r.contact.normalized_phone}</p>}{r.contact.normalized_email&&<p>{r.contact.normalized_email}</p>}</>:<p>Không có quyền đọc thông tin liên hệ.</p>}<h4>Nguồn hội thoại</h4>{r.attribution?<><p>{r.attribution.source==='ctm'?'Click-to-Messenger':'Chưa xác định'}</p>{r.attribution.ad_id&&<p>Quảng cáo: {r.attribution.ad_id}</p>}{r.attribution.campaign_id&&<p>Chiến dịch: {r.attribution.campaign_id}</p>}</>:<p>Nguồn không nằm trong quyền đọc.</p>}</details></div>;
}
function Timeline({tenant,id}:{tenant:string;id:string}){
  const messages=usePages(tenant,`/api/v1/conversations/${id}/messages?limit=50`),notes=usePages(tenant,`/api/v1/conversations/${id}/notes?limit=50`);
  const rows:Message[]=messages.data?.pages.flatMap(p=>p.data)??[];
  const internal:{id:string;body?:string;created_at:string}[]=notes.data?.pages.flatMap(p=>p.data)??[];
  return <><h4>Timeline</h4>{messages.isPending?<p role="status">Đang tải tin nhắn…</p>:messages.error?<ErrorNotice error={messages.error} reload={()=>void messages.refetch()}/>:<><ol className="chat-messages" aria-label="Tin nhắn">{rows.map(m=><li key={m.id} className={`chat-message ${m.direction}`}><div><strong>{m.direction==='inbound'?'Khách':'Phản hồi'}</strong><span className="crm-badge">{labels[m.status]}</span></div><p>{m.text??'Nội dung không nằm trong quyền đọc.'}</p><small>Nhận: {new Date(m.received_at).toLocaleString('vi-VN')} · Phát sinh: {new Date(m.occurred_at).toLocaleString('vi-VN')}</small></li>)}</ol>{!rows.length&&<p>Chưa có tin nhắn.</p>}{messages.hasNextPage&&<Button variant="outline" disabled={messages.isFetching} onClick={()=>void messages.fetchNextPage()}>Tải thêm tin nhắn</Button>}</>}
    <details><summary>Ghi chú nội bộ</summary>{notes.isPending?<p role="status">Đang tải ghi chú…</p>:notes.error?<ErrorNotice error={notes.error} reload={()=>void notes.refetch()}/>:<>{!internal.length&&<p>Chưa có ghi chú trong quyền đọc Activity của bạn.</p>}{internal.sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)).map(n=><article className="chat-note" key={n.id}><p>{n.body??'Nội dung không nằm trong quyền đọc.'}</p><small>{new Date(n.created_at).toLocaleString('vi-VN')}</small></article>)}{notes.hasNextPage&&<Button variant="outline" disabled={notes.isFetching} onClick={()=>void notes.fetchNextPage()}>Tải thêm ghi chú</Button>}</>}</details></>;
}
function Composer({tenant,record:r,keys,reviews,pending,setPending,draft,note,setDraft,reload}:{tenant:string;record:Conversation;keys:Map<string,string>;reviews:Map<string,string>;pending?:PendingSend;setPending:(value:PendingSend|undefined)=>void;draft:string;note:string;setDraft:(mode:string,value:string)=>void;reload:()=>void}){
  const command=useCommand(tenant,keys),[mode,setMode]=useState('reply'),[reviewed,setReviewed]=useState(()=>{const revision=reviews.get(r.id)??r.owner_revision;reviews.set(r.id,revision);return revision;}),[notice,setNotice]=useState('');
  const stale=reviewed!==r.owner_revision,allowed=r.allowed_actions?.includes(mode==='reply'?'reply':'note'),text=mode==='reply'?draft:note;
  if(r.status==='closed')return <p>Hội thoại đã đóng, chỉ có thể đọc.</p>;
  return <form className="crm-form chat-composer" onSubmit={async e=>{e.preventDefault();if(!allowed||stale||command.busy||!text.trim()||pending)return;const payload={text,owner_revision:r.owner_revision};if(mode==='reply')setPending(payload);const result=await command.run(`/api/v1/conversations/${r.id}/${mode==='reply'?'messages':'notes'}`,mode==='reply'?payload:{text});if(result){if(mode==='reply')setPending(undefined);setDraft(mode,'');setNotice(mode==='reply'?'Đã tiếp nhận yêu cầu gửi. Xem trạng thái delivery trong timeline.':'Đã lưu ghi chú nội bộ.');}else{if(mode==='reply'&&command.failure.current?.status&&command.failure.current.status<500)setPending(undefined);reload();}}}>
    <div className="crm-tabs"><Button type="button" variant={mode==='reply'?'default':'outline'} onClick={()=>{setMode('reply');setNotice('');}}>Phản hồi</Button><Button type="button" variant={mode==='note'?'default':'outline'} onClick={()=>{setMode('note');setNotice('');}}>Ghi chú</Button></div>
    {(stale||command.error?.status===409)&&<div role="alert" className="crm-error">Owner hoặc phiên bản đã thay đổi. Kiểm tra phân công trước khi gửi.<Button type="button" variant="outline" onClick={()=>{setReviewed(r.owner_revision);reviews.set(r.id,r.owner_revision);command.setError(null);reload();}}>Đã xem phân công mới</Button></div>}
    {mode==='reply'&&<label>Trả lời nhanh<select aria-label="Trả lời nhanh" value="" disabled={!allowed||stale||command.busy||!!pending} onChange={e=>setDraft('reply',e.target.value)}><option value="">Chèn mẫu để chỉnh sửa…</option>{quickReplies.map(q=><option key={q} value={q}>{q}</option>)}</select></label>}
    <label>{mode==='reply'?'Nội dung phản hồi':'Nội dung ghi chú'}<textarea aria-label={mode==='reply'?'Nội dung phản hồi':'Nội dung ghi chú'} rows={3} maxLength={4000} value={text} disabled={!allowed||stale||command.busy||!!pending} onChange={e=>{setDraft(mode,e.target.value);setNotice('');}}/></label>
    {!allowed&&<p>{mode==='reply'?'Chỉ owner hiện tại có quyền trả lời mới được gửi tin.':'Bạn chưa có quyền ghi chú hội thoại này.'}</p>}
    {pending&&<div role="status" className="chat-note">Chưa xác định kết quả gửi. Bản nháp được giữ đến khi kiểm tra lại yêu cầu cũ.<Button type="button" variant="outline" disabled={command.busy} onClick={async()=>{const result=await command.run(`/api/v1/conversations/${r.id}/messages`,pending);if(result){setPending(undefined);setDraft('reply','');setNotice('Đã tiếp nhận yêu cầu gửi. Xem trạng thái delivery trong timeline.');}else if(command.failure.current?.status===409&&command.failure.current.code==='OWNER_CONFLICT'){setPending(undefined);}reload();}}>Kiểm tra lại yêu cầu gửi</Button></div>}
    <ErrorNotice error={command.error}/><Button type="submit" disabled={!allowed||stale||command.error?.status===409||command.busy||!text.trim()||!!pending}>{command.busy?'Đang xử lý…':mode==='reply'?'Gửi phản hồi':'Lưu ghi chú'}</Button>{notice&&<p role="status">{notice}</p>}
  </form>;
}
