'use client';
import { useState } from 'react';
import { Button } from '../../components/ui/button';
import { useApi,useCommand,ErrorNotice,can,type Context } from './api';
export function Metadata({tenant,context}:{tenant:string;context:Context}){
  const [key,setKey]=useState(context.objects[0]?.key??''),[objectKey,setObjectKey]=useState(''),[label,setLabel]=useState(''),command=useCommand(tenant);
  return <div className="crm-card"><h3>Cấu hình đối tượng</h3><p>Custom object dùng chung quyền, biểu mẫu và liên kết với dữ liệu CRM.</p>{can(context,'schema','create')&&<details><summary>Tạo đối tượng mới</summary><form className="crm-query" onSubmit={async e=>{e.preventDefault();const r=await command.run('/api/v1/object-types',{key:objectKey,label});if(r){setKey(objectKey);setObjectKey('');setLabel('');}}}><label>Key đối tượng<input required pattern="[a-z][a-z0-9_]*" maxLength={64} value={objectKey} onChange={e=>setObjectKey(e.target.value)}/></label><label>Tên hiển thị<input required maxLength={255} value={label} onChange={e=>setLabel(e.target.value)}/></label><Button type="submit" disabled={command.busy}>Tạo đối tượng</Button></form></details>}<ErrorNotice error={command.error}/><label>Đối tượng cấu hình<select aria-label="Đối tượng cấu hình" value={key} onChange={e=>setKey(e.target.value)}>{context.objects.map(o=><option key={o.id} value={o.key}>{o.label}</option>)}</select></label>{key&&<ObjectMetadata key={key} tenant={tenant} context={context} object={key}/>}<AssociationType tenant={tenant} context={context}/></div>;
}
function ObjectMetadata({tenant,context,object}:{tenant:string;context:Context;object:string}){
  const props=useApi(tenant,`/api/v1/object-types/${object}/properties`),descriptor=useApi(tenant,`/api/v1/objects/${object}/descriptor`),command=useCommand(tenant);
  const [editing,setEditing]=useState<any>(null),[label,setLabel]=useState('');
  const selected=context.objects.find(o=>o.key===object),writable=can(context,'schema','update');
  return <><h4>Thuộc tính tùy chỉnh</h4>{props.isPending?<p role="status">Đang tải thuộc tính…</p>:props.error?<ErrorNotice error={props.error}/>:<div className="crm-table-wrap"><table><thead><tr><th>Thuộc tính</th><th>Kiểu</th><th>Quy tắc</th><th/></tr></thead><tbody>{props.data.data.map((p:any)=><tr key={p.id}><td>{p.label}<small>{p.key}</small></td><td>{p.type}</td><td>{p.required?'Bắt buộc · ':''}{p.indexed?'Có thể truy vấn':'Chỉ lưu trữ'}</td><td>{writable&&<Button variant="outline" onClick={()=>{setEditing(p);setLabel(p.label);}}>Đổi nhãn</Button>}</td></tr>)}</tbody></table></div>}{editing&&<form className="crm-query" onSubmit={async e=>{e.preventDefault();if(await command.run(`/api/v1/object-types/${object}/properties/${editing.key}`,{label},'PATCH',editing.version))setEditing(null);}}><label>Nhãn mới<input required value={label} onChange={e=>setLabel(e.target.value)}/></label><Button type="submit" disabled={command.busy}>Lưu nhãn</Button></form>}<ErrorNotice error={command.error}/>{writable&&selected&&<PropertyCreate tenant={tenant} object={object} version={selected.version}/>}{descriptor.data&&<FormViewEditor tenant={tenant} object={object} fields={[...descriptor.data.data.standard,...descriptor.data.data.custom]} writable={writable}/>}</>;
}
function PropertyCreate({tenant,object,version}:{tenant:string;object:string;version:string}){
  const [body,setBody]=useState<any>({key:'',label:'',type:'string',required:false,indexed:true,sensitive:false}),[options,setOptions]=useState(''),[defaultValue,setDefault]=useState(''),command=useCommand(tenant),[localError,setLocalError]=useState('');
  const set=(k:string,v:any)=>setBody((old:any)=>({...old,[k]:v}));
  return <details><summary>Thêm thuộc tính</summary><form className="crm-form" onSubmit={async e=>{e.preventDefault();setLocalError('');const input={...body};if(input.type==='enum')input.options=options.split(',').map(v=>v.trim());if(defaultValue!=='')input.default_value=input.type==='integer'?Number(defaultValue):input.type==='boolean'?defaultValue==='true':defaultValue;const result=await command.run(`/api/v1/object-types/${object}/properties`,input,'POST',version);if(result){setBody({key:'',label:'',type:'string',required:false,indexed:true,sensitive:false});setDefault('');setOptions('');}}}><div className="crm-fields"><label>Key thuộc tính<input required pattern="[a-z][a-z0-9_]*" value={body.key} onChange={e=>set('key',e.target.value)}/></label><label>Nhãn thuộc tính<input required value={body.label} onChange={e=>set('label',e.target.value)}/></label><label>Kiểu dữ liệu<select aria-label="Kiểu dữ liệu" value={body.type} onChange={e=>{set('type',e.target.value);if(e.target.value==='text')set('indexed',false);}}>{['string','text','integer','decimal','boolean','date','datetime','enum'].map(v=><option key={v}>{v}</option>)}</select></label>{body.type==='enum'&&<label>Các lựa chọn, ngăn cách bằng dấu phẩy<input required value={options} onChange={e=>setOptions(e.target.value)}/></label>}<label>Giá trị mặc định (tùy chọn)<input value={defaultValue} onChange={e=>setDefault(e.target.value)}/></label></div>{[['required','Bắt buộc'],['indexed','Cho phép lọc / sắp xếp'],['sensitive','Dữ liệu nhạy cảm']].map(([key,label])=><label key={key} className="crm-check"><input type="checkbox" disabled={key==='indexed'&&body.type==='text'} checked={body[key!]} onChange={e=>set(key!,e.target.checked)}/>{label}</label>)}<p>Kiểu dữ liệu không thay đổi sau khi tạo. Thuộc tính bắt buộc chỉ thêm trước khi có record.</p>{localError&&<p role="alert">{localError}</p>}<ErrorNotice error={command.error}/><Button type="submit" disabled={command.busy}>Tạo thuộc tính</Button></form></details>;
}
function FormViewEditor({tenant,object,fields,writable}:{tenant:string;object:string;fields:any[];writable:boolean}){
  const form=useApi(tenant,`/api/v1/object-types/${object}/forms/default`),view=useApi(tenant,`/api/v1/object-types/${object}/views/default`);
  return <div className="crm-columns"><ConfigEditor key={'form'+form.data?.data.version} tenant={tenant} object={object} fields={fields} kind="forms" current={form.data?.data} writable={writable} loading={form.isPending} error={form.error}/><ConfigEditor key={'view'+view.data?.data.version} tenant={tenant} object={object} fields={fields} kind="views" current={view.data?.data} writable={writable} loading={view.isPending} error={view.error}/></div>;
}
function ConfigEditor({tenant,object,fields,kind,current,writable,loading,error}:{tenant:string;object:string;fields:any[];kind:'forms'|'views';current:any;writable:boolean;loading:boolean;error:any}){
  const [chosen,setChosen]=useState<string[]>(current?.fields??current?.columns??fields.map(f=>f.key)),[filter,setFilter]=useState<any[]>(current?.filter??[]),[sort,setSort]=useState(current?.sort?.field??''),[direction,setDirection]=useState(current?.sort?.direction??'asc'),command=useCommand(tenant);
  if(loading)return <p role="status">Đang tải cấu hình…</p>;if(error&&error.status!==404)return <ErrorNotice error={error}/>;
  return <form className="crm-form crm-editor" onSubmit={async e=>{e.preventDefault();const input=kind==='forms'?{fields:chosen}:{columns:chosen,filter:filter.map(p=>({...p,value:fields.find(f=>f.key===p.field)?.type==='integer'?Number(p.value):fields.find(f=>f.key===p.field)?.type==='boolean'?p.value==='true'||p.value===true:p.value})),sort:sort?{field:sort,direction}:null};await command.run(`/api/v1/object-types/${object}/${kind}/default`,input,'PUT',current?.version);}}><h4>{kind==='forms'?'Biểu mẫu mặc định':'Saved view mặc định'}</h4><fieldset disabled={!writable}><legend>Trường hiển thị & thứ tự</legend>{chosen.map((key,i)=><div className="crm-actions" key={key}><span>{fields.find(f=>f.key===key)?.label??key}</span><Button variant="outline" disabled={i===0} onClick={()=>setChosen(old=>{const next=[...old];[next[i-1],next[i]]=[next[i]!,next[i-1]!];return next;})}>↑</Button><Button variant="outline" onClick={()=>setChosen(old=>old.filter(v=>v!==key))}>Bỏ</Button></div>)}<label>Thêm trường<select aria-label="Thêm trường" value="" onChange={e=>e.target.value&&setChosen(old=>[...old,e.target.value])}><option value="">Chọn…</option>{fields.filter(f=>!chosen.includes(f.key)).map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>{kind==='views'&&<><label>Sắp xếp<select aria-label="Sắp xếp" value={sort} onChange={e=>setSort(e.target.value)}><option value="">Ngày tạo</option>{fields.filter(f=>f.indexed).map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label>Chiều<select aria-label="Chiều" value={direction} onChange={e=>setDirection(e.target.value)}><option value="asc">Tăng dần</option><option value="desc">Giảm dần</option></select></label>{filter.map((p,i)=><div className="crm-query" key={i}><label>Trường lọc<select aria-label="Trường lọc" value={p.field} onChange={e=>setFilter(old=>old.map((v,j)=>i===j?{...v,field:e.target.value}:v))}>{fields.filter(f=>f.indexed).map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label>Điều kiện<select aria-label="Điều kiện" value={p.op} onChange={e=>setFilter(old=>old.map((v,j)=>i===j?{...v,op:e.target.value}:v))}><option value="eq">Bằng</option><option value="gte">Lớn hơn hoặc bằng</option><option value="lte">Nhỏ hơn hoặc bằng</option></select></label><label>Giá trị<input value={p.value} onChange={e=>setFilter(old=>old.map((v,j)=>i===j?{...v,value:e.target.value}:v))}/></label><Button variant="outline" onClick={()=>setFilter(old=>old.filter((_,j)=>i!==j))}>Bỏ lọc</Button></div>)}<Button variant="outline" disabled={filter.length>=10||!fields.some(f=>f.indexed)} onClick={()=>setFilter(old=>[...old,{field:fields.find(f=>f.indexed).key,op:'eq',value:''}])}>Thêm điều kiện</Button></>}</fieldset><ErrorNotice error={command.error}/>{writable&&<Button type="submit" disabled={command.busy}>Lưu {kind==='forms'?'biểu mẫu':'view'}</Button>}</form>;
}
function AssociationType({tenant,context}:{tenant:string;context:Context}){
  const [body,setBody]=useState({key:'',label:'',source_type:'contact',target_type:'company',cardinality:'many_to_many'}),command=useCommand(tenant);
  if(!can(context,'schema','update'))return null;
  return <details className="crm-divider"><summary>Thêm loại liên kết</summary><form className="crm-form" onSubmit={async e=>{e.preventDefault();await command.run('/api/v1/association-types',body);}}>{(['key','label'] as const).map(k=><label key={k}>{k==='key'?'Key liên kết':'Tên liên kết'}<input required value={body[k]} onChange={e=>setBody({...body,[k]:e.target.value})}/></label>)}{(['source_type','target_type'] as const).map(k=><label key={k}>{k==='source_type'?'Đối tượng nguồn':'Đối tượng đích'}<select value={body[k]} onChange={e=>setBody({...body,[k]:e.target.value})}>{context.objects.map(o=><option key={o.id} value={o.key}>{o.label}</option>)}</select></label>)}<label>Quan hệ<select aria-label="Quan hệ" value={body.cardinality} onChange={e=>setBody({...body,cardinality:e.target.value})}><option value="many_to_many">Nhiều – nhiều</option><option value="one_to_many">Một – nhiều</option><option value="one_to_one">Một – một</option></select></label><ErrorNotice error={command.error}/><Button type="submit" disabled={command.busy}>Tạo loại liên kết</Button></form></details>;
}
