'use client';
import { useState } from 'react';
import { Button } from '../../components/ui/button';
import { useApi,useCommand,ErrorNotice,can,type Context } from './api';
export function Operations({tenant,context}:{tenant:string;context:Context}){
 const tabs=[...(can(context,'integration','read')?['deliveries']:[]),...(can(context,'automation','read')?['runs','agents']:[]),...(can(context,'automation','design')?['definitions']:[])],[tab,setTab]=useState(tabs[0]??'');
 return <div className="crm-card"><h3>Vận hành</h3><div className="crm-tabs">{tabs.map(t=><Button key={t} variant={tab===t?'default':'outline'} onClick={()=>setTab(t)}>{t==='deliveries'?'Inbound lỗi':t==='runs'?'Workflow runs':t==='agents'?'Agent Runtime':'Phiên bản automation'}</Button>)}</div>{tab==='deliveries'?<Deliveries tenant={tenant}/>:tab==='agents'?<AgentRuns tenant={tenant}/>:tab==='runs'?<Runs tenant={tenant}/>:tab==='definitions'?<Definitions tenant={tenant}/>:<p>Bạn chưa có quyền xem vận hành.</p>}</div>;
}
function Deliveries({tenant}:{tenant:string}){
 const [cursor,setCursor]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null),[reason,setReason]=useState(''),[pending,setPending]=useState<string|null>(null),[notice,setNotice]=useState(''),query=useApi(tenant,`/api/v1/operations/failed-deliveries?limit=25${cursor?`&cursor=${cursor}`:''}`,true,true),command=useCommand(tenant);
 async function retry(id:string){setPending(id);const result=await command.run(`/api/v1/operations/deliveries/${id}/retry`,{reason:'operator_retry'});if(result){setPending(null);setSelected(null);setReason('');setNotice('Đã lên lịch xử lý lại delivery cũ.');}else if(command.failure.current?.status&&command.failure.current.status<500)setPending(null);}
 if(query.isPending)return <p role="status">Đang tải delivery…</p>;if(query.error)return <ErrorNotice error={query.error} reload={()=>void query.refetch()}/>;
 return <><p>Chỉ xử lý lại inbound lỗi. Tin outbound chưa xác định kết quả cần kiểm tra riêng trong Chat.</p>{!query.data.data.length&&<p>Không có inbound lỗi.</p>}<ul className="record-list">{query.data.data.map((r:any)=><li key={r.id}><div><strong>{r.id}</strong><p>{r.error_code??'Lỗi xử lý'} · {r.attempts} lần thử</p><small>{r.next_attempt_at?`Sẽ thử lại ${new Date(r.next_attempt_at).toLocaleString('vi-VN')}`:'Chờ xử lý thủ công'}</small>{r.can_retry&&<Button variant="outline" onClick={()=>{setSelected(r.id);setReason('');setNotice('');}}>Xử lý lại</Button>}</div></li>)}</ul>{selected&&!pending&&<form onSubmit={e=>{e.preventDefault();if(reason==='operator_retry')void retry(selected);}}><p>Delivery: {selected}</p><label>Lý do retry<select required value={reason} onChange={e=>setReason(e.target.value)}><option value="">Chọn lý do…</option><option value="operator_retry">Đã kiểm tra, yêu cầu xử lý lại</option></select></label><Button type="submit" disabled={command.busy||reason!== 'operator_retry'}>Xác nhận xử lý lại</Button></form>}{pending&&<Button disabled={command.busy} onClick={()=>void retry(pending)}>Kiểm tra lại yêu cầu retry</Button>}<ErrorNotice error={command.error} reload={()=>void query.refetch()}/>{notice&&<p role="status">{notice}</p>}<div className="crm-toolbar">{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>Trang đầu</Button>}{query.data.next_cursor&&<Button variant="outline" onClick={()=>setCursor(query.data.next_cursor)}>Trang tiếp</Button>}</div></>;
}
function Runs({tenant}:{tenant:string}){
 const [cursor,setCursor]=useState<string|null>(null),[id,setId]=useState<string|null>(null),query=useApi(tenant,`/api/v1/operations/workflow-runs?limit=25${cursor?`&cursor=${cursor}`:''}`,true,true);
 return <div className="crm-record-layout"><section>{query.isPending?<p role="status">Đang tải runs…</p>:query.error?<ErrorNotice error={query.error} reload={()=>void query.refetch()}/>:<>{!query.data.data.length&&<p>Chưa có run trong quyền truy cập.</p>}<ul className="record-list">{query.data.data.map((r:any)=><li key={r.id}><button aria-pressed={id===r.id} onClick={()=>setId(r.id)}><strong>Run {r.id.slice(0,8)}</strong><span>{r.status} · {r.current_node}</span>{r.attention&&<small>Cần chú ý</small>}<small>{new Date(r.started_at).toLocaleString('vi-VN')}</small></button></li>)}</ul>{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>Trang đầu</Button>}{query.data.next_cursor&&<Button variant="outline" onClick={()=>setCursor(query.data.next_cursor)}>Trang tiếp</Button>}</>}</section><section>{id?<RunDetail key={id} tenant={tenant} id={id}/>:<p>Chọn run để xem tiến trình thực thi.</p>}</section></div>;
}
function RunDetail({tenant,id}:{tenant:string;id:string}){
 const query=useApi(tenant,`/api/v1/workflow-runs/${id}`,true,true);if(query.isPending)return <p role="status">Đang tải run…</p>;if(query.error)return <ErrorNotice error={query.error} reload={()=>void query.refetch()}/>;const r=query.data.data;
 return <><h4>Run {id.slice(0,8)}</h4><p>{r.status} · {r.error_code??'Không có lỗi'}</p><ol>{r.steps.map((s:any)=><li key={s.node_key}><strong>{s.node_key}</strong> · {s.status} · lần thử {s.attempt}{s.error_code&&<p>{s.error_code}</p>}</li>)}</ol>{r.waits.map((w:any)=><p key={w.node_key}>{w.node_key} · {w.kind} · {w.status} · {new Date(w.resume_at).toLocaleString('vi-VN')}</p>)}</>;
}
function Definitions({tenant}:{tenant:string}){
 const [kind,setKind]=useState('workflows'),[id,setId]=useState<string|null>(null),list=useApi(tenant,`/api/v1/${kind}?limit=100`),versions=useApi(tenant,`/api/v1/${kind}/${id}/versions?limit=100`,!!id);
 return <><label>Loại automation<select value={kind} onChange={e=>{setKind(e.target.value);setId(null);}}><option value="workflows">Workflow</option><option value="chatflows">Chatflow</option></select></label>{list.isPending?<p>Đang tải definitions…</p>:list.error?<ErrorNotice error={list.error}/>:<ul className="record-list">{list.data.data.map((d:any)=><li key={d.id}><button onClick={()=>setId(d.id)}>{d.name} · v{d.version}</button></li>)}</ul>}{id&&(versions.isPending?<p>Đang tải phiên bản…</p>:versions.error?<ErrorNotice error={versions.error}/>:versions.data.data.map((v:any)=><details key={v.id}><summary>Phiên bản {v.number} · {v.state}</summary><pre style={{overflow:'auto',maxHeight:400}}>{JSON.stringify(v.graph,null,2)}</pre></details>))}</>;
}

function AgentRuns({tenant}:{tenant:string}){
 const [cursor,setCursor]=useState<string|null>(null),query=useApi(tenant,`/api/v1/operations/agent-executions?limit=25${cursor?`&cursor=${cursor}`:''}`,true,true);
 if(query.isPending)return <p role="status">Đang tải Agent Runtime…</p>;if(query.error)return <ErrorNotice error={query.error} reload={()=>void query.refetch()}/>;
 return <>{!query.data.data.length&&<p>Chưa có lần chạy trong quyền truy cập.</p>}<ul className="record-list">{query.data.data.map((r:any)=><li key={r.id}><strong>Agent {r.id.slice(0,8)}</strong><p>{r.status} · {r.error_code??'Không có lỗi'}{r.attention?' · Cần chú ý':''}</p><small>{new Date(r.created_at).toLocaleString('vi-VN')}</small></li>)}</ul>{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>Trang đầu</Button>}{query.data.next_cursor&&<Button variant="outline" onClick={()=>setCursor(query.data.next_cursor)}>Trang tiếp</Button>}</>;
}
