'use client';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Button } from '../../components/ui/button';
import { useApi,useCommand,ErrorNotice,can,type Context } from './api';
interface Field {key:string;label:string;type:string;required?:boolean;options?:string[];default_value?:unknown;writable:boolean;immutable?:boolean;indexed?:boolean}
interface Descriptor {standard:Field[];custom:Field[];order:string[]}
const label=(r:any)=>r.fields?.display_name??r.fields?.name??r.fields?.subject??r.fields?.qualification?.service_interest??r.custom_values?.title??r.custom_values?.name_label??r.custom_values?.name??Object.values(r.custom_values??{}).find(v=>typeof v==='string')??r.id.slice(0,8);
export function Records({tenant,context,initial}:{tenant:string;context:Context;initial?:{object:string;id:string}}){
  const objects=context.objects.filter(o=>o.kind==='custom'||['contact','company','activity','lead'].includes(o.key));
  const [object,setObject]=useState(initial?.object??objects[0]?.key??'contact');
  if(!objects.length)return <div className="crm-card"><h3>Chưa có quyền đọc dữ liệu CRM</h3><p>Quản trị viên cần cấp quyền theo đối tượng và phạm vi làm việc.</p></div>;
  return <><div className="crm-object-nav" aria-label="Đối tượng CRM">{objects.map(o=><Button key={o.id} variant={object===o.key?'default':'outline'} onClick={()=>setObject(o.key)}>{o.label}</Button>)}</div><RecordCollection key={object} tenant={tenant} context={context} object={object} initialId={initial?.object===object?initial.id:undefined}/></>;
}
function RecordCollection({tenant,context,object,initialId}:{tenant:string;context:Context;object:string;initialId?:string}){
  const [id,setId]=useState<string|null>(initialId??null),[creating,setCreating]=useState(false),[cursor,setCursor]=useState<string|null>(null),[filter,setFilter]=useState(''),[sort,setSort]=useState('');
  const descriptor=useApi(tenant,`/api/v1/objects/${object}/descriptor`),query=new URLSearchParams({limit:'20',...(cursor?{cursor}:{}),...(filter?{filter}:{}),...(sort?{sort}:{})});
  const list=useApi(tenant,`/api/v1/objects/${object}/records?${query}`),name=context.objects.find(o=>o.key===object)?.label??object;
  const savedView=useApi(tenant,`/api/v1/object-types/${object}/views/default`,can(context,'schema','read'));
  const [columns,setColumns]=useState<string[]|null>(null);
  const desc=descriptor.data?.data as Descriptor|undefined;
  return <div className="crm-record-layout"><section className="crm-card crm-list"><div className="crm-toolbar"><h3>{name}</h3>{can(context,object,'create')&&<Button onClick={()=>{setId(null);setCreating(true);}}>Tạo {name}</Button>}</div>
    {savedView.data&&<Button variant="outline" onClick={()=>{setFilter(JSON.stringify(savedView.data.data.filter));setSort(savedView.data.data.sort?JSON.stringify(savedView.data.data.sort):'');setColumns(savedView.data.data.columns);setCursor(null);}}>Dùng saved view</Button>}
    {desc&&<QueryControls descriptor={desc} onChange={(f,s)=>{setFilter(f);setSort(s);setCursor(null);}}/>}
    {list.isPending?<p role="status">Đang tải records…</p>:list.error?<ErrorNotice error={list.error} reload={()=>void list.refetch()}/>:<>
      {!list.data.data.length?<p className="crm-empty">Chưa có record phù hợp.</p>:<ul className="record-list">{list.data.data.map((r:any)=><li key={r.id}><button type="button" aria-pressed={id===r.id} onClick={()=>{setCreating(false);setId(r.id);}}><strong>{String(label(r))}</strong><span>{r.fields?.status??(r.owner_principal_id===context.principal_id?'Của bạn':r.owner_principal_id?'Đã phân công':'Chưa phân công')}</span>{columns?.map(k=><small key={k}>{k}: {String(r.custom_values?.[k]??r.fields?.[k]??'—')}</small>)}<small>{r.id.slice(0,8)} · v{r.version}</small></button></li>)}</ul>}
      <div className="crm-toolbar">{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>Trang đầu</Button>}{list.data.next_cursor&&<Button variant="outline" onClick={()=>setCursor(list.data.next_cursor)}>Trang tiếp</Button>}</div></>}
  </section><section className="crm-card crm-detail">{descriptor.isPending?<p role="status">Đang tải cấu trúc dữ liệu…</p>:descriptor.error?<ErrorNotice error={descriptor.error}/>:creating&&desc?(object==='lead'?<LeadCreate tenant={tenant} onCreated={r=>{setCreating(false);setId(r.id);}}/>:<RecordForm tenant={tenant} context={context} object={object} descriptor={desc} onSaved={r=>{setCreating(false);setId(r.id);}}/>):id&&desc?<RecordDetail key={id} tenant={tenant} context={context} object={object} id={id} descriptor={desc}/>:<div className="crm-empty"><h3>Chọn một record</h3><p>Xem thông tin, cập nhật dữ liệu và liên kết các đối tượng.</p></div>}</section></div>;
}
function QueryControls({descriptor,onChange}:{descriptor:Descriptor;onChange:(filter:string,sort:string)=>void}){
  const fields=[...descriptor.standard,...descriptor.custom].filter(f=>f.indexed),[field,setField]=useState(''),[input,setInput]=useState(''),[sort,setSort]=useState(''),[error,setError]=useState('');
  return <form className="crm-query" onSubmit={e=>{e.preventDefault();try{const f=fields.find(f=>f.key===field),v=f?.type==='integer'?Number(input):f?.type==='boolean'?input==='true':input;onChange(field?JSON.stringify([{field,op:'eq',value:v}]):'',sort?JSON.stringify({field:sort,direction:'asc'}):'');setError('');}catch{setError('Giá trị lọc không hợp lệ.');}}}><label>Lọc theo<select aria-label="Lọc theo" value={field} onChange={e=>setField(e.target.value)}><option value="">Tất cả</option>{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>{field&&<label>Giá trị bằng<input value={input} onChange={e=>setInput(e.target.value)}/></label>}<label>Sắp xếp<select aria-label="Sắp xếp" value={sort} onChange={e=>setSort(e.target.value)}><option value="">Ngày tạo</option>{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><Button variant="outline" type="submit">Áp dụng</Button>{error&&<span role="alert">{error}</span>}</form>;
}
function RecordDetail({tenant,context,object,id,descriptor}:{tenant:string;context:Context;object:string;id:string;descriptor:Descriptor}){
  const record=useApi(tenant,`/api/v1/objects/${object}/records/${id}`);
  if(record.isPending)return <p role="status">Đang tải chi tiết…</p>;if(record.error)return <ErrorNotice error={record.error} reload={()=>void record.refetch()}/>;
  const r=record.data.data;
  return <><div className="crm-detail-heading"><h3>{String(label(r))}</h3><span className="crm-badge">{r.archived?'Đã lưu trữ':r.fields.status??'Đang hoạt động'}</span><small className="crm-record-id">{r.id}</small><p>Owner: {r.owner_principal_id===context.principal_id?'Bạn':r.owner_principal_id??'Chưa phân công'} · Phiên bản {r.version}</p></div>
    {object==='lead'?<LeadQualification key={r.version} tenant={tenant} context={context} record={r} editable={descriptor.standard.some(f=>f.key==='qualification'&&f.writable)} reload={()=>void record.refetch()}/>:<RecordForm key={r.version} tenant={tenant} context={context} object={object} descriptor={descriptor} record={r} onSaved={()=>void record.refetch()} reload={()=>void record.refetch()}/>}
    {!r.archived&&object!=='lead'&&can(context,object,'archive',r)&&<Archive tenant={tenant} object={object} record={r}/>}
    {can(context,'association','read')&&<Associations tenant={tenant} context={context} record={r}/>}
  </>;
}
function FieldControl({field,path,register,disabled}:{field:Field;path:string;register:ReturnType<typeof useForm>['register'];disabled?:boolean}){
  const common={...register(path),disabled,'aria-label':field.label};
  return <label className="crm-field">{field.label}{field.required?' *':''}{field.type==='enum'?<select {...common} required={field.required}><option value="">Chọn…</option>{field.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:field.type==='boolean'?<select {...common} required={field.required}><option value="">Chưa đặt</option><option value="true">Có</option><option value="false">Không</option></select>:field.type==='preference'?<select {...common}><option value="">Chưa đặt</option><option value="messenger">Messenger</option><option value="phone">Điện thoại</option><option value="email">Email</option></select>:field.type==='text'?<textarea {...common} rows={3} maxLength={4000} required={field.required}/>:<input {...common} type={field.type==='integer'?'number':field.type==='date'?'date':field.type==='datetime'?'datetime-local':'text'} step={field.type==='integer'?1:undefined} maxLength={field.type==='string'?255:undefined} required={field.required}/>}</label>;
}
function inputValue(f:Field,v:any){if(v===null||v===undefined)return '';if(f.type==='boolean')return String(v);if(f.type==='datetime')return String(v).slice(0,16);if(f.type==='preference')return v.preferred_contact_method??'';return v;}
function wireValue(f:Field,v:any){if(v===''||v===undefined)return f.type==='preference'?{}:null;if(f.type==='boolean')return v==='true';if(f.type==='integer')return Number(v);if(f.type==='datetime')return new Date(v+'Z').toISOString();if(f.type==='preference')return {preferred_contact_method:v};return v;}
function RecordForm({tenant,context,object,descriptor,record,onSaved,reload}:{tenant:string;context:Context;object:string;descriptor:Descriptor;record?:any;onSaved:(r:any)=>void;reload?:()=>void}){
  const defaults:any={std:{},custom:{}};for(const [group,fields] of [['std',descriptor.standard],['custom',descriptor.custom]] as const)for(const f of fields)defaults[group][f.key]=inputValue(f,record?(group==='std'?record.fields:record.custom_values)[f.key]:f.default_value);
  const {register,handleSubmit}=useForm({defaultValues:defaults}),command=useCommand(tenant),editable=!record?.archived&&can(context,object,record?'update':'create',record);
  const save=handleSubmit(async input=>{const body:any={fields:{},custom_values:{}};for(const [group,fields] of [['std',descriptor.standard],['custom',descriptor.custom]] as const)for(const f of fields){if(!f.writable||record&&f.immutable)continue;const v=wireValue(f,input[group]?.[f.key]);if(!record&&v===null)continue;body[group==='std'?'fields':'custom_values'][f.key]=v;}
    const result=await command.run(`/api/v1/objects/${object}/records${record?'/'+record.id:''}`,body,record?'PATCH':'POST',record?.version);if(result)onSaved(result.data);
  });
  const fields=descriptor.order.flatMap(k=>{const standard=descriptor.standard.find(f=>f.key===k),f=standard??descriptor.custom.find(f=>f.key===k);return f?[{field:f,group:standard?'std':'custom'}]:[];});
  return <form onSubmit={save} className="crm-form" aria-label={record?'Sửa record':'Tạo record'}><h3>{record?'Thông tin':'Record mới'}</h3><div className="crm-fields">{fields.map(({field,group})=><FieldControl key={group+field.key} field={field} path={`${group}.${field.key}`} register={register} disabled={!editable||!field.writable||!!record&&field.immutable}/>)}</div><ErrorNotice error={command.error} reload={reload}/>{editable&&<Button type="submit" disabled={command.busy}>{command.busy?'Đang lưu…':record?'Lưu thay đổi':'Tạo record'}</Button>}</form>;
}
function Archive({tenant,object,record}:{tenant:string;object:string;record:any}){
  const [reason,setReason]=useState(''),[open,setOpen]=useState(false),command=useCommand(tenant);
  return <div className="crm-divider">{!open?<Button variant="outline" onClick={()=>setOpen(true)}>Lưu trữ record</Button>:<form onSubmit={async e=>{e.preventDefault();if(await command.run(`/api/v1/objects/${object}/records/${record.id}/archive`,{reason},'POST',record.version))setOpen(false);}}><label>Lý do lưu trữ<input required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Record sẽ được ẩn khỏi danh sách hoạt động.</p><Button type="submit" variant="destructive" disabled={command.busy}>Xác nhận lưu trữ</Button> <Button variant="outline" onClick={()=>setOpen(false)}>Hủy</Button><ErrorNotice error={command.error}/></form>}</div>;
}
function LeadCreate({tenant,onCreated}:{tenant:string;onCreated:(r:any)=>void}){
  const contacts=useApi(tenant,'/api/v1/objects/contact/records?limit=100'),command=useCommand(tenant),[contact,setContact]=useState('');
  return <form className="crm-form" onSubmit={async e=>{e.preventDefault();const r=await command.run('/api/v1/leads',{contact_id:contact});if(r)onCreated(r.data);}}><h3>Lead mới</h3><label>Liên hệ<select aria-label="Liên hệ" required value={contact} onChange={e=>setContact(e.target.value)}><option value="">Chọn liên hệ…</option>{contacts.data?.data.map((r:any)=><option key={r.id} value={r.id}>{String(label(r))}</option>)}</select></label><p>Mỗi nhu cầu là một Lead riêng. Qualification được lưu ở bước tiếp theo.</p><ErrorNotice error={contacts.error??command.error}/><Button type="submit" disabled={command.busy||!contact}>Tạo Lead</Button></form>;
}
function LeadQualification({tenant,context,record,editable,reload}:{tenant:string;context:Context;record:any;editable:boolean;reload:()=>void}){
  const q=record.fields.qualification,[values,setValues]=useState<any>({...q,consent_evidence:q?.consent_evidence?{kind:'manual',note:q.consent_evidence.note}:undefined}),[reason,setReason]=useState(''),command=useCommand(tenant);
  const allowed=editable&&can(context,'lead','qualify',record)&&['new','qualifying'].includes(record.fields.status);
  if(q===undefined)return <p>Qualification không nằm trong quyền đọc của bạn.</p>;
  const set=(k:string,v:unknown)=>setValues((old:any)=>({...old,[k]:v}));
  const submit=async(action:'draft'|'qualify'|'disqualify')=>{const body=action==='draft'?{fields:{qualification:values}}:action==='qualify'?{qualification:values}:{reason};await command.run(action==='draft'?`/api/v1/objects/lead/records/${record.id}`:`/api/v1/leads/${record.id}/${action==='qualify'?'qualification':'disqualify'}`,body,action==='draft'?'PATCH':'POST',record.version);};
  return <div className="crm-form"><h3>Nhu cầu & đồng ý liên hệ</h3><p>Contact: {record.fields.contact_id}</p><label>Dịch vụ quan tâm<input disabled={!allowed} value={values.service_interest??''} maxLength={255} onChange={e=>set('service_interest',e.target.value)}/></label><label>Tóm tắt nhu cầu<textarea disabled={!allowed} value={values.need_summary??''} maxLength={4000} onChange={e=>set('need_summary',e.target.value)}/></label><label>Phương thức liên hệ<select aria-label="Phương thức liên hệ" disabled={!allowed} value={values.preferred_contact_method??''} onChange={e=>set('preferred_contact_method',e.target.value)}><option value="">Chọn…</option><option value="messenger">Messenger</option><option value="phone">Điện thoại</option></select></label><label>Số điện thoại (+84…)<input disabled={!allowed} value={values.phone??''} onChange={e=>set('phone',e.target.value||null)}/></label><label className="crm-check"><input type="checkbox" disabled={!allowed} checked={values.contact_permission===true} onChange={e=>set('contact_permission',e.target.checked)}/>Khách đã đồng ý được liên hệ</label><label>Bằng chứng đồng ý (ghi nhận thủ công)<textarea disabled={!allowed} value={values.consent_evidence?.note??''} maxLength={1000} onChange={e=>set('consent_evidence',{kind:'manual',note:e.target.value})}/></label>{q.consent_evidence?.recorded_at&&<small>Đã ghi nhận: {q.consent_evidence.recorded_at}</small>}<ErrorNotice error={command.error} reload={reload}/>{allowed&&<><div className="crm-actions"><Button variant="outline" disabled={command.busy} onClick={()=>void submit('draft')}>Lưu nháp</Button><Button disabled={command.busy} onClick={()=>void submit('qualify')}>Xác nhận đủ điều kiện</Button></div><details><summary>Loại Lead</summary><label>Lý do<input value={reason} onChange={e=>setReason(e.target.value)}/></label><Button variant="destructive" disabled={command.busy||!reason.trim()} onClick={()=>void submit('disqualify')}>Xác nhận loại</Button></details></>}</div>;
}
function Associations({tenant,context,record}:{tenant:string;context:Context;record:any}){
  const list=useApi(tenant,`/api/v1/records/${record.id}/associations`),types=useApi(tenant,'/api/v1/association-types?limit=100',can(context,'schema','read'));
  const [type,setType]=useState(''),[target,setTarget]=useState(''),command=useCommand(tenant),sourceType=context.objects.find(o=>o.key===record.object_key)?.id;
  const options=types.data?.data.filter((t:any)=>t.source_object_type_id===sourceType)??[],chosen=options.find((t:any)=>t.key===type),targetObject=context.objects.find(o=>o.id===chosen?.target_object_type_id)?.key;
  const targets=useApi(tenant,`/api/v1/objects/${targetObject??'contact'}/records?limit=100`,!!targetObject);
  return <section className="crm-divider"><h3>Liên kết</h3><ErrorNotice error={list.error??command.error}/>{list.data?.data.length?<ul>{list.data.data.map((a:any)=><li key={a.id}>{a.source_record_id===record.id?'→':'←'} {a.source_record_id===record.id?a.target_record_id:a.source_record_id}</li>)}</ul>:<p>Chưa có liên kết hiển thị.</p>}{!record.archived&&can(context,'association','create')&&can(context,record.object_key,'update',record)&&<form className="crm-form" onSubmit={async e=>{e.preventDefault();if(await command.run('/api/v1/associations',{type_key:type,source_record_id:record.id,target_record_id:target},'POST',record.version))setTarget('');}}><label>Loại liên kết<select aria-label="Loại liên kết" required value={type} onChange={e=>{setType(e.target.value);setTarget('');}}><option value="">Chọn…</option>{options.map((t:any)=><option key={t.id} value={t.key}>{t.label}</option>)}</select></label><label>Record đích<select aria-label="Record đích" required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Chọn…</option>{targets.data?.data.map((r:any)=><option key={r.id} value={r.id}>{String(label(r))}</option>)}</select></label><ErrorNotice error={targets.error}/><Button type="submit" disabled={command.busy||!type||!target}>Thêm liên kết</Button></form>}</section>;
}
