'use client';
import { useState } from 'react';
import { Button } from '../../components/ui/button';
import { useApi,useCommand,ErrorNotice,type Context } from './api';
const age=(v:string|undefined)=>v?`${Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000))} phút`:'—';
const time=(v:string|null)=>v?new Date(v).toLocaleString('vi-VN'):'—';
export function Sales({tenant,context,open}:{tenant:string;context:Context;open:(kind:'contact'|'lead'|'conversation',id:string)=>void}){
 const [status,setStatus]=useState('handed_off'),[owner,setOwner]=useState('all'),[team,setTeam]=useState(''),[teamInput,setTeamInput]=useState(''),[source,setSource]=useState('all'),[cursor,setCursor]=useState<string|null>(null),[id,setId]=useState<string|null>(null);
 const params=new URLSearchParams({status,owner,source,limit:'25',...(team?{team}:{}),...(cursor?{cursor}:{} )}),queue=useApi(tenant,`/api/v1/sales/leads?${params}`,true,true);
 function filter(change:()=>void){change();setCursor(null);setId(null);}
 return <div className="crm-record-layout"><section className="crm-card"><h3>Hàng chờ Sales</h3><div className="crm-form-grid">
  <label>Trạng thái Sales<select value={status} onChange={e=>filter(()=>setStatus(e.target.value))}><option value="handed_off">Chờ nhận</option><option value="accepted">Đã nhận</option></select></label>
  <label>Phân công Sales<select value={owner} onChange={e=>filter(()=>setOwner(e.target.value))}><option value="all">Tất cả trong quyền truy cập</option><option value="mine">Của tôi</option><option value="unassigned">Chưa phân công</option></select></label>
  <label>Nguồn Lead<select value={source} onChange={e=>filter(()=>setSource(e.target.value))}><option value="all">Tất cả nguồn</option><option value="ctm">CTM</option><option value="unknown">Chưa xác định</option></select></label>
  <form onSubmit={e=>{e.preventDefault();filter(()=>setTeam(teamInput.trim()));}}><label>Sales team ID<input value={teamInput} onChange={e=>setTeamInput(e.target.value)} placeholder="Tất cả team được phép"/></label><Button type="submit" variant="outline">Lọc team</Button></form></div>
  {queue.isPending?<p role="status">Đang tải Lead…</p>:queue.error?<ErrorNotice error={queue.error} reload={()=>void queue.refetch()}/>:<>{!queue.data.data.length&&<p>Chưa có Lead phù hợp.</p>}<ul className="record-list">{queue.data.data.map((item:any)=>{const r=item.record;return <li key={r.id}><button aria-pressed={id===r.id} onClick={()=>setId(r.id)}><strong>{r.fields.qualification?.service_interest??`Lead ${r.id.slice(0,8)}`}</strong><span>{item.handoff?.status==='accepted'?'Đã nhận':'Chờ nhận'} · {r.owner_principal_id===context.principal_id?'Của bạn':r.owner_principal_id?'Đã phân công':'Chưa phân công'}</span><small>{r.fields.qualification?.need_summary??'—'}</small><small>Qualified: {time(r.fields.qualified_at)} · Đã chờ {age(r.fields.qualified_at)} · Nguồn: {item.source??'Ẩn theo quyền'}</small>{item.handoff?.attention&&<span>Cần chú ý · Hạn nhận {time(item.handoff.due_at)}</span>}</button></li>;})}</ul><div className="crm-toolbar">{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>Trang đầu</Button>}{queue.data.next_cursor&&<Button variant="outline" onClick={()=>setCursor(queue.data.next_cursor)}>Trang tiếp</Button>}</div></>}
 </section><section className="crm-card">{id?<SalesDetail key={`${tenant}:${id}`} tenant={tenant} id={id} open={open}/>:<p>Chọn Lead để xem nhu cầu và nhận bàn giao.</p>}</section></div>;
}
function SalesDetail({tenant,id,open}:{tenant:string;id:string;open:(kind:'contact'|'lead'|'conversation',id:string)=>void}){
 const query=useApi(tenant,`/api/v1/sales/leads/${id}`,true,true),command=useCommand(tenant),[notice,setNotice]=useState(''),[pending,setPending]=useState<{version:string;owner_revision:string;handoff_id:string}|null>(null);
 async function accept(input:{version:string;owner_revision:string;handoff_id:string}){setPending(input);const result=await command.run(`/api/v1/leads/${id}/handoffs/${input.handoff_id}/accept`,{owner_revision:input.owner_revision},'POST',input.version);if(result){setPending(null);setNotice('Đã nhận Lead.');}else if(command.failure.current?.status&&command.failure.current.status<500){setPending(null);}await query.refetch();}
 if(query.isPending)return <p role="status">Đang tải chi tiết Lead…</p>;if(query.error)return <ErrorNotice error={query.error} reload={()=>void query.refetch()}/>;
 const d=query.data.data,r=d.record,q=r.fields.qualification??{},stale=command.error?.status===409;
 return <><h3>{q.service_interest??'Chi tiết Lead'}</h3><p>{q.need_summary??'Nhu cầu không được hiển thị.'}</p><dl><dt>Trạng thái</dt><dd>{d.handoff?.status==='accepted'?'Đã nhận':'Chờ nhận'}</dd><dt>Owner</dt><dd>{r.owner_principal_id??'Chưa phân công'}</dd><dt>Team</dt><dd>{r.team_id??'—'}</dd><dt>Đồng ý liên hệ</dt><dd>{q.contact_permission===true?'Đã đồng ý':q.contact_permission===false?'Không đồng ý':'Ẩn theo quyền'}</dd><dt>Phương thức</dt><dd>{q.preferred_contact_method??'—'} {q.phone??''}</dd><dt>Hạn nhận</dt><dd>{time(d.handoff?.due_at)}</dd><dt>Đã nhận lúc</dt><dd>{time(d.handoff?.accepted_at)}</dd></dl>
  <div className="crm-toolbar">{d.contact&&<Button variant="outline" onClick={()=>open('contact',d.contact.id)}>Mở Contact: {d.contact.label}</Button>}<Button variant="outline" onClick={()=>open('lead',id)}>Mở Lead trong CRM</Button>{d.conversation_id&&<Button variant="outline" onClick={()=>open('conversation',d.conversation_id)}>Mở Conversation</Button>}</div>
  <ErrorNotice error={command.error}/>{stale&&<div role="alert"><p>Lead đã thay đổi. Kiểm tra owner mới trước khi tiếp tục.</p><Button variant="outline" onClick={()=>{command.setError(null);void query.refetch();}}>Đã xem trạng thái mới</Button></div>}
  {pending?<Button disabled={command.busy} onClick={()=>void accept(pending)}>Kiểm tra lại yêu cầu nhận</Button>:d.can_accept&&<Button disabled={command.busy||stale} onClick={()=>void accept({version:r.version,owner_revision:r.owner_revision,handoff_id:d.handoff.id})}>{command.busy?'Đang nhận…':'Nhận Lead'}</Button>}{notice&&<p role="status">{notice}</p>}
 </>;
}
