import { describe,it,expect } from 'vitest';
import { randomBytes,createHmac } from 'node:crypto';
import { MessengerAuth,metaApps,parseMessenger } from '../src/messenger.js';
const secret=randomBytes(32).toString('hex'),token=randomBytes(32).toString('hex');
const config=[{id:'100',secret_env:'CONNECTOR_META_SECRET',verify_env:'CONNECTOR_META_VERIFY'}];
const auth=new MessengerAuth(config,{CONNECTOR_META_SECRET:secret,CONNECTOR_META_VERIFY:token});
const message=(extra={})=>({sender:{id:'200'},recipient:{id:'300'},timestamp:1791244800000,message:{mid:'synthetic-mid',text:'Xin chào 👋',...extra}});
const body=(events:unknown[],stream='messaging')=>Buffer.from(JSON.stringify({object:'page',entry:[{id:'300',time:1,[stream]:events}]}));
describe('Messenger signed raw contract',()=>{
 it('requires explicit app references and rejects secret values or duplicate app IDs',()=>{expect(metaApps(undefined)).toEqual([]);expect(metaApps(JSON.stringify(config))).toEqual(config);for(const v of [[...config,...config],[{...config[0],secret:'secret'}],[{...config[0],secret_env:secret}]])expect(()=>metaApps(JSON.stringify(v))).toThrow('INVALID_META_CONFIG');});
 it('verifies original bytes including whitespace and Unicode without reserialization',()=>{const raw=Buffer.from(' '+body([message()]).toString()+'\n'),signature='sha256='+createHmac('sha256',secret).update(raw).digest('hex');expect(auth.verify('100',raw,signature)).toEqual(raw);expect(()=>auth.verify('100',body([message()]),signature)).toThrow('WEBHOOK_FORBIDDEN');});
 it('rejects absent signature, wrong app, wrong secret and unsupported signature versions',()=>{for(const sig of [undefined,'sha1='+'a'.repeat(40),'sha256='+'0'.repeat(64),['sha256='+'a'.repeat(64)]])expect(()=>auth.verify('100',body([message()]),sig)).toThrow();expect(()=>auth.verify('101',body([message()]),'sha256='+'a'.repeat(64))).toThrow();});
 it('verifies exact challenge and fails closed on arrays or nondecimal reflected input',()=>{const q={'hub.mode':'subscribe','hub.verify_token':token,'hub.challenge':'001234'};expect(auth.challenge('100',q)).toBe('001234');for(const bad of [{...q,'hub.challenge':'<script>'},{...q,'hub.verify_token':'wrong'},{...q,'hub.mode':['subscribe']},{...q,extra:'x'}])expect(()=>auth.challenge('100',bad)).toThrow();});
 it('retains original text and reply while keeping echo/standby out of active inbound',()=>{expect(parseMessenger(body([message({reply_to:{mid:'earlier'}})]))[0]?.normalized).toMatchObject({text:'Xin chào 👋',text_source:'original',reply_to:{external_msg_id:'earlier'}});expect(parseMessenger(body([message()],'standby'))[0]?.status).toBe('attention');const echo={...message({is_echo:true}),sender:{id:'300'},recipient:{id:'200'}};expect(parseMessenger(body([echo]))[0]?.kind).toBe('echo');expect(parseMessenger(body([echo]))[0]?.status).toBe('attention');});
 it('uses message ID across wrapper reorder and refuses truthy malformed echo and wrong recipient',()=>{const first=parseMessenger(body([message()]))[0]!;const second=parseMessenger(Buffer.from(JSON.stringify({entry:[{time:2,messaging:[message()],id:'300'}],object:'page'})))[0]!;expect(first.event_key).toBe(second.event_key);expect(first.digest).toBe(second.digest);for(const v of [message({is_echo:'true'}),{...message(),recipient:{id:'999'}}])expect(()=>parseMessenger(body([v]))).toThrow();});
 it('does not fetch attachments and retains unsupported content for attention',()=>{const p=parseMessenger(body([message({attachments:[{type:'image',payload:{url:'https://media.example.invalid/a'}}]})]))[0]!;expect(p.normalized.attachments).toEqual([{type:'image',url:'https://media.example.invalid/a',provider_id:null}]);expect(parseMessenger(body([message({unknown:'extension'})]))[0]?.status).toBe('attention');expect(parseMessenger(body([message({attachments:[{type:'appointment_booking',payload:{}}]})]))[0]?.kind).toBe('unsupported');});
 it('rejects malformed URLs, oversize text, invalid timestamps, mixed entry types and empty batches',()=>{const samples=[body([message({attachments:[{type:'image',payload:{url:'http://127.0.0.1'}}]})]),body([message({text:'x'.repeat(4001)})]),body([{...message(),timestamp:1e30}]),Buffer.from('{"object":"page","entry":[]}'),Buffer.from('{"object":"page","entry":[{"id":"300","changes":[]}]}'),body(Array.from({length:101},()=>message()))];for(const v of samples)expect(()=>parseMessenger(v)).toThrow('INVALID_WEBHOOK');});
 it('keeps nonmessage receipt and control outside customer text/consent',()=>{for(const field of ['delivery','read','pass_thread_control','postback']){const event={sender:{id:'200'},recipient:{id:'300'},timestamp:1,[field]:{mid:'synthetic'}};const parsed=parseMessenger(body([event]))[0]!;expect(parsed.status).toBe('attention');expect(parsed.normalized.text).toBeNull();}});
});
