import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin',node='VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin',eng='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
export const chatflowMigration:Migration={version:14,name:'chatflow_sessions',statements:[
`CREATE TABLE chatflow_definition(id ${id} PRIMARY KEY,tenant_id ${id} NOT NULL,\`key\` VARCHAR(64) NOT NULL,name VARCHAR(255) NOT NULL,active_version_id ${id} NULL,version BIGINT UNSIGNED NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),UNIQUE(tenant_id,\`key\`),FOREIGN KEY(tenant_id) REFERENCES tenant(id)) ${eng}`,
`CREATE TABLE chatflow_version(id ${id} PRIMARY KEY,tenant_id ${id} NOT NULL,definition_id ${id} NOT NULL,number INT UNSIGNED NOT NULL,graph JSON NOT NULL,state VARCHAR(16) NOT NULL CHECK(state IN('draft','published')),UNIQUE(tenant_id,id),UNIQUE(tenant_id,definition_id,id),UNIQUE(tenant_id,definition_id,number),FOREIGN KEY(tenant_id,definition_id) REFERENCES chatflow_definition(tenant_id,id)) ${eng}`,
'ALTER TABLE chatflow_definition ADD FOREIGN KEY(tenant_id,id,active_version_id) REFERENCES chatflow_version(tenant_id,definition_id,id)',
`CREATE TABLE chatflow_session(id ${id} PRIMARY KEY,tenant_id ${id} NOT NULL,version_id ${id} NOT NULL,parent_run_id ${id} NOT NULL,start_action_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,conversation_id ${id} NOT NULL,service_actor_id ${id} NOT NULL,execution_role_id ${id} NOT NULL,node_key ${node} NOT NULL,status VARCHAR(24) NOT NULL CHECK(status IN('running','waiting_message','paused_human','completed','failed','cancelled')),active_conversation_key ${id} GENERATED ALWAYS AS (CASE WHEN status IN('running','waiting_message','paused_human') THEN conversation_id ELSE NULL END) STORED,version BIGINT UNSIGNED NOT NULL DEFAULT 1,owner_revision BIGINT UNSIGNED NOT NULL,variables JSON NOT NULL DEFAULT (JSON_OBJECT()),draft JSON NOT NULL DEFAULT (JSON_OBJECT()),provenance JSON NOT NULL DEFAULT (JSON_OBJECT()),last_message_id ${id} NULL,lead_id ${id} NULL,outcome VARCHAR(32) NULL,error_code VARCHAR(64) NULL,checked_at DATETIME(6) NULL,created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),UNIQUE(tenant_id,id),UNIQUE(tenant_id,id,conversation_id),UNIQUE(tenant_id,start_action_key),UNIQUE(tenant_id,active_conversation_key),INDEX(status,checked_at),FOREIGN KEY(tenant_id,version_id) REFERENCES chatflow_version(tenant_id,id),FOREIGN KEY(tenant_id,parent_run_id) REFERENCES workflow_run(tenant_id,id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),FOREIGN KEY(tenant_id,service_actor_id) REFERENCES service_actor(tenant_id,id),FOREIGN KEY(tenant_id,execution_role_id) REFERENCES \`role\`(tenant_id,id),FOREIGN KEY(tenant_id,last_message_id) REFERENCES message(tenant_id,id)) ${eng}`,
`CREATE TABLE chatflow_node_run(tenant_id ${id} NOT NULL,session_id ${id} NOT NULL,node_key ${node} NOT NULL,status VARCHAR(16) NOT NULL CHECK(status IN('pending','running','waiting','succeeded','cancelled')),invalid_attempts INT UNSIGNED NOT NULL DEFAULT 0 CHECK(invalid_attempts<=3),prompt_attempt INT NOT NULL DEFAULT -1,execution_id ${id} NULL,lease_until DATETIME(6) NULL,fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(tenant_id,session_id,node_key),FOREIGN KEY(tenant_id,session_id) REFERENCES chatflow_session(tenant_id,id),FOREIGN KEY(tenant_id,execution_id) REFERENCES agent_execution(tenant_id,id)) ${eng}`,
`CREATE TABLE chatflow_turn(tenant_id ${id} NOT NULL,session_id ${id} NOT NULL,message_id ${id} NOT NULL,node_key ${node} NOT NULL,status VARCHAR(16) NOT NULL CHECK(status IN('validated','invalid','runtime')),PRIMARY KEY(tenant_id,session_id,message_id),FOREIGN KEY(tenant_id,session_id,node_key) REFERENCES chatflow_node_run(tenant_id,session_id,node_key),FOREIGN KEY(tenant_id,message_id) REFERENCES message(tenant_id,id)) ${eng}`,
'ALTER TABLE `lead` DROP CHECK lead_chk_1,DROP CHECK lead_chk_2,DROP CHECK lead_chk_3,ADD FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),ADD FOREIGN KEY(tenant_id,qualification_session_id,conversation_id) REFERENCES chatflow_session(tenant_id,id,conversation_id),ADD FOREIGN KEY(tenant_id,source_touchpoint_id) REFERENCES touchpoint(tenant_id,id)',
`ALTER TABLE outbound_intent ADD chatflow_session_id ${id} NULL,ADD FOREIGN KEY(tenant_id,chatflow_session_id,conversation_id) REFERENCES chatflow_session(tenant_id,id,conversation_id)`,
'ALTER TABLE chatflow_session ADD FOREIGN KEY(tenant_id,lead_id) REFERENCES `lead`(tenant_id,record_id)',
]};
