import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin';
const engine='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
const states="'queued','sending','sent','failed','unknown','cancelled'";
export const conversationMigration:Migration={version:9,name:'conversation_text',statements:[
  `CREATE TABLE channel_connection(id ${id} NOT NULL,tenant_id ${id} NOT NULL,provider VARCHAR(32) NOT NULL CHECK(provider='mock_messenger'),external_account_id VARCHAR(255) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),team_id ${id} NOT NULL,PRIMARY KEY(id),UNIQUE(tenant_id,id),UNIQUE(tenant_id,provider,external_account_id),FOREIGN KEY(tenant_id,team_id) REFERENCES team(tenant_id,id)) ${engine}`,
  `CREATE TABLE contact_identity(id ${id} NOT NULL,tenant_id ${id} NOT NULL,connection_id ${id} NOT NULL,contact_id ${id} NOT NULL,external_subject_id VARCHAR(255) NOT NULL,PRIMARY KEY(id),UNIQUE(tenant_id,id),UNIQUE(tenant_id,connection_id,external_subject_id),UNIQUE(tenant_id,id,contact_id,connection_id),FOREIGN KEY(tenant_id,connection_id) REFERENCES channel_connection(tenant_id,id),FOREIGN KEY(tenant_id,contact_id) REFERENCES contact(tenant_id,record_id)) ${engine}`,
  `CREATE TABLE conversation(tenant_id ${id} NOT NULL,record_id ${id} NOT NULL,contact_id ${id} NOT NULL,contact_identity_id ${id} NOT NULL,connection_id ${id} NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'open' CHECK(status IN ('open','pending','closed')),active_identity_key ${id} GENERATED ALWAYS AS (CASE WHEN status IN ('open','pending') THEN contact_identity_id ELSE NULL END) STORED,opened_at DATETIME(6) NOT NULL,closed_at DATETIME(6) NULL,CHECK((status='closed' AND closed_at IS NOT NULL) OR (status<>'closed' AND closed_at IS NULL)),PRIMARY KEY(tenant_id,record_id),UNIQUE(tenant_id,active_identity_key),UNIQUE(tenant_id,record_id,connection_id),FOREIGN KEY(tenant_id,record_id) REFERENCES crm_record(tenant_id,id),FOREIGN KEY(tenant_id,contact_identity_id,contact_id,connection_id) REFERENCES contact_identity(tenant_id,id,contact_id,connection_id),INDEX ix_conversation_queue(tenant_id,opened_at,record_id)) ${engine}`,
  `CREATE TABLE outbound_intent(id ${id} NOT NULL,tenant_id ${id} NOT NULL,conversation_id ${id} NOT NULL,actor_kind VARCHAR(16) NOT NULL CHECK(actor_kind IN ('human','ai')),actor_id ${id} NOT NULL,account_id ${id} NULL,owner_revision BIGINT UNSIGNED NOT NULL CHECK(owner_revision>=1),text TEXT NOT NULL CHECK(CHAR_LENGTH(text) BETWEEN 1 AND 4000),status VARCHAR(16) NOT NULL CHECK(status IN (${states})),idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,provider_message_id VARCHAR(255) NULL,error_code VARCHAR(64) NULL,dispatch_token ${id} NULL,sending_at DATETIME(6) NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE(tenant_id,id),UNIQUE(tenant_id,id,conversation_id),UNIQUE(tenant_id,actor_id,idempotency_key),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),FOREIGN KEY(tenant_id,actor_id) REFERENCES principal(tenant_id,id),FOREIGN KEY(account_id) REFERENCES account(id),INDEX ix_outbound_work(status,created_at,id)) ${engine}`,
  `CREATE TABLE message(id ${id} NOT NULL,tenant_id ${id} NOT NULL,conversation_id ${id} NOT NULL,connection_id ${id} NOT NULL,provider_message_id VARCHAR(255) NULL,outbound_intent_id ${id} NULL,direction VARCHAR(16) NOT NULL CHECK(direction IN ('inbound','outbound')),text TEXT NOT NULL CHECK(CHAR_LENGTH(text) BETWEEN 1 AND 4000),occurred_at DATETIME(6) NOT NULL,received_at DATETIME(6) NOT NULL,status VARCHAR(16) NOT NULL CHECK(status IN ('received',${states})),CHECK((direction='inbound' AND status='received' AND outbound_intent_id IS NULL AND provider_message_id IS NOT NULL) OR (direction='outbound' AND status<>'received' AND outbound_intent_id IS NOT NULL)),PRIMARY KEY(id),UNIQUE(tenant_id,id),UNIQUE(tenant_id,connection_id,provider_message_id),UNIQUE(tenant_id,outbound_intent_id),FOREIGN KEY(tenant_id,conversation_id,connection_id) REFERENCES conversation(tenant_id,record_id,connection_id),FOREIGN KEY(tenant_id,outbound_intent_id,conversation_id) REFERENCES outbound_intent(tenant_id,id,conversation_id),INDEX ix_message_timeline(tenant_id,conversation_id,received_at,id)) ${engine}`,
  `CREATE TABLE mock_outbound_receipt(tenant_id ${id} NOT NULL,intent_id ${id} NOT NULL,provider_message_id VARCHAR(255) NOT NULL,PRIMARY KEY(tenant_id,intent_id),UNIQUE(tenant_id,provider_message_id),FOREIGN KEY(tenant_id,intent_id) REFERENCES outbound_intent(tenant_id,id)) ${engine}`,
]};
