import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin';
const engine='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
function subtype(name:string,cols:string){return `CREATE TABLE \`${name}\`(tenant_id ${id} NOT NULL,record_id ${id} NOT NULL,${cols},PRIMARY KEY(tenant_id,record_id),FOREIGN KEY(tenant_id,record_id) REFERENCES crm_record(tenant_id,id)) ${engine}`;}
export const crmCoreMigration:Migration={version:8,name:'crm_core',statements:[
  subtype('contact',"display_name VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,normalized_phone VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,normalized_email VARCHAR(254) COLLATE utf8mb4_bin NULL,lifecycle VARCHAR(32) NOT NULL DEFAULT 'prospect' CHECK(lifecycle IN ('prospect','customer')),customer_since DATETIME(6) NULL,contact_preference JSON NOT NULL DEFAULT (JSON_OBJECT()) CHECK(JSON_TYPE(contact_preference)='OBJECT'),INDEX ix_contact_name(tenant_id,display_name,record_id),INDEX ix_contact_phone(tenant_id,normalized_phone,record_id),INDEX ix_contact_email(tenant_id,normalized_email,record_id)"),
  subtype('company',"name VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,domain VARCHAR(253) CHARACTER SET ascii COLLATE ascii_bin NULL,INDEX ix_company_name(tenant_id,name,record_id),INDEX ix_company_domain(tenant_id,domain,record_id)"),
  subtype('activity',`kind VARCHAR(32) COLLATE utf8mb4_bin NOT NULL CHECK(kind IN ('note','task','call')),subject VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,body TEXT NULL,due_at DATETIME(6) NULL,status VARCHAR(32) NOT NULL DEFAULT 'open' CHECK(status IN ('open','done','cancelled')),related_record_id ${id} NOT NULL,FOREIGN KEY(tenant_id,related_record_id) REFERENCES crm_record(tenant_id,id),INDEX ix_activity_kind(tenant_id,kind,record_id),INDEX ix_activity_subject(tenant_id,subject,record_id),INDEX ix_activity_due(tenant_id,due_at,record_id)`),
  subtype('lead',`contact_id ${id} NOT NULL,conversation_id ${id} NULL CHECK(conversation_id IS NULL),qualification_session_id ${id} NULL CHECK(qualification_session_id IS NULL),source_touchpoint_id ${id} NULL CHECK(source_touchpoint_id IS NULL),status VARCHAR(32) COLLATE utf8mb4_bin NOT NULL DEFAULT 'new' CHECK(status IN ('new','qualifying','qualified','handed_off','accepted','disqualified')),qualification JSON NOT NULL DEFAULT (JSON_OBJECT()) CHECK(JSON_TYPE(qualification)='OBJECT'),qualified_at DATETIME(6) NULL,accepted_at DATETIME(6) NULL,UNIQUE(tenant_id,qualification_session_id),FOREIGN KEY(tenant_id,contact_id) REFERENCES contact(tenant_id,record_id),INDEX ix_lead_contact(tenant_id,contact_id,status,record_id),INDEX ix_lead_status(tenant_id,status,record_id),INDEX ix_lead_qualified(tenant_id,qualified_at,record_id)`),
]};
