import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin';
const engine='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
export const facebookMigration:Migration={version:19,name:'facebook_configuration',statements:[
 "ALTER TABLE channel_connection DROP CHECK channel_connection_chk_1, ADD CONSTRAINT ck_channel_provider CHECK(provider IN ('mock_messenger','messenger')), ADD UNIQUE KEY uq_channel_platform(tenant_id,id,provider)",
 `CREATE TABLE facebook_page(tenant_id ${id} NOT NULL,connection_id ${id} NOT NULL,app_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,page_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,name VARCHAR(255) NOT NULL,token_ciphertext TEXT NULL,version BIGINT UNSIGNED NOT NULL DEFAULT 1 CHECK(version>=1),connected_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(tenant_id,connection_id),UNIQUE(app_id,page_id),FOREIGN KEY(tenant_id,connection_id) REFERENCES channel_connection(tenant_id,id)) ${engine}`,
 `CREATE TABLE facebook_oauth_attempt(state_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,tenant_id ${id} NOT NULL,account_id ${id} NOT NULL,session_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,team_id ${id} NOT NULL,app_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,expires_at DATETIME(6) NOT NULL,consumed_at DATETIME(6) NULL,is_current BOOLEAN NOT NULL DEFAULT 1,FOREIGN KEY(tenant_id,team_id) REFERENCES team(tenant_id,id),FOREIGN KEY(account_id) REFERENCES account(id),INDEX ix_facebook_attempt(tenant_id,account_id,expires_at)) ${engine}`,
 `ALTER TABLE conversation ADD channel VARCHAR(32) NOT NULL DEFAULT 'mock_messenger', ADD channel_id ${id} GENERATED ALWAYS AS (connection_id) STORED, ADD CONSTRAINT fk_conversation_channel FOREIGN KEY(tenant_id,connection_id,channel) REFERENCES channel_connection(tenant_id,id,provider), ADD INDEX ix_conversation_channel(tenant_id,channel,opened_at,record_id), ADD INDEX ix_conversation_channel_id(tenant_id,channel_id,opened_at,record_id)`,
]};
