import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin';
const engine='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
export const intakeMigration:Migration={version:10,name:'mock_messenger_intake',statements:[
  `ALTER TABLE channel_connection ADD service_actor_id ${id} NULL,ADD credential_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,ADD UNIQUE(credential_hash),ADD FOREIGN KEY(tenant_id,service_actor_id) REFERENCES service_actor(tenant_id,id),ADD CHECK((service_actor_id IS NULL AND credential_hash IS NULL) OR (service_actor_id IS NOT NULL AND credential_hash IS NOT NULL))`,
  'ALTER TABLE contact_identity ADD display_label VARCHAR(255) NULL',
  `CREATE TABLE inbound_delivery(id ${id} NOT NULL,tenant_id ${id} NOT NULL,connection_id ${id} NOT NULL,provider_event_id VARCHAR(255) NOT NULL,payload_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,payload JSON NOT NULL CHECK(JSON_TYPE(payload)='OBJECT'),status VARCHAR(16) NOT NULL DEFAULT 'received' CHECK(status IN ('received','processed','failed')),attempts INT UNSIGNED NOT NULL DEFAULT 0,next_attempt_at DATETIME(6) NULL,lease_until DATETIME(6) NULL,fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,last_error_code VARCHAR(64) NULL,conversation_id ${id} NULL,message_id ${id} NULL,duplicate TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK(duplicate IN (0,1)),attribution VARCHAR(16) NOT NULL DEFAULT 'unknown' CHECK(attribution IN ('unknown','ctm')),received_at DATETIME(6) NOT NULL,processed_at DATETIME(6) NULL,PRIMARY KEY(id),UNIQUE(tenant_id,id),UNIQUE(tenant_id,connection_id,provider_event_id),FOREIGN KEY(tenant_id,connection_id) REFERENCES channel_connection(tenant_id,id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),FOREIGN KEY(tenant_id,message_id) REFERENCES message(tenant_id,id),INDEX ix_intake_work(status,next_attempt_at,lease_until,received_at,id)) ${engine}`,
  `CREATE TABLE touchpoint(id ${id} NOT NULL,tenant_id ${id} NOT NULL,connection_id ${id} NOT NULL,delivery_id ${id} NOT NULL,contact_id ${id} NOT NULL,conversation_id ${id} NOT NULL,channel VARCHAR(32) NOT NULL CHECK(channel='mock_messenger'),source VARCHAR(16) NOT NULL CHECK(source='ctm'),campaign_id VARCHAR(255) NULL,ad_id VARCHAR(255) NULL,occurred_at DATETIME(6) NOT NULL,received_at DATETIME(6) NOT NULL,metadata JSON NOT NULL DEFAULT (JSON_OBJECT()) CHECK(JSON_TYPE(metadata)='OBJECT'),PRIMARY KEY(id),UNIQUE(tenant_id,id),UNIQUE(tenant_id,delivery_id),FOREIGN KEY(tenant_id,connection_id) REFERENCES channel_connection(tenant_id,id),FOREIGN KEY(tenant_id,delivery_id) REFERENCES inbound_delivery(tenant_id,id),FOREIGN KEY(tenant_id,contact_id) REFERENCES contact(tenant_id,record_id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),INDEX ix_touchpoint_conversation(tenant_id,conversation_id,received_at,id)) ${engine}`,
]};
