import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin';
const ascii=(n:number)=>`VARCHAR(${n}) CHARACTER SET ascii COLLATE ascii_bin`;
const version='version BIGINT UNSIGNED NOT NULL DEFAULT 1 CHECK(version>=1)';
const engine='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
const fk=(column:string,target:string)=>`FOREIGN KEY(tenant_id,${column}) REFERENCES ${target}(tenant_id,id)`;
const key="`key` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL CHECK(REGEXP_LIKE(`key`,'^[a-z][a-z0-9_]{0,63}$')), UNIQUE(tenant_id,`key`)";
function table(name:string,columns:string,mutable=true){return `CREATE TABLE ${name}(id ${id} PRIMARY KEY,tenant_id ${id} NOT NULL,${columns},created_at DATETIME(6) NOT NULL${mutable?',updated_at DATETIME(6) NOT NULL':''},UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id) REFERENCES tenant(id)) ${engine}`;}
export const registryMigration:Migration={version:6,name:'crm_registry',statements:[
  table('object_type',`${key},label VARCHAR(255) NOT NULL,kind ${ascii(32)} NOT NULL CHECK(kind IN ('standard','custom')),schema_version BIGINT UNSIGNED NOT NULL DEFAULT 1 CHECK(schema_version>=1),archived_at DATETIME(6) NULL,${version}`),
  table('crm_record',`object_type_id ${id} NOT NULL,owner_principal_id ${id} NULL,team_id ${id} NULL,${version},owner_revision BIGINT UNSIGNED NOT NULL DEFAULT 1 CHECK(owner_revision>=1),custom_values JSON NOT NULL DEFAULT (JSON_OBJECT()) CHECK(JSON_TYPE(custom_values)='OBJECT'),archived_at DATETIME(6) NULL,${fk('object_type_id','object_type')},${fk('owner_principal_id','principal')},${fk('team_id','team')},INDEX ix_record_owner(tenant_id,object_type_id,owner_principal_id,updated_at,id),INDEX ix_record_team(tenant_id,object_type_id,team_id,updated_at,id)`),
  table('association_type',`${key},source_object_type_id ${id} NOT NULL,target_object_type_id ${id} NOT NULL,label VARCHAR(255) NOT NULL,cardinality ${ascii(32)} NOT NULL CHECK(cardinality IN ('many_to_many','one_to_many','one_to_one')),${version},${fk('source_object_type_id','object_type')},${fk('target_object_type_id','object_type')}`),
  table('association',`association_type_id ${id} NOT NULL,source_record_id ${id} NOT NULL,target_record_id ${id} NOT NULL,${fk('association_type_id','association_type')},${fk('source_record_id','crm_record')},${fk('target_record_id','crm_record')},UNIQUE(tenant_id,association_type_id,source_record_id,target_record_id),INDEX ix_assoc_source(tenant_id,source_record_id,created_at,id),INDEX ix_assoc_target(tenant_id,target_record_id,created_at,id)`,false),
  table('ownership_history',`record_id ${id} NOT NULL,from_owner_id ${id} NULL,to_owner_id ${id} NULL,from_team_id ${id} NULL,to_team_id ${id} NULL,owner_revision BIGINT UNSIGNED NOT NULL CHECK(owner_revision>=1),reason TEXT NOT NULL,actor_kind ${ascii(32)} NOT NULL CHECK(actor_kind IN ('human','ai','service','system')),actor_id ${id} NOT NULL,UNIQUE(tenant_id,record_id,owner_revision),${fk('record_id','crm_record')},${fk('from_owner_id','principal')},${fk('to_owner_id','principal')},${fk('from_team_id','team')},${fk('to_team_id','team')}`,false),
  `CREATE TABLE record_team_access(tenant_id ${id} NOT NULL,record_id ${id} NOT NULL,team_id ${id} NOT NULL,PRIMARY KEY(tenant_id,record_id,team_id),${fk('record_id','crm_record')},${fk('team_id','team')}) ${engine}`,
  table('field_policy',`role_id ${id} NOT NULL,object_type_id ${id} NOT NULL,property_key ${ascii(64)} NOT NULL,denied_actions JSON NOT NULL CHECK(JSON_TYPE(denied_actions)='ARRAY'),UNIQUE(tenant_id,role_id,object_type_id,property_key),${fk('role_id','`role`')},${fk('object_type_id','object_type')}`),
]};
