import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin',eng='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs',node='VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin',ts='created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)';
export const workflowMigration:Migration={version:13,name:'workflow_engine',statements:[
`CREATE TABLE workflow_definition(id ${id} PRIMARY KEY,tenant_id ${id} NOT NULL,\`key\` VARCHAR(64) NOT NULL,name VARCHAR(255) NOT NULL,service_actor_id ${id} NOT NULL,active_version_id ${id} NULL,enabled BOOLEAN NOT NULL DEFAULT 0 CHECK(enabled IN(0,1)),version BIGINT UNSIGNED NOT NULL DEFAULT 1,${ts},UNIQUE(tenant_id,id),UNIQUE(tenant_id,\`key\`),FOREIGN KEY(tenant_id,service_actor_id) REFERENCES service_actor(tenant_id,id)) ${eng}`,
`CREATE TABLE workflow_version(id ${id} PRIMARY KEY,tenant_id ${id} NOT NULL,definition_id ${id} NOT NULL,number INT UNSIGNED NOT NULL,graph JSON NOT NULL,execution_role_id ${id} NOT NULL,state VARCHAR(16) NOT NULL CHECK(state IN('draft','published')),published_at DATETIME(6) NULL,${ts},UNIQUE(tenant_id,id),UNIQUE(tenant_id,definition_id,id),UNIQUE(tenant_id,definition_id,number),FOREIGN KEY(tenant_id,definition_id) REFERENCES workflow_definition(tenant_id,id),FOREIGN KEY(tenant_id,execution_role_id) REFERENCES \`role\`(tenant_id,id)) ${eng}`,
'ALTER TABLE workflow_definition ADD FOREIGN KEY(tenant_id,id,active_version_id) REFERENCES workflow_version(tenant_id,definition_id,id)',
`CREATE TABLE workflow_trigger_selection(tenant_id ${id} NOT NULL,definition_id ${id} NOT NULL,event_id ${id} NOT NULL,${ts},PRIMARY KEY(tenant_id,definition_id,event_id),FOREIGN KEY(tenant_id,definition_id) REFERENCES workflow_definition(tenant_id,id)) ${eng}`,
`CREATE TABLE workflow_run(id ${id} PRIMARY KEY,tenant_id ${id} NOT NULL,definition_id ${id} NOT NULL,version_id ${id} NOT NULL,trigger_event_id ${id} NOT NULL,service_actor_id ${id} NOT NULL,current_node ${node} NOT NULL,context JSON NOT NULL,status VARCHAR(16) NOT NULL CHECK(status IN('queued','running','waiting','completed','failed','cancelled')),correlation_id VARCHAR(128) NOT NULL,error_code VARCHAR(64) NULL,attention BOOLEAN NOT NULL DEFAULT 0,cancel_pending BOOLEAN NOT NULL DEFAULT 0,cancel_attempts INT UNSIGNED NOT NULL DEFAULT 0,cancel_retry_at DATETIME(6) NULL,last_checked_at DATETIME(6) NULL,started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),finished_at DATETIME(6) NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,version_id,trigger_event_id),UNIQUE(tenant_id,definition_id,trigger_event_id),INDEX(status),FOREIGN KEY(tenant_id,definition_id,version_id) REFERENCES workflow_version(tenant_id,definition_id,id),FOREIGN KEY(tenant_id,service_actor_id) REFERENCES service_actor(tenant_id,id)) ${eng}`,
`CREATE TABLE workflow_step_run(tenant_id ${id} NOT NULL,run_id ${id} NOT NULL,node_key ${node} NOT NULL,status VARCHAR(16) NOT NULL CHECK(status IN('pending','running','succeeded','failed','cancelled')),attempt INT UNSIGNED NOT NULL DEFAULT 0,input JSON NOT NULL,output JSON NULL,action_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,lease_until DATETIME(6) NULL,fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,next_attempt_at DATETIME(6) NULL,error_code VARCHAR(64) NULL,PRIMARY KEY(tenant_id,run_id,node_key),UNIQUE(tenant_id,action_key),INDEX(status,lease_until,next_attempt_at),FOREIGN KEY(tenant_id,run_id) REFERENCES workflow_run(tenant_id,id)) ${eng}`,
`CREATE TABLE workflow_action(tenant_id ${id} NOT NULL,run_id ${id} NOT NULL,node_key ${node} NOT NULL,result JSON NOT NULL,${ts},PRIMARY KEY(tenant_id,run_id,node_key),FOREIGN KEY(tenant_id,run_id,node_key) REFERENCES workflow_step_run(tenant_id,run_id,node_key)) ${eng}`,
`CREATE TABLE workflow_wait(tenant_id ${id} NOT NULL,run_id ${id} NOT NULL,node_key ${node} NOT NULL,kind VARCHAR(16) NOT NULL CHECK(kind IN('event','timer')),event_type VARCHAR(64) NULL,match_key ${id} NULL,resume_at DATETIME(6) NOT NULL,status VARCHAR(16) NOT NULL CHECK(status IN('waiting','resumed','timed_out','cancelled')),result JSON NULL,PRIMARY KEY(tenant_id,run_id,node_key),INDEX(status,resume_at),INDEX(tenant_id,event_type,match_key),FOREIGN KEY(tenant_id,run_id,node_key) REFERENCES workflow_step_run(tenant_id,run_id,node_key)) ${eng}`,
]};
