import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin';
const engine='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
export const workspaceActivityMigration:Migration={version:22,name:'chat_workspace_snooze_activity',statements:[
  `CREATE TABLE chat_workspace_rollout(tenant_id ${id} NOT NULL,feature_key VARCHAR(32) NOT NULL,state VARCHAR(16) NOT NULL,watermark JSON NOT NULL DEFAULT (JSON_OBJECT()),updated_at DATETIME(6) NOT NULL,PRIMARY KEY(tenant_id,feature_key),CHECK(state IN ('disabled','backfilling','ready'))) ${engine}`,
  'ALTER TABLE conversation_workspace ADD snoozed_until DATETIME(6) NULL,ADD snooze_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,ADD INDEX workspace_snooze(tenant_id,snoozed_until,conversation_id)',
  `CREATE TABLE conversation_snooze(tenant_id ${id} NOT NULL,conversation_id ${id} NOT NULL,until_at DATETIME(6) NULL,revision BIGINT UNSIGNED NOT NULL DEFAULT 1,actor_principal_id ${id} NULL,reason VARCHAR(250) NULL,last_cause VARCHAR(16) NOT NULL,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(tenant_id,conversation_id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),CHECK(revision>0),CHECK(last_cause IN ('scheduled','rescheduled','deadline','inbound','manual','assignment','closed')),INDEX snooze_due(until_at,tenant_id,conversation_id)) ${engine}`,
  `CREATE TABLE conversation_activity_counter(tenant_id ${id} NOT NULL,conversation_id ${id} NOT NULL,last_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,backfilled BOOLEAN NOT NULL DEFAULT FALSE,PRIMARY KEY(tenant_id,conversation_id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id)) ${engine}`,
  `CREATE TABLE conversation_activity(tenant_id ${id} NOT NULL,id ${id} NOT NULL,conversation_id ${id} NOT NULL,activity_seq BIGINT UNSIGNED NOT NULL,source_service VARCHAR(16) NOT NULL,source_kind VARCHAR(32) NOT NULL,source_id ${id} NOT NULL,source_revision BIGINT UNSIGNED NOT NULL,kind VARCHAR(16) NOT NULL,actor_kind VARCHAR(16) NULL,actor_id ${id} NULL,occurred_at DATETIME(6) NOT NULL,recorded_at DATETIME(6) NOT NULL,payload JSON NOT NULL,PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),UNIQUE activity_order(tenant_id,conversation_id,activity_seq),UNIQUE activity_provenance(tenant_id,source_service,source_kind,source_id,source_revision,conversation_id),CHECK(activity_seq>0),CHECK(source_revision>0),CHECK(source_service IN ('chat','crm','workflow','chatflow')),CHECK(kind IN ('message','note','assignment','lifecycle','snooze','tags','automation'))) ${engine}`,
  'ALTER TABLE workflow_run ADD activity_revision BIGINT UNSIGNED NOT NULL DEFAULT 0',
]};
