import type { Migration } from './migrations.js';
const id='CHAR(36) CHARACTER SET ascii COLLATE ascii_bin';
const engine='ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs';
export const workspaceMigration:Migration={version:20,name:'chat_workspace_read_foundation',statements:[
  `CREATE TABLE conversation_workspace(tenant_id ${id} NOT NULL,conversation_id ${id} NOT NULL,latest_inbound_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,answered_inbound_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,last_message_at DATETIME(6) NOT NULL,waiting_since DATETIME(6) NULL,waiting_metric_state VARCHAR(16) NOT NULL DEFAULT 'ready',PRIMARY KEY(tenant_id,conversation_id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),CHECK(answered_inbound_seq<=latest_inbound_seq),CHECK(waiting_metric_state IN ('ready','unavailable')),INDEX workspace_latest(tenant_id,last_message_at,conversation_id),INDEX workspace_waiting(tenant_id,waiting_since,conversation_id)) ${engine}`,
  `CREATE TABLE message_workspace(tenant_id ${id} NOT NULL,message_id ${id} NOT NULL,conversation_id ${id} NOT NULL,inbound_seq BIGINT UNSIGNED NULL,reply_through_inbound_seq BIGINT UNSIGNED NULL,PRIMARY KEY(tenant_id,message_id),UNIQUE(tenant_id,conversation_id,inbound_seq),FOREIGN KEY(tenant_id,message_id) REFERENCES message(tenant_id,id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),CHECK(inbound_seq IS NULL OR inbound_seq>0),CHECK(inbound_seq IS NULL OR reply_through_inbound_seq IS NULL)) ${engine}`,
  `CREATE TABLE conversation_read_state(tenant_id ${id} NOT NULL,conversation_id ${id} NOT NULL,principal_id ${id} NOT NULL,id ${id} NOT NULL,last_read_inbound_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,revision BIGINT UNSIGNED NOT NULL DEFAULT 1,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(tenant_id,conversation_id,principal_id),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id),CHECK(revision>0),INDEX read_principal(tenant_id,principal_id,conversation_id)) ${engine}`,
  `CREATE TABLE chat_read_rollout_principal(tenant_id ${id} NOT NULL,principal_id ${id} NOT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(tenant_id,principal_id)) ${engine}`,
  `CREATE TABLE chat_read_rollout_conversation(tenant_id ${id} NOT NULL,conversation_id ${id} NOT NULL,baseline_inbound_seq BIGINT UNSIGNED NOT NULL,PRIMARY KEY(tenant_id,conversation_id),FOREIGN KEY(tenant_id,conversation_id) REFERENCES conversation(tenant_id,record_id)) ${engine}`,
  `INSERT INTO chat_read_rollout_principal SELECT tenant_id,id,UTC_TIMESTAMP(6) FROM principal WHERE kind='human'`,
  `INSERT INTO chat_read_rollout_conversation SELECT c.tenant_id,c.record_id,COUNT(m.id) FROM conversation c LEFT JOIN message m ON m.tenant_id=c.tenant_id AND m.conversation_id=c.record_id AND m.direction='inbound' GROUP BY c.tenant_id,c.record_id`,
]};
