import { chromium,expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile,mkdir,writeFile } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { randomUUID,createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
const env=parseEnv(await readFile('.env','utf8')),origin=env.APP_ORIGIN,dir='artifacts/SRC-016';
assert.equal(env.APP_ENV,'development');assert(['localhost','127.0.0.1'].includes(new URL(origin).hostname));
const fixtureId=alias=>{const h=createHash('sha256').update(`agentic-crm:identity-fixture:v1:${alias}`).digest('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-5${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`;};
const fixture=await readFile('scripts/inbox-runtime-fixture.mjs','utf8');
function assign(label,id,owned){const result=spawnSync('docker',['compose','exec','-T','api','node','--input-type=module','-e',fixture],{input:JSON.stringify({label,id,owned}),encoding:'utf8',timeout:30000});assert.equal(result.status,0,'synthetic assignment fixture: '+result.stderr.slice(-500));}
await mkdir(dir,{recursive:true});const browser=await chromium.launch({channel:process.env.E2E_BROWSER_CHANNEL??'chrome',headless:true}),contexts=[],tag=Date.now().toString(36);let stage='startup';
async function login(user){stage=`login ${user}`;const context=await browser.newContext({viewport:{width:1600,height:1200}});contexts.push(context);context.setDefaultTimeout(15000);const page=await context.newPage();await page.goto(origin);await page.getByRole('link',{name:'Đăng nhập',exact:true}).click();await page.locator('#username').fill(user);await page.locator('#password').fill(env[`SEED_${user.toUpperCase()}_PASSWORD`]);await page.locator('#kc-login').click();await page.waitForURL(origin+'/');await page.getByLabel('Chọn tổ chức',{exact:true}).waitFor();return {page,context};}
async function intake(label){const body={provider_event_id:`src016-${label}-${tag}`,provider_message_id:`src016-${label}-${tag}`,external_subject_id:`src016-synthetic-${tag}`,display_label:`SRC016 Synthetic ${label} ${tag}`,occurred_at:new Date().toISOString(),message:{type:'text',text:`Synthetic inbox inbound ${label} ${tag}`},referral:{source:'ctm',ad_id:'synthetic-ad',campaign_id:'synthetic-campaign'}};const headers={'Content-Type':'application/json','X-Connection-Id':fixtureId(`${label}:mock_connection`),Authorization:`Bearer ${env[`MOCK_${label.toUpperCase()}_TOKEN`]}`};const ack=await fetch(origin+'/api/v1/integrations/mock-messenger/deliveries',{method:'POST',headers,body:JSON.stringify(body)});assert.equal(ack.status,202);const id=(await ack.json()).data.delivery_id;for(let i=0;i<80;i++){const status=await (await fetch(origin+`/api/v1/integrations/deliveries/${id}`,{headers})).json();if(status.data.status==='processed')return status.data.conversation_id;await new Promise(r=>setTimeout(r,250));}throw new Error('intake timeout');}
async function open(page,label){await page.getByLabel('Chọn tổ chức',{exact:true}).selectOption(fixtureId(`clinic_${label}`));await page.getByRole('button',{name:'Chat',exact:true}).click();await page.getByLabel('Tìm đầu tên trong danh sách đã tải').fill(`SRC016 Synthetic ${label} ${tag}`);for(let i=0;i<20;i++){if(await page.locator('.chat-queue .record-list button').count())break;const next=page.getByRole('button',{name:'Tải thêm hội thoại',exact:true});if(await next.isVisible())await next.click();else await page.waitForTimeout(300);}await page.locator('.chat-queue .record-list button').filter({hasText:`SRC016 Synthetic ${label} ${tag}`}).click();await page.getByRole('heading',{name:`SRC016 Synthetic ${label} ${tag}`,exact:true}).waitFor();}
try{
  stage='real mock intake';const id=await intake('alpha'),betaId=await intake('beta'),tenant=fixtureId('clinic_alpha');const alpha=await login('alpha_admin'),page=alpha.page;
  stage='unassigned queue and real timeline';await open(page,'alpha');await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).toBeDisabled();await expect(page.locator('.chat-thread').getByText(`Synthetic inbox inbound alpha ${tag}`,{exact:true})).toBeVisible();
  stage='note without ownership';await page.getByRole('button',{name:'Ghi chú',exact:true}).click();await page.getByLabel('Nội dung ghi chú',{exact:true}).fill(`Synthetic note ${tag}`);await page.getByRole('button',{name:'Lưu ghi chú',exact:true}).click();await page.getByText('Đã lưu ghi chú nội bộ.',{exact:true}).waitFor();await page.getByText('Ghi chú nội bộ',{exact:true}).click();await expect(page.getByText(`Synthetic note ${tag}`,{exact:true})).toBeVisible();
  stage='owner polling and explicit review';assign('alpha',id,true);await page.getByRole('button',{name:'Phản hồi',exact:true}).click();await page.getByRole('button',{name:'Đã xem phân công mới',exact:true}).waitFor();await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Đã xem phân công mới',exact:true}).click();await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).toBeEnabled();
  stage='quick reply inserts only';await page.getByLabel('Trả lời nhanh',{exact:true}).selectOption({index:1});await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).not.toHaveValue('');let before=(await (await alpha.context.request.get(origin+`/api/v1/conversations/${id}/messages`,{headers:{'X-Tenant-Id':tenant}})).json()).data;assert.equal(before.filter(m=>m.direction==='outbound').length,0);
  stage='lost ACK retry preserves key and exactly one intent';const text=`Synthetic retry ${tag}`,keys=[];let lose=true;await page.getByLabel('Nội dung phản hồi',{exact:true}).fill(text);const path=`**/api/v1/conversations/${id}/messages`;
  await page.route(path,async route=>{if(route.request().method()!=='POST')return route.continue();keys.push(route.request().headers()['idempotency-key']);if(lose){lose=false;await route.fetch();return route.abort('failed');}return route.continue();});
  await page.getByRole('button',{name:'Gửi phản hồi',exact:true}).click();await page.getByRole('alert').filter({hasText:'Không thể hoàn tất yêu cầu.'}).waitFor();await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).toHaveValue(text);await page.getByRole('button',{name:'Kiểm tra lại yêu cầu gửi',exact:true}).click();await page.getByText('Đã tiếp nhận yêu cầu gửi.',{exact:false}).waitFor();assert.equal(keys.length,2);assert.equal(keys[0],keys[1]);await page.unroute(path);await expect(page.locator('.chat-message').filter({hasText:text}).getByText('Đã gửi',{exact:true})).toBeVisible({timeout:20000});
  const after=(await (await alpha.context.request.get(origin+`/api/v1/conversations/${id}/messages`,{headers:{'X-Tenant-Id':tenant}})).json()).data;assert.equal(after.filter(m=>m.text===text).length,1);
  stage='cursor pagination through real API';
  await page.route(`**/api/v1/conversations/${id}/messages?*`,async route=>{const url=new URL(route.request().url());url.searchParams.set('limit','1');const response=await route.fetch({url:url.toString()});await route.fulfill({response});});
  await page.getByRole('button',{name:'Tải thêm tin nhắn',exact:true}).waitFor();await page.getByRole('button',{name:'Tải thêm tin nhắn',exact:true}).click();await expect(page.locator('.chat-message').filter({hasText:text})).toBeVisible();await page.unroute(`**/api/v1/conversations/${id}/messages?*`);
  stage='unknown delivery display (fault injection)';
  await page.route(`**/api/v1/conversations/${id}/messages?*`,async route=>{const response=await route.fetch(),body=await response.json();for(const m of body.data)if(m.direction==='outbound')m.status='unknown';await route.fulfill({response,json:body});});
  await expect(page.getByText('Chưa rõ kết quả — cần kiểm tra delivery',{exact:true})).toBeVisible({timeout:15000});assert.equal(await page.getByRole('button',{name:'Gửi lại',exact:true}).count(),0);await page.unroute(`**/api/v1/conversations/${id}/messages?*`);
  stage='stale owner retains draft';await page.getByLabel('Nội dung phản hồi',{exact:true}).fill('Synthetic retained draft');assign('alpha',id,false);await page.getByRole('button',{name:'Đã xem phân công mới',exact:true}).waitFor();await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).toBeDisabled();await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).toHaveValue('Synthetic retained draft');
  stage='desktop and narrow layout';if(!await page.locator('.chat-context').evaluate(e=>e.open))await page.locator('.chat-context summary').click();await page.screenshot({path:dir+'/inbox-desktop.png',fullPage:true});await page.setViewportSize({width:760,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:dir+'/inbox-mobile.png',fullPage:true});
  stage='forbidden detail clears cached content (fault injection)';await page.route(`**/api/v1/conversations/${id}`,route=>route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:{code:'FORBIDDEN'}})}));await expect(page.locator('.chat-detail')).toHaveCount(0,{timeout:15000});await expect(page.locator('.chat-thread').getByText(`Synthetic inbox inbound alpha ${tag}`,{exact:true})).toHaveCount(0);await page.unroute(`**/api/v1/conversations/${id}`);
  const beta=await login('beta_admin');stage='Beta isolation';await open(beta.page,'beta');assert.equal((await beta.context.request.get(origin+`/api/v1/conversations/${id}`,{headers:{'X-Tenant-Id':fixtureId('clinic_beta')}})).status(),404);
  const viewer=await login('read_only');stage='read-only and tenant switch';await open(viewer.page,'alpha');await expect(viewer.page.getByLabel('Nội dung phản hồi',{exact:true})).toBeDisabled();await open(viewer.page,'beta');await expect(viewer.page.locator('.chat-thread').getByText(`Synthetic inbox inbound alpha ${tag}`,{exact:true})).toHaveCount(0);await expect(viewer.page.locator('.chat-thread').getByText(`Synthetic inbox inbound beta ${tag}`,{exact:true})).toBeVisible();
  await writeFile(dir+'/browser-facts.json',JSON.stringify({status:'PASS',chrome:browser.version(),tag,conversations:{alpha:id,beta:betaId},checks:['real intake/timeline','non-owner note','owner polling/review','quick reply no auto-send','lost ACK same key one message','real cursor pagination','unknown display injected','sent status polling','stale draft','403 cache removal injected','responsive','Beta isolation','read-only','tenant switch']},null,2));console.log('PASS: SRC-016 real Chrome/OIDC inbox, note, send/retry, polling, owner stale, tenant/permission and responsive checks.');
}catch(error){let message=String(error?.message??error);for(const [key,value] of Object.entries(env))if(/PASSWORD|SECRET|TOKEN|KEY/.test(key)&&value)message=message.replaceAll(value,'[redacted]');console.error(`FAIL SRC-016 ${stage}: ${message.slice(0,2000)}`);if(!stage.startsWith('login'))await contexts[0]?.pages()[0]?.screenshot({path:dir+'/browser-failure.png',fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{for(const context of contexts)await context.close();await browser.close();}
