import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile,mkdir,writeFile } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { randomUUID } from 'node:crypto';
const env=parseEnv(await readFile('.env','utf8')),origin=env.APP_ORIGIN;
assert.equal(env.APP_ENV,'development');assert(['localhost','127.0.0.1'].includes(new URL(origin).hostname));
await mkdir('artifacts/SRC-013',{recursive:true});
const browser=await chromium.launch({channel:process.env.E2E_BROWSER_CHANNEL??'chrome',headless:true}),contexts=[],tag=Date.now().toString(36),facts=[];
let stage='startup';
async function login(user){
  stage=`login ${user}`;const context=await browser.newContext({viewport:{width:1500,height:1100}});contexts.push(context);context.setDefaultTimeout(20000);
  const page=await context.newPage();await page.goto(origin);await page.getByRole('link',{name:'Đăng nhập',exact:true}).click();await page.locator('#password').waitFor();await page.locator('#username').fill(user);await page.locator('#password').fill(env[`SEED_${user.toUpperCase()}_PASSWORD`]);await page.locator('#kc-login').click();await page.waitForURL(origin+'/');await page.getByLabel('Chọn tổ chức',{exact:true}).waitFor();
  const memberships=(await (await context.request.get(origin+'/api/v1/me/memberships')).json()).data;
  return {page,context,memberships};
}
async function mutate(context,tenant,path,body,version){const csrf=(await (await context.request.get(origin+'/auth/csrf')).json()).data.csrf_token;return context.request.fetch(origin+path,{method:version?'PATCH':'POST',headers:{Origin:origin,'X-Tenant-Id':tenant,'X-CSRF-Token':csrf,'Idempotency-Key':randomUUID(),...(version?{'If-Match':`"${version}"`}:{})},data:body});}
async function choose(page,key){await page.getByRole('button',{name:'CRM',exact:true}).click();await page.getByRole('button',{name:key,exact:true}).click();}
async function findRecord(page,field,text){await page.getByLabel('Lọc theo',{exact:true}).selectOption(field);await page.getByLabel('Giá trị bằng',{exact:true}).fill(text);await page.getByRole('button',{name:'Áp dụng',exact:true}).click();await page.locator('.record-list button').filter({hasText:text}).click();}
async function createRecord(page,object,fill){await choose(page,object);await page.getByRole('button',{name:`Tạo ${object}`,exact:true}).click();await fill();await page.getByRole('button',{name:'Tạo record',exact:true}).click();await page.locator('.crm-record-id').waitFor();return page.locator('.crm-record-id').innerText();}
try{
  const alpha=await login('alpha_admin'),tenant=alpha.memberships[0].tenant_id,page=alpha.page;await page.getByLabel('Chọn tổ chức',{exact:true}).selectOption(tenant);await page.getByRole('heading',{name:'Dữ liệu & cộng tác'}).waitFor();
  stage='Contact CRUD and stale version UI';
  const contactName=`Synthetic M1 Alpha ${tag}`,contact=await createRecord(page,'contact',async()=>{await page.getByLabel('Tên liên hệ',{exact:true}).fill(contactName);await page.getByLabel('Số điện thoại (+84…)',{exact:true}).fill('+84900000001');await page.getByLabel('Email',{exact:true}).fill('synthetic@example.invalid');});
  const changed=await mutate(alpha.context,tenant,`/api/v1/objects/contact/records/${contact}`,{fields:{display_name:contactName+' revised'}},'1');assert.equal(changed.status(),200);
  await page.getByLabel('Tên liên hệ',{exact:true}).fill(contactName+' stale');await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click();await page.getByRole('alert').filter({hasText:'Record đã thay đổi'}).waitFor();await page.getByRole('button',{name:'Tải lại',exact:true}).click();await page.getByLabel('Tên liên hệ',{exact:true}).waitFor();await page.waitForFunction(name=>document.querySelector('input[aria-label="Tên liên hệ"]')?.value===name,contactName+' revised');
  await page.getByLabel('Tên liên hệ',{exact:true}).fill(contactName);await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click();await page.getByText('Phiên bản 3',{exact:false}).waitFor();
  facts.push({tenant,object:'contact',id:contact,name:contactName});
  stage='Company and Activity browser create';
  await createRecord(page,'company',async()=>{await page.getByLabel('Tên công ty',{exact:true}).fill(`Synthetic Company ${tag}`);await page.getByLabel('Tên miền',{exact:true}).fill('example.invalid');});
  await createRecord(page,'activity',async()=>{await page.getByLabel('Loại hoạt động',{exact:true}).selectOption('note');await page.getByLabel('Tiêu đề',{exact:true}).fill(`Synthetic activity ${tag}`);await page.getByLabel('Record liên quan',{exact:true}).fill(contact);await page.getByLabel('Nội dung',{exact:true}).fill('Synthetic test note');});
  stage='Custom metadata property and form/view';
  await page.getByRole('button',{name:'Cấu hình dữ liệu',exact:true}).click();await page.getByLabel('Đối tượng cấu hình',{exact:true}).selectOption('appointment');
  const existing=(await (await alpha.context.request.get(origin+'/api/v1/object-types/appointment/properties',{headers:{'X-Tenant-Id':tenant}})).json()).data;
  if(!existing.some(p=>p.key==='m1_review')){
    await page.getByText('Thêm thuộc tính',{exact:true}).click();await page.getByLabel('Key thuộc tính',{exact:true}).fill('m1_review');await page.getByLabel('Nhãn thuộc tính',{exact:true}).fill('Review state');await page.getByLabel('Kiểu dữ liệu',{exact:true}).selectOption('enum');await page.getByLabel('Các lựa chọn, ngăn cách bằng dấu phẩy',{exact:true}).fill('ready,review');await page.getByRole('button',{name:'Tạo thuộc tính',exact:true}).click();await page.getByRole('cell',{name:'Review state m1_review',exact:false}).waitFor();
  }
  const form=page.locator('form').filter({has:page.getByRole('heading',{name:'Biểu mẫu mặc định',exact:true})});
  await form.getByLabel('Thêm trường',{exact:true}).waitFor();
  if(!await form.locator('.crm-actions span').filter({hasText:'Review state'}).count())await form.getByLabel('Thêm trường',{exact:true}).selectOption('m1_review');
  const [savedForm]=await Promise.all([page.waitForResponse(r=>r.url().endsWith('/forms/default')&&r.request().method()==='PUT'),form.getByRole('button',{name:'Lưu biểu mẫu',exact:true}).click()]);assert.equal(savedForm.status(),200);
  const view=page.locator('form').filter({has:page.getByRole('heading',{name:'Saved view mặc định',exact:true})});await view.getByLabel('Sắp xếp',{exact:true}).selectOption('title');const [savedView]=await Promise.all([page.waitForResponse(r=>r.url().endsWith('/views/default')&&r.request().method()==='PUT'),view.getByRole('button',{name:'Lưu view',exact:true}).click()]);assert.equal(savedView.status(),200);
  stage='Custom objects CRUD and association';
  const appointment=await createRecord(page,'Appointment',async()=>{await page.getByLabel('Tên cuộc hẹn',{exact:true}).fill(`Synthetic Appointment ${tag}`);await page.getByLabel('Trạng thái hẹn',{exact:true}).selectOption('planned');await page.getByLabel('Review state',{exact:true}).selectOption('ready');});
  const service=await createRecord(page,'ServiceOffering',async()=>{await page.getByLabel('Tên dịch vụ',{exact:true}).fill(`Synthetic Service ${tag}`);await page.getByLabel('Nhóm dịch vụ',{exact:true}).selectOption('consultation');await page.getByLabel('Giá niêm yết',{exact:true}).fill('125.5');});
  await choose(page,'Appointment');await findRecord(page,'title',`Synthetic Appointment ${tag}`);await page.getByLabel('Loại liên kết',{exact:true}).selectOption('appointment_service');await page.getByLabel('Record đích',{exact:true}).selectOption(service);await page.getByRole('button',{name:'Thêm liên kết',exact:true}).click();await page.getByText(`→ ${service}`,{exact:true}).waitFor();await page.getByRole('button',{name:'Dùng saved view',exact:true}).click();
  facts.push({tenant,object:'appointment',id:appointment,name:`Synthetic Appointment ${tag}`});
  stage='Lead draft and explicit consent qualification';
  await choose(page,'lead');await page.getByRole('button',{name:'Tạo lead',exact:true}).click();await page.getByLabel('Liên hệ',{exact:true}).selectOption(contact);await page.getByRole('button',{name:'Tạo Lead',exact:true}).click();await page.getByRole('heading',{name:'Nhu cầu & đồng ý liên hệ',exact:true}).waitFor();
  const lead=await page.locator('.crm-record-id').innerText();await page.getByLabel('Dịch vụ quan tâm',{exact:true}).fill('Synthetic service interest');await page.getByLabel('Tóm tắt nhu cầu',{exact:true}).fill('Synthetic need only');await page.getByLabel('Phương thức liên hệ',{exact:true}).selectOption('messenger');await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await page.getByText('Phiên bản 2',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Xác nhận đủ điều kiện',exact:true}).click();await page.getByRole('alert').filter({hasText:'qualification.contact_permission'}).waitFor();await page.getByLabel('Khách đã đồng ý được liên hệ',{exact:true}).check();await page.getByLabel('Bằng chứng đồng ý (ghi nhận thủ công)',{exact:true}).fill('Synthetic explicit permission for fixture');await page.getByRole('button',{name:'Xác nhận đủ điều kiện',exact:true}).click();await page.locator('.crm-detail .crm-badge').filter({hasText:'qualified'}).waitFor();
  facts.push({tenant,object:'lead',id:lead,status:'qualified'});
  stage='Admin team and role configuration';
  await page.getByRole('button',{name:'Quản trị',exact:true}).click();await page.getByRole('button',{name:'Nhóm',exact:true}).click();await page.getByRole('button',{name:'Thêm mới',exact:true}).click();await page.getByLabel('Tên',{exact:true}).fill(`Synthetic M1 team ${tag}`);await page.getByLabel('Mục đích',{exact:true}).selectOption('general');await page.getByRole('button',{name:'Lưu cấu hình',exact:true}).click();await page.getByText(`Synthetic M1 team ${tag}`,{exact:true}).waitFor();
  await page.getByRole('button',{name:'Vai trò',exact:true}).click();await page.getByRole('button',{name:'Thêm mới',exact:true}).click();await page.getByLabel('Tên',{exact:true}).fill(`Synthetic M1 role ${tag}`);await page.getByLabel('Key',{exact:true}).fill(`m1_${tag}`);await page.getByRole('button',{name:'Thêm quyền',exact:true}).click();await page.getByRole('button',{name:'Lưu cấu hình',exact:true}).click();await page.getByText(`Synthetic M1 role ${tag}`,{exact:true}).waitFor();
  await page.getByRole('button',{name:'Thành viên',exact:true}).click();await page.getByRole('columnheader',{name:'Thông tin'}).waitFor();await page.getByRole('button',{name:'AI Agents',exact:true}).click();await page.getByText('Intake AI',{exact:true}).waitFor();
  await choose(page,'contact');await findRecord(page,'display_name',contactName);await page.screenshot({path:'artifacts/SRC-013/crm-desktop.png',fullPage:true});await page.setViewportSize({width:760,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:'artifacts/SRC-013/crm-mobile.png',fullPage:true});
  const beta=await login('beta_admin'),betaTenant=beta.memberships[0].tenant_id;await beta.page.getByLabel('Chọn tổ chức',{exact:true}).selectOption(betaTenant);
  stage='Beta standard CRUD and cross tenant denial';const betaContact=await createRecord(beta.page,'contact',async()=>{await beta.page.getByLabel('Tên liên hệ',{exact:true}).fill(`Synthetic M1 Beta ${tag}`);});facts.push({tenant:betaTenant,object:'contact',id:betaContact,name:`Synthetic M1 Beta ${tag}`});assert.equal((await beta.context.request.get(origin+`/api/v1/objects/contact/records/${contact}`,{headers:{'X-Tenant-Id':betaTenant}})).status(),404);
  stage='Viewer read, hidden writes/admin and tenant-switch isolation';const viewer=await login('read_only');assert.equal(viewer.memberships.length,2);
  for(const t of [tenant,betaTenant]){await viewer.page.getByLabel('Chọn tổ chức',{exact:true}).selectOption(t);await viewer.page.getByRole('heading',{name:'Dữ liệu & cộng tác'}).waitFor();await choose(viewer.page,'contact');await viewer.page.locator('.record-list').waitFor();assert.equal(await viewer.page.getByRole('button',{name:'Tạo contact',exact:true}).count(),0);assert.equal(await viewer.page.getByRole('button',{name:'Quản trị',exact:true}).count(),0);assert.equal((await mutate(viewer.context,t,'/api/v1/objects/contact/records',{fields:{display_name:'Should never persist'}})).status(),403);if(t===betaTenant)assert.equal(await viewer.page.getByText(contactName,{exact:true}).count(),0);}
  await writeFile('artifacts/SRC-013/browser-facts.json',JSON.stringify({tag,facts,chrome:browser.version()},null,2));console.log(`PASS: M1 real OIDC Alpha/Beta/viewer; standard/custom CRUD, projection query/view/form, association, draft/consent, stale409, admin teams/roles, responsive layout and tenant isolation. Chrome ${browser.version()}.`);
}catch(error){let message=String(error?.message??'unknown');for(const [key,value] of Object.entries(env))if(/PASSWORD|SECRET|KEY/.test(key)&&value)message=message.replaceAll(value,'[redacted]');console.error(`FAIL: M1 browser at ${stage}: ${message.slice(0,2500)}`);if(!stage.startsWith('login'))await contexts[0]?.pages()[0]?.screenshot({path:'artifacts/SRC-013/browser-failure.png',fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{for(const context of contexts)await context.close();await browser.close();}
