import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile,writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID,randomBytes,createHash } from 'node:crypto';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const id=alias=>{if(alias==='alpha:human:sales_binh')return '00900000-0000-5000-a000-000000000001';const h=createHash('sha256').update(`agentic-crm:identity-fixture:v1:${alias}`).digest('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-5${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`;};
export async function releaseDemo({env,artifacts,prefix,run}){
 const origin=env.APP_ORIGIN;assert.equal(origin,'http://localhost:18080');assert.match(env.COMPOSE_PROJECT_NAME,/^agentic-crm-release-/);
 const tenant=id('clinic_alpha'),beta=id('clinic_beta'),admin=id('alpha:human:alpha_admin'),ai=id('alpha:intake_ai'),seller=id('alpha:human:sales_binh');
 const sql=(query,params=[])=>{const code=`import {databaseSource} from './dist/kernel/database/data-source.js';const s=databaseSource();await s.initialize();try{console.log(JSON.stringify(await s.query(${JSON.stringify(query)},${JSON.stringify(params)})));}finally{await s.destroy();}`;return JSON.parse(run('docker',['compose','exec','-T','api','node','--input-type=module'],{input:code,encoding:'utf8',stdio:['pipe','pipe','pipe']}));};
 const until=async(fn,label,ms=60000)=>{const deadline=Date.now()+ms;while(Date.now()<deadline){const result=await fn();if(result)return result;await delay(500);}throw new Error(`DEMO_TIMEOUT:${label}`);};
 if(prefix==='resume'){
  const facts=JSON.parse(await readFile(join(artifacts,'upgrade-demo.json'),'utf8'));
  await until(()=>sql('SELECT id FROM workflow_run WHERE id=? AND status=\'completed\'',[facts.timerRun]).length,'persisted timer resumes',90000);
  assert.equal(sql("SELECT id FROM outbox_event WHERE aggregate_id=? AND event_type='workflow.completed'",[facts.timerRun]).length,1);
  await writeFile(join(artifacts,'resume-demo.json'),JSON.stringify({status:'PASS',timerRun:facts.timerRun,completedEvents:1}));return;
 }
 const browser=await chromium.launch({channel:process.env.E2E_BROWSER_CHANNEL||'chrome',headless:true});const contexts=[];let page,stage='login';
 const login=async user=>{const context=await browser.newContext({viewport:{width:1440,height:1000}});contexts.push(context);const p=await context.newPage();page=p;p.setDefaultTimeout(20000);await p.goto(origin);await p.getByRole('link',{name:'Đăng nhập',exact:true}).click();await p.locator('#username').fill(user);await p.locator('#password').fill(env[`SEED_${user.toUpperCase()}_PASSWORD`]);await p.locator('#kc-login').click();await p.waitForURL(origin+'/');await p.getByLabel('Chọn tổ chức',{exact:true}).waitFor();return {context,page:p};};
 const data=async(response,status=200)=>{assert.equal(response.status(),status,`HTTP_${response.status()}_EXPECTED_${status}`);return (await response.json()).data;};
 const get=(context,path,t=tenant)=>context.request.get(origin+'/api/v1/'+path,{headers:{'X-Tenant-Id':t}});
 const mutate=async(context,method,path,body,version)=>{const csrf=(await(await context.request.get(origin+'/auth/csrf')).json()).data.csrf_token;return data(await context.request.fetch(origin+'/api/v1/'+path,{method,headers:{Origin:origin,'X-Tenant-Id':tenant,'X-CSRF-Token':csrf,'Idempotency-Key':randomUUID(),...(version?{'If-Match':`"${version}"`}:{})},data:body}),method==='POST'&&(path==='admin/roles'||path==='admin/teams'||path==='chatflows'||path==='workflows'||path.endsWith('/versions'))?201:200);};
 try{
  const a=await login('alpha_admin');page=a.page;const context=a.context;
  stage='M2 fixture configuration';
  const permissions=[...['read','design','publish','operate'].map(action=>({resource:'automation',action,scope:'all'})),...['read','reply','assign','takeover'].map(action=>({resource:'conversation',action,scope:'all'})),...['create','read','qualify','handoff','accept'].map(action=>({resource:'lead',action,scope:'all'})),...['create','read','share'].map(action=>({resource:'contact',action,scope:'all'})),{resource:'integration',action:'deliver',scope:'all'}];
  const role=(await mutate(context,'POST','admin/roles',{key:'release_m2',name:'Synthetic release M2',permissions})).id;
  const intakeTeam=(await mutate(context,'POST','admin/teams',{name:'Synthetic release intake',purpose:'chat'})).id,salesTeam=(await mutate(context,'POST','admin/teams',{name:'Synthetic release Sales',purpose:'sales'})).id;
  const members=await data(await get(context,'admin/memberships?limit=100'));
  for(const [principal,team] of [[admin,intakeTeam],[seller,salesTeam]]){const m=members.find(m=>m.principal_id===principal);assert(m);await mutate(context,'PATCH',`admin/memberships/${m.id}`,{role_ids:[...m.role_ids,role],team_ids:[...m.team_ids,team]},m.version);}
  // Private local configuration fixture: there is no public service credential provisioning API in M2.
  const service=randomUUID(),connection=randomUUID(),token=randomBytes(32).toString('hex');
  sql("INSERT INTO service_actor(id,tenant_id,`key`,role_id,created_at,updated_at) VALUES (?,?,'release_m2',?,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))",[service,tenant,role]);
  sql('INSERT INTO principal_role VALUES (?,?,?)',[tenant,ai,role]);sql('INSERT INTO team_member(tenant_id,team_id,principal_id) VALUES (?,?,?)',[tenant,intakeTeam,ai]);
  sql('UPDATE agent_policy SET allowed_tools=?,allowed_actions=?,version=version+1 WHERE tenant_id=? AND id=?',[JSON.stringify(['conversation.propose_reply','qualification.save','crm.read_contact','routing.request_human']),JSON.stringify(['conversation.read','conversation.reply','contact.read','lead.create','lead.qualify','routing.request_human']),tenant,id('alpha:policy')]);
  const credentials=new Map();const connectionInsert=(c,t=token)=>{sql("INSERT INTO channel_connection(id,tenant_id,provider,external_account_id,team_id,service_actor_id,credential_hash) VALUES (?,?,'mock_messenger',?,?,?,?)",[c,tenant,c,intakeTeam,service,createHash('sha256').update(t).digest('hex')]);credentials.set(c,t);};connectionInsert(connection);
  const collect=(key,type,next,choices)=>({key,type:'collect',config:{variable_key:key,value_type:type,required:true,prompt:'Synthetic administrative question',...(choices?{choices}:{})},next});
  const cf=(await mutate(context,'POST','chatflows',{key:'release_m2',name:'Synthetic release qualification'})).id;
  const graph={entry_node:'service_interest',nodes:[collect('service_interest','string','need_summary'),collect('need_summary','string','preferred_contact_method'),collect('preferred_contact_method','enum','contact_permission',['messenger','phone']),collect('contact_permission','boolean','validate'),{key:'validate',type:'validate_qualification',config:{on_valid:'lead',on_invalid:'human'}},{key:'lead',type:'upsert_lead',config:{},next:'end'},{key:'human',type:'request_human',config:{reason:'qualification_incomplete',target_chat_team:intakeTeam},next:'end'},{key:'end',type:'end',config:{outcome:'qualified'}}]};
  const version=(await mutate(context,'POST',`chatflows/${cf}/versions`,{graph})).id;await mutate(context,'POST',`chatflows/${cf}/versions/1/publish`,{},'1');
  const workflow=async(key,conn,nodes)=>{const d=(await mutate(context,'POST','workflows',{key,name:'Synthetic release workflow',service_actor_id:service})).id;await mutate(context,'POST',`workflows/${d}/versions`,{graph:{trigger:{event_type:'conversation.created',connection_id:conn},entry_node:nodes[0].key,nodes},execution_role_id:role});await mutate(context,'POST',`workflows/${d}/versions/1/publish`,{},'1');await mutate(context,'PATCH',`workflows/${d}`,{enabled:true},'2');return d;};
  const definition=await workflow('release_m2',connection,[{key:'route',type:'assign_owner',config:{record_id:{ref:'trigger.aggregate_id'},team_id:intakeTeam,capability:'chat',preference:'ai'},next:'start'},{key:'start',type:'start_chatflow',config:{conversation_id:{ref:'trigger.aggregate_id'},chatflow_version_id:version},next:'wait'},{key:'wait',type:'wait_event',config:{event_type:'chatflow.completed',match_key:{ref:'outputs.start.session_id'},timeout_seconds:3600},next:'handoff',on_timeout:'end'},{key:'handoff',type:'request_lead_handoff',config:{lead_id:{ref:'outputs.wait.lead_id'},target_team_id:salesTeam},next:'sale'},{key:'sale',type:'wait_event',config:{event_type:'lead.accepted',match_key:{ref:'outputs.handoff.handoff_id'},timeout_seconds:900},next:'end',on_timeout:'end'},{key:'end',type:'end',config:{outcome:'accepted'}}]);
  const inbound=async(alias,index,text,conn=connection)=>{const body={provider_event_id:`release-${alias}-${index}`,provider_message_id:`release-${alias}-${index}`,external_subject_id:`release-${alias}`,display_label:`Synthetic release ${alias}`,occurred_at:new Date().toISOString(),message:{type:'text',text},referral:{source:'ctm',ad_id:'synthetic-release-ad'}};
   const post=b=>fetch(origin+'/api/v1/integrations/mock-messenger/deliveries',{method:'POST',headers:{'Content-Type':'application/json','X-Connection-Id':conn,Authorization:`Bearer ${credentials.get(conn)}`},body:JSON.stringify(b)});
   const response=await post(body);assert.equal(response.status,202);const ack=(await response.json()).data;
   if(index===1){const replay=await post(body);assert.equal(replay.status,202);assert.deepEqual((await replay.json()).data,ack);}
   return until(()=>sql("SELECT conversation_id,message_id FROM inbound_delivery WHERE id=? AND status='processed'",[ack.delivery_id])[0],'intake');};
  stage='AI qualification through worker';const first=await inbound('ai',1,'Synthetic service');
  const session=await until(()=>sql("SELECT id,parent_run_id FROM chatflow_session WHERE conversation_id=? AND status='waiting_message'",[first.conversation_id])[0],'AI session');
  for(const [index,text]of [[2,'Synthetic administrative need'],[3,'messenger'],[4,'đồng ý']])await inbound('ai',index,text);
  const handed=await until(()=>sql("SELECT record_id FROM `lead` WHERE qualification_session_id=? AND status='handed_off'",[session.id])[0],'Sales handoff');
  assert.equal(sql('SELECT owner_principal_id FROM crm_record WHERE id=?',[first.conversation_id])[0].owner_principal_id,ai);
  stage='Sales browser accept';const s=await login('sales_binh');await s.page.getByLabel('Chọn tổ chức',{exact:true}).selectOption(tenant);await s.page.getByRole('button',{name:'Sales',exact:true}).click();await s.page.getByLabel('Sales team ID').fill(salesTeam);await s.page.getByRole('button',{name:'Lọc team',exact:true}).click();await s.page.getByRole('button',{name:/^Synthetic service/}).click();await s.page.getByRole('button',{name:'Nhận Lead',exact:true}).click();await s.page.getByText('Đã nhận Lead.',{exact:true}).waitFor();await s.page.screenshot({path:join(artifacts,`${prefix}-sales.png`),fullPage:true});
  await until(()=>sql("SELECT id FROM workflow_run WHERE id=? AND status='completed'",[session.parent_run_id])[0],'accepted parent');
  assert.equal(sql('SELECT accepted_by_principal_id FROM lead_handoff WHERE lead_id=?',[handed.record_id])[0].accepted_by_principal_id,seller);
  assert.equal(sql('SELECT owner_principal_id FROM crm_record WHERE id=?',[first.conversation_id])[0].owner_principal_id,ai);
  assert.equal(sql('SELECT lifecycle FROM contact WHERE record_id=(SELECT contact_id FROM `lead` WHERE record_id=?)',[handed.record_id])[0].lifecycle,'prospect');
  assert.equal((await get(context,`leads/${handed.record_id}`,beta)).status(),403);
  stage='Human takeover and completion';page=a.page;const second=await inbound('human',1,'Synthetic service');await until(()=>sql("SELECT id FROM chatflow_session WHERE conversation_id=? AND status='waiting_message'",[second.conversation_id])[0],'Human session');const consent=await inbound('human',2,'đồng ý');
  await page.reload();await page.getByLabel('Chọn tổ chức',{exact:true}).selectOption(tenant);await page.getByRole('button',{name:'Chat',exact:true}).click();await page.getByRole('button',{name:/Synthetic release human/}).click();await page.getByText('Phân công & lịch sử',{exact:true}).click();await page.getByRole('button',{name:'Tiếp quản hội thoại',exact:true}).click();await page.getByLabel('Dịch vụ quan tâm',{exact:true}).fill('Synthetic service');await page.getByRole('textbox',{name:/^Nhu cầu của khách/}).fill('Synthetic administrative need');await page.getByRole('combobox',{name:/^Cách liên hệ/}).selectOption('messenger');await page.getByRole('combobox',{name:/^Tin nhắn đồng ý liên hệ/}).selectOption(consent.message_id);await page.getByRole('checkbox',{name:/Tôi đã kiểm tra/}).check();await page.getByRole('button',{name:'Hoàn tất nhu cầu',exact:true}).click();await page.getByText('Đã xác nhận nhu cầu và đồng ý liên hệ.',{exact:true}).waitFor();await page.screenshot({path:join(artifacts,`${prefix}-human.png`),fullPage:true});
  await until(()=>sql("SELECT h.id FROM lead_handoff h JOIN `lead` l ON l.tenant_id=h.tenant_id AND l.record_id=h.lead_id WHERE l.conversation_id=?",[second.conversation_id])[0],'Human handoff');assert.equal(sql('SELECT owner_principal_id FROM crm_record WHERE id=?',[second.conversation_id])[0].owner_principal_id,admin);
  let timerRun;
  if(prefix==='upgrade'){
   stage='persisted restart timer';const c=randomUUID();connectionInsert(c,randomBytes(32).toString('hex'));const d=await workflow('release_timer',c,[{key:'timer',type:'wait_timer',config:{duration_seconds:30},next:'end'},{key:'end',type:'end',config:{outcome:'resumed'}}]);await inbound('timer',1,'Synthetic restart',c);timerRun=(await until(()=>sql("SELECT id FROM workflow_run WHERE definition_id=? AND status='waiting'",[d])[0],'timer wait')).id;
  }
  await writeFile(join(artifacts,`${prefix}-demo.json`),JSON.stringify({status:'PASS',chrome:browser.version(),checks:['real OIDC','credential CTM intake and duplicate ACK','worker AI qualification','Sales UI acceptance','parent completion','owner independence/prospect','cross-tenant denial','Human UI takeover/completion and handoff'],definition,lead:handed.record_id,run:session.parent_run_id,timerRun},null,2));
 }catch(e){await page?.screenshot({path:join(artifacts,`${prefix}-failure.png`),fullPage:true}).catch(()=>{});throw new Error(`DEMO_${stage}`);}
 finally{for(const c of contexts)await c.close();await browser.close();}
}
