import { chromium,expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile,mkdir,writeFile } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { randomUUID,createHash } from 'node:crypto';
const env=parseEnv(await readFile('.env','utf8')),origin=env.APP_ORIGIN,dir='artifacts/SRC-017';
assert.equal(env.APP_ENV,'development');assert(['localhost','127.0.0.1'].includes(new URL(origin).hostname));
const fixtureId=alias=>{const h=createHash('sha256').update(`agentic-crm:identity-fixture:v1:${alias}`).digest('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-5${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`;};
await mkdir(dir,{recursive:true});const browser=await chromium.launch({channel:process.env.E2E_BROWSER_CHANNEL??'chrome',headless:true}),contexts=[],tag=Date.now().toString(36);let stage='startup';
async function login(user){stage=`login ${user}`;const context=await browser.newContext({viewport:{width:1600,height:1200}});contexts.push(context);context.setDefaultTimeout(15000);const page=await context.newPage();await page.goto(origin);await page.getByRole('link',{name:'Đăng nhập',exact:true}).click();await page.locator('#username').fill(user);await page.locator('#password').fill(env[`SEED_${user.toUpperCase()}_PASSWORD`]);await page.locator('#kc-login').click();await page.waitForURL(origin+'/');await page.getByLabel('Chọn tổ chức',{exact:true}).waitFor();return {page,context};}
async function intake(label){const body={provider_event_id:`src017-${label}-${tag}`,provider_message_id:`src017-${label}-${tag}`,external_subject_id:`src017-synthetic-${tag}`,display_label:`SRC017 Synthetic ${label} ${tag}`,occurred_at:new Date().toISOString(),message:{type:'text',text:`Synthetic inbox inbound ${label} ${tag}`},referral:{source:'ctm',ad_id:'synthetic-ad',campaign_id:'synthetic-campaign'}};const headers={'Content-Type':'application/json','X-Connection-Id':fixtureId(`${label}:mock_connection`),Authorization:`Bearer ${env[`MOCK_${label.toUpperCase()}_TOKEN`]}`};const ack=await fetch(origin+'/api/v1/integrations/mock-messenger/deliveries',{method:'POST',headers,body:JSON.stringify(body)});assert.equal(ack.status,202);const id=(await ack.json()).data.delivery_id;for(let i=0;i<80;i++){const status=await (await fetch(origin+`/api/v1/integrations/deliveries/${id}`,{headers})).json();if(status.data.status==='processed')return status.data.conversation_id;await new Promise(r=>setTimeout(r,250));}throw new Error('intake timeout');}
async function open(page,label){await page.getByLabel('Chọn tổ chức',{exact:true}).selectOption(fixtureId(`clinic_${label}`));await page.getByRole('button',{name:'Chat',exact:true}).click();await page.getByLabel('Tìm đầu tên trong danh sách đã tải').fill(`SRC017 Synthetic ${label} ${tag}`);for(let i=0;i<20;i++){if(await page.locator('.chat-queue .record-list button').count())break;const next=page.getByRole('button',{name:'Tải thêm hội thoại',exact:true});if(await next.isVisible())await next.click();else await page.waitForTimeout(300);}await page.locator('.chat-queue .record-list button').filter({hasText:`SRC017 Synthetic ${label} ${tag}`}).click();await page.getByRole('heading',{name:`SRC017 Synthetic ${label} ${tag}`,exact:true}).waitFor();}async function mutate(context,tenant,path,body,version,key=randomUUID()){
  const csrf=(await (await context.request.get(origin+'/auth/csrf')).json()).data.csrf_token;
  return context.request.post(origin+path,{headers:{'X-Tenant-Id':tenant,'Origin':origin,'X-CSRF-Token':csrf,'Idempotency-Key':key,'If-Match':`"${version}"`},data:body});
}
try{
  const id=await intake('alpha'),betaId=await intake('beta'),tenant=fixtureId('clinic_alpha'),principal=fixtureId('alpha:human:alpha_admin'),alpha=await login('alpha_admin'),page=alpha.page;
  const detail=async()=>(await (await alpha.context.request.get(origin+`/api/v1/conversations/${id}`,{headers:{'X-Tenant-Id':tenant}})).json()).data;
  stage='real targets and policy-disabled AI';await open(page,'alpha');await page.getByText('Phân công & lịch sử',{exact:true}).click();await expect(page.getByLabel('Owner mới',{exact:true})).toBeEnabled();assert(await page.getByLabel('Owner mới',{exact:true}).locator('option:disabled').count()>0);
  stage='Human takeover';await page.getByRole('button',{name:'Tiếp quản hội thoại',exact:true}).click();await page.getByText('Đã cập nhật phân công.',{exact:true}).waitFor();assert.equal((await detail()).owner_principal_id,principal);await page.getByRole('button',{name:'Đã xem phân công mới',exact:true}).click();await expect(page.getByLabel('Nội dung phản hồi',{exact:true})).toBeEnabled();
  stage='lost assignment ACK replays original version/key';let lose=true;const keys=[],versions=[],path=`**/api/v1/records/${id}/assignment`;
  await page.route(path,async route=>{keys.push(route.request().headers()['idempotency-key']);versions.push(route.request().headers()['if-match']);if(lose){lose=false;await route.fetch();return route.abort('failed');}return route.continue();});
  await page.getByLabel('Owner mới',{exact:true}).selectOption('');const before=await detail();await page.getByRole('button',{name:'Lưu phân công',exact:true}).click();await page.getByRole('button',{name:'Kiểm tra lại phân công',exact:true}).waitFor();await page.getByRole('button',{name:'Kiểm tra lại phân công',exact:true}).click();await page.getByText('Đã cập nhật phân công.',{exact:true}).waitFor();assert.equal(keys.length,2);assert.equal(keys[0],keys[1]);assert.equal(versions[0],versions[1]);assert.equal((await detail()).owner_revision,String(BigInt(before.owner_revision)+1n));assert.equal((await detail()).owner_principal_id,null);await page.unroute(path);
  stage='stale assignment review';await page.getByLabel('Owner mới',{exact:true}).selectOption(principal);const version=(await detail()).version;assert.equal((await mutate(alpha.context,tenant,`/api/v1/records/${id}/assignment`,{owner_principal_id:principal,reason:'manual'},version)).status(),200);await page.getByRole('button',{name:'Xem lại phân công hiện tại',exact:true}).waitFor();await expect(page.getByRole('button',{name:'Lưu phân công',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Xem lại phân công hiện tại',exact:true}).click();await expect(page.getByRole('button',{name:'Lưu phân công',exact:true})).toBeEnabled();
  stage='tenant and viewer boundaries';const viewer=await login('read_only');await open(viewer.page,'alpha');await expect(viewer.page.getByText('Phân công & lịch sử',{exact:true})).toHaveCount(0);const denied=await mutate(viewer.context,tenant,`/api/v1/conversations/${id}/takeover`,{reason:'human_takeover'},(await detail()).version);assert.equal(denied.status(),403);const beta=await login('beta_admin');await open(beta.page,'beta');assert.equal((await beta.context.request.get(origin+`/api/v1/records/${id}/assignment-targets`,{headers:{'X-Tenant-Id':fixtureId('clinic_beta')}})).status(),404);
  stage='layout and history';await page.screenshot({path:dir+'/routing-desktop.png',fullPage:true});await page.setViewportSize({width:760,height:1100});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByText('Phân công & lịch sử',{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/routing-mobile.png',fullPage:false});
  await writeFile(dir+'/browser-facts.json',JSON.stringify({status:'PASS',chrome:browser.version(),tag,conversations:{alpha:id,beta:betaId},checks:['real target eligibility','policy-disabled AI','takeover','lost ACK same key/version one assignment','stale review','viewer denied','cross-tenant denied','history','responsive']},null,2));console.log('PASS SRC-017: real Chrome/OIDC assignment, takeover, receipt replay, stale review and isolation.');
}catch(error){let message=String(error?.message??error);for(const [key,value] of Object.entries(env))if(/PASSWORD|SECRET|TOKEN|KEY/.test(key)&&value)message=message.replaceAll(value,'[redacted]');console.error(`FAIL SRC-017 ${stage}: ${message.slice(0,2000)}`);if(!stage.startsWith('login'))await contexts[0]?.pages()[0]?.screenshot({path:dir+'/browser-failure.png',fullPage:true}).catch(()=>{});process.exitCode=1;}
finally{for(const context of contexts)await context.close();await browser.close();}
